"""Model cache reason codes."""

from ..wire_model import WireEnum


class CacheReferenceReason(WireEnum):
    """What keeps a cached artifact from being removed."""

    RECIPE_INSTALLATION = "recipe-installation"
    RUNNING_MODEL = "running-model"
    SAVED_PROFILE = "saved-profile"


class ModelCacheBlockerCode(WireEnum):
    """Why a model download plan is blocked or waiting."""

    INSUFFICIENT_RESERVED_STORAGE = "insufficient-reserved-storage"
    MODEL_NOT_CACHED = "model-not-cached"
    RECIPE_NOT_CACHED = "recipe-not-cached"


class ModelCacheCode(WireEnum):
    """Model cache resolution, storage, removal and operation problems."""

    ACCESS_RECHECK_UNAVAILABLE = "model_cache.access_recheck_unavailable"
    ARTIFACT_COUNT = "model_cache.artifact_count"
    ARTIFACT_DUPLICATE = "model_cache.artifact_duplicate"
    ARTIFACT_INVALID = "model_cache.artifact_invalid"
    ARTIFACT_MISSING = "model_cache.artifact_missing"
    ARTIFACT_UNVERIFIED = "model_cache.artifact_unverified"
    CANCELLATION_INVALID = "model_cache.cancellation_invalid"
    CANCELLATION_KEY_REUSED = "model_cache.cancellation_key_reused"
    CAPACITY = "model_cache.capacity"
    COVERAGE_INCOMPLETE = "model_cache.coverage_incomplete"
    CREDENTIALS_MISSING = "model_cache.credentials_missing"
    CURSOR_INVALID = "model_cache.cursor_invalid"
    DEPENDENCY_COUNT = "model_cache.dependency_count"
    DIGEST_INVALID = "model_cache.digest_invalid"
    DIGEST_MISMATCH = "model_cache.digest_mismatch"
    DIGEST_SIZE_CONFLICT = "model_cache.digest_size_conflict"
    DOCUMENT_UNREADABLE = "model_cache.document_unreadable"
    DOWNLOAD_BLOCKED = "model_cache.download_blocked"
    ENTRY_MISSING = "model_cache.entry_missing"
    FIXTURE_SOURCES_FORBIDDEN = "model_cache.fixture_sources_forbidden"
    IDENTITY_CONFLICT = "model_cache.identity_conflict"
    IDENTITY_MISMATCH = "model_cache.identity_mismatch"
    INTERRUPTED = "model_cache.interrupted"
    LOCK_UNAVAILABLE = "model_cache.lock_unavailable"
    MANIFEST_IDENTITY_MISMATCH = "model_cache.manifest_identity_mismatch"
    MANIFEST_INVALID = "model_cache.manifest_invalid"
    MANIFEST_TOO_LARGE = "model_cache.manifest_too_large"
    MODEL_CONTENT_DIGESTS_INVALID = "model_cache.model_content_digests_invalid"
    MODEL_DEFINITION_INVALID = "model_cache.model_definition_invalid"
    MODEL_DEFINITION_MISSING = "model_cache.model_definition_missing"
    MODEL_DEPENDENCY_CYCLE = "model_cache.model_dependency_cycle"
    MODEL_PIN_INVALID = "model_cache.model_pin_invalid"
    MODEL_VARIANT_INVALID = "model_cache.model_variant_invalid"
    NOT_CANCELLABLE = "model_cache.not_cancellable"
    OBJECT_BUSY = "model_cache.object_busy"
    OPERATION_FAILED = "model_cache.operation_failed"
    OPERATION_MISSING = "model_cache.operation_missing"
    OPERATION_NOT_RETRYABLE = "model_cache.operation_not_retryable"
    OPERATION_UNREADABLE = "model_cache.operation_unreadable"
    PAYLOAD_INVALID = "model_cache.payload_invalid"
    PIN_MISMATCH = "model_cache.pin_mismatch"
    PIN_REQUIRED = "model_cache.pin_required"
    PLAN_INVALID = "model_cache.plan_invalid"
    RANGE_INVALID = "model_cache.range_invalid"
    RATE_LIMITED = "model_cache.rate_limited"
    RECIPE_IDENTITY_AMBIGUOUS = "model_cache.recipe_identity_ambiguous"
    RECIPE_IDENTITY_INVALID = "model_cache.recipe_identity_invalid"
    RECIPE_IDENTITY_MISSING = "model_cache.recipe_identity_missing"
    RECIPE_INVALID = "model_cache.recipe_invalid"
    RECIPE_MODEL_MISSING = "model_cache.recipe_model_missing"
    RECIPE_REVISION_INVALID = "model_cache.recipe_revision_invalid"
    RECIPE_REVISION_MISSING = "model_cache.recipe_revision_missing"
    REDIRECT_FORBIDDEN = "model_cache.redirect_forbidden"
    RELEASE_ASSET_IDENTITY_CONFLICT = "model_cache.release_asset_identity_conflict"
    RELEASE_METADATA_INVALID = "model_cache.release_metadata_invalid"
    REMOVAL_CHILD_FAILED = "model_cache.removal_child_failed"
    REMOVAL_CHILD_INVALID = "model_cache.removal_child_invalid"
    REMOVAL_CHILD_MISMATCH = "model_cache.removal_child_mismatch"
    REMOVAL_CHILD_MISSING = "model_cache.removal_child_missing"
    REMOVAL_CHILD_PENDING = "model_cache.removal_child_pending"
    REMOVAL_INVALID = "model_cache.removal_invalid"
    REMOVAL_PATH_UNSAFE = "model_cache.removal_path_unsafe"
    REMOVAL_PLAN_INVALID = "model_cache.removal_plan_invalid"
    REMOVAL_REFERENCED = "model_cache.removal_referenced"
    REMOVAL_SCOPE_CHANGED = "model_cache.removal_scope_changed"
    REMOVAL_SCOPE_INVALID = "model_cache.removal_scope_invalid"
    REMOVAL_SCOPE_UNAVAILABLE = "model_cache.removal_scope_unavailable"
    REMOVAL_WAIT = "model_cache.removal_wait"
    REQUEST_KEY_INVALID = "model_cache.request_key_invalid"
    REQUEST_KEY_REUSED = "model_cache.request_key_reused"
    REVIEW_INVALID = "model_cache.review_invalid"
    REVIEW_UNAVAILABLE = "model_cache.review_unavailable"
    REVISION_INVALID = "model_cache.revision_invalid"
    REVISION_MISSING = "model_cache.revision_missing"
    SCHEMA_UNSUPPORTED = "model_cache.schema_unsupported"
    SELECTOR_AMBIGUOUS = "model_cache.selector_ambiguous"
    SELECTOR_INVALID = "model_cache.selector_invalid"
    SELECTOR_MISSING = "model_cache.selector_missing"
    SOURCE_GONE = "model_cache.source_gone"
    SOURCE_INVALID = "model_cache.source_invalid"
    SOURCE_SIZE_MISMATCH = "model_cache.source_size_mismatch"
    SOURCE_TRUNCATED = "model_cache.source_truncated"
    SOURCE_UNAVAILABLE = "model_cache.source_unavailable"
    SOURCE_UNSUPPORTED = "model_cache.source_unsupported"
    SOURCE_UNTRUSTED = "model_cache.source_untrusted"
    STALE_PLAN = "model_cache.stale_plan"
    UNAVAILABLE = "model_cache.unavailable"
    UPSTREAM_CHECK_BUDGET_EXHAUSTED = "model_cache.upstream_check_budget_exhausted"
    UPSTREAM_CHECK_FAILED = "model_cache.upstream_check_failed"
    UPSTREAM_REVISION_INVALID = "model_cache.upstream_revision_invalid"
