"""Recipes reason codes."""

from ..wire_model import WireEnum


class RecipeBuildCode(WireEnum):
    """Recipe image build planning and recording problems."""

    ADAPTER_UNAVAILABLE = "build.adapter_unavailable"
    CANCELLATION_PENDING = "build.cancellation_pending"
    CAPABILITY_MISSING = "build.capability_missing"
    CAPACITY_BUSY = "build.capacity_busy"
    CAPACITY_CONTRACT_INVALID = "build.capacity_contract_invalid"
    CONSUMER_BUSY = "build.consumer_busy"
    CONSUMER_INVALID = "build.consumer_invalid"
    CONTRACT_INVALID = "build.contract_invalid"
    DEPENDENCIES_STALE = "build.dependencies_stale"
    EVIDENCE_INVALID = "build.evidence_invalid"
    IMAGE_SIZE_INVALID = "build.image_size_invalid"
    INPUT_MISMATCH = "build.input_mismatch"
    INSUFFICIENT_DISK = "build.insufficient_disk"
    INSUFFICIENT_MEMORY = "build.insufficient_memory"
    INVENTORY_MISSING = "build.inventory_missing"
    INVENTORY_STALE = "build.inventory_stale"
    NETWORK_CAPABILITY_MISSING = "build.network_capability_missing"
    NODE_INCOMPATIBLE = "build.node_incompatible"
    NODE_UNKNOWN = "build.node_unknown"
    PLAN_INVALID = "build.plan_invalid"
    PRODUCER_INVALID = "build.producer_invalid"
    RECIPE_UNRESOLVED = "build.recipe_unresolved"
    RESOLUTION_STALE = "build.resolution_stale"
    RESOURCES_INVALID = "build.resources_invalid"
    RESULT_CONFLICT = "build.result_conflict"
    RUNTIME_CHANGED = "build.runtime_changed"
    SECURITY_INVALID = "build.security_invalid"
    SOURCE_INVALID = "build.source_invalid"
    SOURCE_UNAVAILABLE = "build.source_unavailable"
    STATE = "build.state"
    SHARED_CONSUMERS = "build.shared_consumers"


class RecipeImageCode(WireEnum):
    """Runtime image availability, preparation and cache-removal problems."""

    ACTION_INVALID = "recipe_image.action_invalid"
    BUILD_CANCELLED = "recipe_image.build_cancelled"
    BUILD_CAPACITY_WAIT = "recipe_image.build_capacity_wait"
    BUILD_FAILED = "recipe_image.build_failed"
    BUILD_INPUT_MISSING = "recipe_image.build_input_missing"
    BUILD_INVALID = "recipe_image.build_invalid"
    BUILD_UNAVAILABLE = "recipe_image.build_unavailable"
    BUILD_WAIT = "recipe_image.build_wait"
    BUILDER_BUSY = "recipe_image.builder_busy"
    BUILDER_OCCUPIED = "recipe_image.builder_occupied"
    CANCEL_BUSY = "recipe_image.cancel_busy"
    CANCEL_REQUEST_KEY_REUSED = "recipe_image.cancel_request_key_reused"
    CANCELLATION_INVALID = "recipe_image.cancellation_invalid"
    CLAIM_LOST = "recipe_image.claim_lost"
    DATABASE_BUSY = "recipe_image.database_busy"
    IDENTITY_CONFLICT = "recipe_image.identity_conflict"
    IDENTITY_INVALID = "recipe_image.identity_invalid"
    INSUFFICIENT_DISK = "recipe_image.insufficient_disk"
    INSUFFICIENT_MEMORY = "recipe_image.insufficient_memory"
    METADATA_REFRESH_FAILED = "recipe_image.metadata_refresh_failed"
    METADATA_REFRESH_UNAVAILABLE = "recipe_image.metadata_refresh_unavailable"
    MODEL_CACHE_FAILED = "recipe_image.model_cache_failed"
    MODEL_CACHE_INVALID = "recipe_image.model_cache_invalid"
    MODEL_CACHE_UNAVAILABLE = "recipe_image.model_cache_unavailable"
    MODEL_CHILD_CANCELLED = "recipe_image.model_child_cancelled"
    MODEL_CHILD_MISSING = "recipe_image.model_child_missing"
    NO_BUILDER = "recipe_image.no_builder"
    NOT_CANCELLABLE = "recipe_image.not_cancellable"
    NOT_RETRYABLE = "recipe_image.not_retryable"
    OPERATION_INVALID = "recipe_image.operation_invalid"
    REMOVAL_EVIDENCE_UNAVAILABLE = "recipe_image.removal_evidence_unavailable"
    OPERATION_MISSING = "recipe_image.operation_missing"
    PREPARATION_FAILED = "recipe_image.preparation_failed"
    PREPARATION_EXHAUSTED = "recipe_image.preparation_exhausted"
    PREPARING = "recipe_image.preparing"
    RECIPE_INVALID = "recipe_image.recipe_invalid"
    RECIPE_UNAVAILABLE = "recipe_image.recipe_unavailable"
    REMOVAL_CHOICE_INVALID = "recipe_image.removal_choice_invalid"
    REMOVAL_FAILED = "recipe_image.removal_failed"
    REMOVAL_REFERENCED = "recipe_image.removal_referenced"
    REMOVAL_SCOPE_LIMITED = "recipe_image.removal_scope_limited"
    REQUEST_KEY_REUSED = "recipe_image.request_key_reused"
    RUNTIME_INVALID = "recipe_image.runtime_invalid"
    SELECTOR_AMBIGUOUS = "recipe_image.selector_ambiguous"
    SELECTOR_INVALID = "recipe_image.selector_invalid"
    SELECTOR_MISSING = "recipe_image.selector_missing"
    SOURCE_POLICY_REFUSED = "recipe_image.source_policy_refused"
    SUPERSEDED_BY_NEWER_REVISION = "recipe_image.superseded_by_newer_revision"
    WAITING_FOR_MODEL = "recipe_image.waiting_for_model"
    WAITING_FOR_WORKER = "recipe_image.waiting_for_worker"


class RecipeOperationCode(WireEnum):
    """Recipe operation conflicts."""

    RECIPE_OPERATION_CONFLICT = "recipe.operation_conflict"
    EVIDENCE_UNPROVEN = "recipe.evidence_unproven"


class RecipePackageCode(WireEnum):
    """Recipe package download and verification problems."""

    CACHE_UNAVAILABLE = "recipe_package.cache_unavailable"
    DIGEST_MISMATCH = "recipe_package.digest_mismatch"
    DOCUMENT_INCOMPATIBLE = "recipe_package.document_incompatible"
    EXTRACT_INVALID = "recipe_package.extract_invalid"
    NOT_FOUND = "recipe_package.not_found"
    PACKAGE_INVALID = "recipe_package.package_invalid"
    RELEASE_INCOMPLETE = "recipe_package.release_incomplete"
    RELEASE_INVALID = "recipe_package.release_invalid"
    RESPONSE_INVALID = "recipe_package.response_invalid"
    SCHEMA_INCOMPATIBLE = "recipe_package.schema_incompatible"
    SNAPSHOT_CHANGED = "recipe_package.snapshot_changed"
    UNAVAILABLE = "recipe_package.unavailable"
    URI_INVALID = "recipe_package.uri_invalid"
    URL_INSECURE = "recipe_package.url_insecure"
    URL_INVALID = "recipe_package.url_invalid"


class RecipeUpdateCode(WireEnum):
    """Recipe update batch problems."""

    CLAIM_LOST = "recipe_update.claim_lost"
    OBSERVATION_INVALID = "recipe_update.observation_invalid"
    OPERATION_INVALID = "recipe_update.operation_invalid"
    REQUEST_KEY_REUSED = "recipe_update.request_key_reused"
    SCOPE_INVALID = "recipe_update.scope_invalid"
    CANCEL_EFFECT_UNKNOWN = "recipe-update.cancel-effect-unknown"


class ReconcileCode(WireEnum):
    """Why an installation reconcile is blocked."""

    ACTIVE_EFFECT_UNKNOWN = "reconcile.active_effect_unknown"
    AGENT_UNAVAILABLE = "reconcile.agent_unavailable"
    CAPACITY_BUSY = "reconcile.capacity_busy"
    INSTALL_PROVENANCE_MISMATCH = "reconcile.install_provenance_mismatch"
    INSTALL_PROVENANCE_UNAVAILABLE = "reconcile.install_provenance_unavailable"
    INSTALLATION_EFFECT_UNKNOWN = "reconcile.installation_effect_unknown"
    INSTALLATION_IDENTITY_MISMATCH = "reconcile.installation_identity_mismatch"
    INSTALLATION_IDENTITY_UNAVAILABLE = "reconcile.installation_identity_unavailable"
    MEMBERSHIP_CHANGED = "reconcile.membership_changed"
    OPERATION_ACTIVE = "reconcile.operation_active"
    RANK_MEMBERSHIP_CHANGED = "reconcile.rank_membership_changed"
    RECIPE_REVISION_UNAVAILABLE = "reconcile.recipe_revision_unavailable"
    SPEC_IDENTITY_MISMATCH = "reconcile.spec_identity_mismatch"
