"""Sources reason codes."""

from ..wire_model import WireEnum


class SourceBundleCode(WireEnum):
    """Recipe source bundle validation problems."""

    ARCHIVE_TOO_LARGE = "bundle.archive_too_large"
    DIGEST_INVALID = "bundle.digest_invalid"
    DIGEST_MISMATCH = "bundle.digest_mismatch"
    DUPLICATE_PATH = "bundle.duplicate_path"
    EMPTY = "bundle.empty"
    ENTRY_FORBIDDEN = "bundle.entry_forbidden"
    EXPANDED_TOO_LARGE = "bundle.expanded_too_large"
    FILE_INVALID = "bundle.file_invalid"
    FILE_TOO_LARGE = "bundle.file_too_large"
    INVALID_ARCHIVE = "bundle.invalid_archive"
    MANIFEST_INVALID = "bundle.manifest_invalid"
    METADATA_MISMATCH = "bundle.metadata_mismatch"
    NOT_FOUND = "bundle.not_found"
    PATH_FORBIDDEN = "bundle.path_forbidden"
    PATH_TOO_LONG = "bundle.path_too_long"
    READ_FAILED = "bundle.read_failed"
    SIZE_MISMATCH = "bundle.size_mismatch"
    STORAGE_COLLISION = "bundle.storage_collision"
    STORAGE_CONFLICT = "bundle.storage_conflict"
    STORAGE_UNAVAILABLE = "bundle.storage_unavailable"
    TOO_MANY_FILES = "bundle.too_many_files"
    DIGEST_MISMATCH_ = "source.digest_mismatch"


class SourcePolicyCode(WireEnum):
    """Findings of the build source policy (Dockerfile and Compose rules)."""

    CAPABILITIES = "compose.capabilities"
    DEVICES = "compose.devices"
    HOST_BIND = "compose.host_bind"
    HOST_NAMESPACE = "compose.host_namespace"
    INVALID = "compose.invalid"
    PRIVILEGED = "compose.privileged"
    SERVICE_INVALID = "compose.service_invalid"
    TOO_LARGE = "compose.too_large"
    UNCONFINED = "compose.unconfined"
    VOLUMES_INVALID = "compose.volumes_invalid"
    ADD_FORBIDDEN = "dockerfile.add_forbidden"
    BASE_PLACEHOLDER = "dockerfile.base_placeholder"
    BASE_UNPINNED = "dockerfile.base_unpinned"
    BUILD_PRIVILEGE = "dockerfile.build_privilege"
    COPY_BASE_PLACEHOLDER = "dockerfile.copy_base_placeholder"
    COPY_BASE_UNPINNED = "dockerfile.copy_base_unpinned"
    COPY_INVALID = "dockerfile.copy_invalid"
    COPY_PATH = "dockerfile.copy_path"
    FROM_MISSING = "dockerfile.from_missing"
    HEREDOC_FORBIDDEN = "dockerfile.heredoc_forbidden"
    INVALID_UTF8 = "dockerfile.invalid_utf8"
    MISSING = "dockerfile.missing"
    NETWORK_HOST = "dockerfile.network_host"
    ONBUILD_FORBIDDEN = "dockerfile.onbuild_forbidden"
    ROOT_USER = "dockerfile.root_user"
    SECRET_MOUNT = "dockerfile.secret_mount"
