"""Strict, transport-neutral contracts for high-level Run and Switch work.

The low-level recipe routes remain useful primitives, but a client selecting a
model and a Spark group must be able to review one Controller-owned outcome
plan.  These contracts deliberately contain intent and evidence only.  They
do not encode a browser gesture, a button, or a transport-specific authority.
"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, StringConstraints, model_validator

from .preparation_contract import RolloutPreparation

_UUID_PATTERN = (
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-"
    r"[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
)
_NODE_PATTERN = r"^spk_[0-9a-f]{32}$"
_DIGEST_PATTERN = r"^[0-9a-f]{64}$"

UuidId = Annotated[str, StringConstraints(pattern=_UUID_PATTERN)]
NodeId = Annotated[str, StringConstraints(pattern=_NODE_PATTERN)]
Digest = Annotated[str, StringConstraints(pattern=_DIGEST_PATTERN)]
Alias = Annotated[
    str,
    StringConstraints(
        min_length=1,
        max_length=128,
        pattern=r"^[a-z0-9](?:[a-z0-9._-]{0,126}[a-z0-9])?$",
    ),
]


class _StrictModel(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True, allow_inf_nan=False)


class InvocationMetadata(_StrictModel):
    """Context for audit and tracing which has no decision-making authority."""

    origin: Annotated[
        str,
        StringConstraints(
            min_length=1,
            max_length=64,
            pattern=r"^[A-Za-z0-9][A-Za-z0-9._:/-]{0,63}$",
        ),
    ] = "operator"
    correlation_id: UuidId | None = None
    reason: Annotated[str, StringConstraints(max_length=256)] | None = None
    context: dict[
        Annotated[str, StringConstraints(min_length=1, max_length=64)],
        Annotated[str, StringConstraints(max_length=256)],
    ] = Field(default_factory=dict, max_length=16)


class SparkGroupNode(_StrictModel):
    node_id: NodeId
    rank: int = Field(ge=0, le=31)
    role: Annotated[str, StringConstraints(min_length=1, max_length=64)]
    endpoint_owner: bool = False


class SparkGroup(_StrictModel):
    """A complete, rank-labelled Spark group selected by the operator."""

    nodes: list[SparkGroupNode] = Field(min_length=1, max_length=32)

    @model_validator(mode="after")
    def validate_group(self) -> SparkGroup:
        node_ids = [node.node_id for node in self.nodes]
        ranks = [node.rank for node in self.nodes]
        if len(node_ids) != len(set(node_ids)):
            raise ValueError("Spark group node IDs must be unique")
        if sorted(ranks) != list(range(len(ranks))):
            raise ValueError("Spark group ranks must be contiguous from zero")
        if sum(node.endpoint_owner for node in self.nodes) != 1:
            raise ValueError("Spark group must have exactly one endpoint owner")
        return self


class RunSwitchPreviewRequest(_StrictModel):
    schema_version: Literal[2] = 2
    model_version_sha256: Digest
    recipe_revision_id: UuidId
    spark_group: SparkGroup
    alias: Alias
    action: Literal["run", "switch"] = "run"
    retention: Literal["retain-cached", "reclaim-unreferenced"] = "retain-cached"
    invocation: InvocationMetadata = Field(default_factory=InvocationMetadata)


class RunSwitchApplyRequest(RunSwitchPreviewRequest):
    # Preview binding and idempotency are generated by the Controller when a
    # caller uses the one-step Run/Switch route.  They remain accepted for
    # advanced clients that explicitly replay a reviewed plan.
    plan_digest: Digest | None = None
    request_key: UuidId | None = None


class RunSwitchStopPreviewRequest(_StrictModel):
    schema_version: Literal[2] = 2
    run_id: UuidId
    invocation: InvocationMetadata = Field(default_factory=InvocationMetadata)


class RunSwitchStopApplyRequest(RunSwitchStopPreviewRequest):
    plan_digest: Digest | None = None
    request_key: UuidId | None = None


class RunSwitchReason(_StrictModel):
    code: Annotated[str, StringConstraints(min_length=1, max_length=96)]
    detail: Annotated[str, StringConstraints(min_length=1, max_length=512)]
    severity: Literal["blocker", "warning", "info"]
    scope: Literal[
        "model",
        "recipe",
        "mapping",
        "group",
        "node",
        "artifact",
        "freshness",
        "conflict",
        "operation",
    ]
    node_ids: list[NodeId] = Field(default_factory=list, max_length=32)
    stale: bool = False


class FreshnessEvidence(_StrictModel):
    source: Annotated[str, StringConstraints(min_length=1, max_length=96)]
    state: Literal["fresh", "stale", "unknown"]
    observed_at: datetime | None = None
    age_seconds: float | None = Field(default=None, ge=0)
    maximum_age_seconds: int | None = Field(default=None, ge=1, le=86_400)
    evidence_digest: Digest | None = None


class CapabilityEvidence(_StrictModel):
    """One capability's declaration and evidence, kept separate by owner."""

    name: Annotated[str, StringConstraints(min_length=1, max_length=96)]
    declared: bool | None
    evidence: Literal["tested", "observed", "not-tested", "unknown"]
    support: Literal["supported", "unsupported", "unknown"]
    evidence_digest: Digest | None = None
    detail: Annotated[str, StringConstraints(max_length=256)] | None = None


class SparkFitNode(_StrictModel):
    node_id: NodeId
    rank: int = Field(ge=0, le=31)
    role: Annotated[str, StringConstraints(min_length=1, max_length=64)]
    allowed: bool
    disk_required_bytes: int | None = Field(default=None, ge=0)
    disk_free_bytes: int | None = Field(default=None, ge=0)
    disk_free_after_bytes: int | None = None
    memory_required_bytes: int | None = Field(default=None, ge=0)
    memory_available_bytes: int | None = Field(default=None, ge=0)
    memory_free_after_bytes: int | None = None
    blockers: list[RunSwitchReason] = Field(default_factory=list, max_length=32)
    warnings: list[RunSwitchReason] = Field(default_factory=list, max_length=32)


class SparkFit(_StrictModel):
    allowed: bool
    nodes: list[SparkFitNode] = Field(min_length=1, max_length=32)
    blockers: list[RunSwitchReason] = Field(default_factory=list, max_length=64)
    warnings: list[RunSwitchReason] = Field(default_factory=list, max_length=64)


class ArtifactStorageImpact(_StrictModel):
    """Byte impact with unknown values preserved as unknown, never guessed."""

    required_bytes: int | None = Field(default=None, ge=0)
    reused_bytes: int = Field(default=0, ge=0)
    copied_bytes: int = Field(default=0, ge=0)
    missing_nas_bytes: int | None = Field(default=None, ge=0)
    missing_spark_bytes: int | None = Field(default=None, ge=0)
    reclaimable_bytes: int = Field(default=0, ge=0)
    reclaimed_bytes: int = Field(default=0, ge=0)
    nas_coverage: Literal["complete", "partial", "unknown"]
    spark_coverage: Literal["complete", "partial", "unknown"]
    retention: Literal["retain-cached", "reclaim-unreferenced"]
    running_coverage: Literal["complete", "partial", "unknown"] = "unknown"
    artifact_digests: list[Digest] = Field(default_factory=list, max_length=256)
    reclaimable_digests: list[Digest] = Field(default_factory=list, max_length=256)


class BuildSourceEvidence(_StrictModel):
    state: Literal["available", "missing", "unknown"]
    source_bundle_sha256: Digest | None = None
    detail: Annotated[str, StringConstraints(max_length=256)] | None = None


class BuildCompatibilityEvidence(_StrictModel):
    expected_architecture: Annotated[
        str, StringConstraints(min_length=1, max_length=64)
    ]
    observed_architecture: Annotated[str, StringConstraints(max_length=64)] | None = None
    state: Literal["compatible", "incompatible", "unknown"]
    evidence_digest: Digest | None = None
    detail: Annotated[str, StringConstraints(max_length=256)] | None = None


class RuntimeImageStorageImpact(_StrictModel):
    build_id: UuidId | None
    image_digest: Annotated[str, StringConstraints(pattern=r"^sha256:[0-9a-f]{64}$")] | None
    oci_layout_sha256: Digest | None = None
    image_bytes: int | None = Field(default=None, ge=0)
    required_bytes: int | None = Field(default=None, ge=0)
    reused_bytes: int = Field(default=0, ge=0)
    copied_bytes: int = Field(default=0, ge=0)
    missing_nas_bytes: int | None = Field(default=None, ge=0)
    missing_spark_bytes: int | None = Field(default=None, ge=0)
    missing_image_distribution_bytes: int | None = Field(default=None, ge=0)
    nas_coverage: Literal["complete", "partial", "unknown"]
    spark_coverage: Literal["complete", "partial", "unknown"]
    running_coverage: Literal["complete", "partial", "unknown"] = "unknown"
    reclaimable_bytes: int = Field(default=0, ge=0)
    reclaimable_digests: list[Digest] = Field(default_factory=list, max_length=256)


class RecipeBuildEvidence(_StrictModel):
    state: Literal["available", "planned", "building", "failed", "missing", "incompatible", "unknown"]
    build_id: UuidId | None
    # A pending build is still bound to an immutable source/build input and a
    # deterministically selected Controller builder.  The OCI output digest
    # is filled only after the durable build child records its receipt.
    build_input_sha256: Digest | None = None
    builder_node_id: NodeId | None = None
    image_digest: Annotated[str, StringConstraints(pattern=r"^sha256:[0-9a-f]{64}$")] | None
    image_bytes: int | None = Field(default=None, ge=0)
    oci_layout_sha256: Digest | None = None
    source: BuildSourceEvidence
    compatibility: BuildCompatibilityEvidence
    runtime: RuntimeImageStorageImpact
    detail: Annotated[str, StringConstraints(max_length=512)] | None = None


class MappingSelection(_StrictModel):
    mapping_id: UuidId | None
    mapping_generation: int | None = Field(default=None, ge=1)
    topology_name: Annotated[str, StringConstraints(min_length=1, max_length=64)]
    parameters: dict[str, object] = Field(default_factory=dict, max_length=128)
    placement_digest: Digest
    action: Literal["reuse", "create"]
    nodes: list[SparkGroupNode] = Field(min_length=1, max_length=32)


class StopImpact(_StrictModel):
    run_id: UuidId
    alias: Alias
    state: Annotated[str, StringConstraints(min_length=1, max_length=24)]
    node_ids: list[NodeId] = Field(min_length=1, max_length=32)
    reserved_bytes: int = Field(ge=0)
    plan_digest: Digest


RunSwitchPhaseKind = Literal[
    "transfer",
    "verify",
    "prepare",
    "cleanup",
    "stop",
    "start",
    "final_verify",
]


class RunSwitchPhase(_StrictModel):
    index: int = Field(ge=0, le=31)
    kind: RunSwitchPhaseKind
    # ``kind`` stays in the shared lifecycle vocabulary.  This typed purpose
    # distinguishes Controller-side OCI preparation from target installation
    # while keeping Activity's generic phase enum stable.
    subphase: Literal[
        "container-build",
        "model-download",
        "runtime-image",
        "runtime-plan",
        "target-copy",
        "runtime-install",
    ] | None = None
    state: Literal["planned", "retained", "skipped", "blocked"]
    node_ids: list[NodeId] = Field(default_factory=list, max_length=32)
    operation_digest: Digest | None = None
    detail: Annotated[str, StringConstraints(min_length=1, max_length=256)]


class RunSwitchPlan(_StrictModel):
    schema_version: Literal[2] = 2
    generated_at: datetime
    action: Literal["run", "switch", "stop"]
    model_version_sha256: Digest | None
    recipe_revision_id: UuidId | None
    recipe_content_sha256: Digest | None
    alias: Alias | None
    run_id: UuidId | None
    spark_group: SparkGroup
    mapping: MappingSelection | None
    installation_id: UuidId | None
    installation_state: Annotated[str, StringConstraints(min_length=1, max_length=24)] | None
    recipe_build_id: UuidId | None
    image_digest: Annotated[str, StringConstraints(pattern=r"^sha256:[0-9a-f]{64}$")] | None
    start_plan_digest: Digest | None
    model_capabilities: list[CapabilityEvidence] = Field(max_length=128)
    recipe_capabilities: list[CapabilityEvidence] = Field(max_length=128)
    freshness: list[FreshnessEvidence] = Field(max_length=128)
    fit_current: SparkFit
    fit_after_stop: SparkFit | None
    # ``fit`` is the current admission view retained as a compact client
    # affordance; the two named views above make stop-before-prepare decisions
    # explicit for reviewers and profile callers.
    fit: SparkFit
    storage: ArtifactStorageImpact
    runtime_storage: RuntimeImageStorageImpact
    build: RecipeBuildEvidence
    preparation: RolloutPreparation | None = None
    conflicts: list[RunSwitchReason] = Field(max_length=128)
    stops: list[StopImpact] = Field(max_length=128)
    reclaimed_bytes: int = Field(ge=0)
    phases: list[RunSwitchPhase] = Field(min_length=1, max_length=16)
    allowed: bool
    blockers: list[RunSwitchReason] = Field(max_length=128)
    warnings: list[RunSwitchReason] = Field(max_length=128)
    invocation: InvocationMetadata
    plan_digest: Digest
    stop_before_prepare: bool = False
    stop_before_transfer: bool = False


class RunSwitchMemberProgress(_StrictModel):
    node_id: NodeId
    phase: RunSwitchPhaseKind | None = None
    state: Literal["pending", "running", "succeeded", "failed", "unknown"]
    completed_bytes: int = Field(default=0, ge=0)
    total_bytes: int | None = Field(default=None, ge=0)
    error: Annotated[str, StringConstraints(max_length=256)] | None = None


class RunSwitchProgress(_StrictModel):
    phase_index: int = Field(ge=0, le=31)
    phase_count: int = Field(ge=1, le=32)
    phase: RunSwitchPhaseKind | None
    state: Literal["queued", "running", "succeeded", "failed", "unknown"]
    completed_bytes: int = Field(default=0, ge=0)
    total_bytes: int | None = Field(default=None, ge=0)
    total_bytes_known: bool
    subphase: Literal[
        "container-build",
        "model-download",
        "runtime-image",
        "runtime-plan",
        "target-copy",
        "runtime-install",
    ] | None = None
    members: list[RunSwitchMemberProgress] = Field(min_length=1, max_length=32)

    @model_validator(mode="after")
    def total_bytes_state_is_consistent(self) -> RunSwitchProgress:
        if self.total_bytes_known != (self.total_bytes is not None):
            raise ValueError("progress total byte knowledge is inconsistent")
        if self.total_bytes is not None and self.completed_bytes > self.total_bytes:
            raise ValueError("progress completed bytes exceed total bytes")
        return self


class RunSwitchOperation(_StrictModel):
    schema_version: Literal[2] = 2
    operation_id: UuidId
    kind: Literal["recipe.run-switch.v2", "recipe.stop.v2"]
    action: Literal["run", "switch", "stop"]
    state: Annotated[str, StringConstraints(min_length=1, max_length=32)]
    plan_digest: Digest
    request_key: UuidId
    node_ids: list[NodeId] = Field(min_length=1, max_length=32)
    current_phase: RunSwitchPhaseKind | None = None
    completed_phases: list[RunSwitchPhaseKind] = Field(max_length=16)
    progress: RunSwitchProgress
    status_reason: Annotated[str, StringConstraints(max_length=512)] | None = None
    result: dict[str, object] | None = None


__all__ = [
    "Alias",
    "ArtifactStorageImpact",
    "BuildCompatibilityEvidence",
    "BuildSourceEvidence",
    "CapabilityEvidence",
    "Digest",
    "FreshnessEvidence",
    "InvocationMetadata",
    "MappingSelection",
    "RecipeBuildEvidence",
    "RunSwitchApplyRequest",
    "RunSwitchMemberProgress",
    "RunSwitchOperation",
    "RunSwitchPhase",
    "RunSwitchPhaseKind",
    "RunSwitchPlan",
    "RunSwitchPreviewRequest",
    "RunSwitchProgress",
    "RunSwitchReason",
    "RunSwitchStopApplyRequest",
    "RunSwitchStopPreviewRequest",
    "RuntimeImageStorageImpact",
    "SparkFit",
    "SparkFitNode",
    "SparkGroup",
    "SparkGroupNode",
    "StopImpact",
    "UuidId",
]
