schema_version = 2

[nodes.spk_42a502cc1a5de4c79aea1b6b6d993c74]
display_name = "DGX Spark 1"
hostname = "spark-3542"
lifecycle = "ready"

[nodes.spk_42a502cc1a5de4c79aea1b6b6d993c74.management]
host = "192.168.1.211"
user = "carst"
port = 22

[nodes.spk_42a502cc1a5de4c79aea1b6b6d993c74.labels]
pool = "default"
role = "head"
architecture = "aarch64"
accelerator = "nvidia-gb10"

[nodes.spk_ec7897d93866091c4249cc7825fb95c7]
display_name = "DGX Spark 2"
hostname = "spark-2297"
lifecycle = "ready"

[nodes.spk_ec7897d93866091c4249cc7825fb95c7.management]
host = "192.168.1.212"
user = "carst"
port = 22

[nodes.spk_ec7897d93866091c4249cc7825fb95c7.labels]
pool = "default"
role = "worker"
architecture = "aarch64"
accelerator = "nvidia-gb10"
