import type {components} from "./generated";

export type NodeSummary = components["schemas"]["NodeStatus"];
export type AuthSession = components["schemas"]["AuthSession"];
export type FleetTelemetryDetails = components["schemas"]["TelemetryDetails"];
export type TelemetryPoint = components["schemas"]["TelemetryPoint"];
export type FleetTelemetryState = components["schemas"]["TelemetryState"];
export type VisualFleetNode = components["schemas"]["FleetNode"];
export type VisualFleetSnapshot = components["schemas"]["FleetSnapshot"];
export type FleetNodeIdentity = components["schemas"]["FleetNodeIdentity"];
export type NodeProfileUpdate = components["schemas"]["NodeProfileUpdateRequest"];
export type FleetEvidenceResponse = components["schemas"]["FleetStatusResponse"];
export type TelemetryHistory = components["schemas"]["TelemetryHistoryResponse"];
export type TelemetryResolution = TelemetryHistory["resolution"];
export type TelemetryHistoryPoint = components["schemas"]["TelemetryPoint"] | components["schemas"]["TelemetryRollupPoint"];
export type TelemetryHistoryMetadata = components["schemas"]["TelemetryHistoryMetadata"];
export type TelemetryRollupPoint = components["schemas"]["TelemetryRollupPoint"];
export type TelemetryMetricSummary = components["schemas"]["TelemetryMetricSummary"];
export type AgentUpgradeStrategy = "one-at-a-time" | "all-at-once";
export type AgentUpgradePackage = {
  architecture: "linux-arm64"; package_bytes: number; package_sha256: string;
  package_signature: string; package_url: string; package_version: string;
  schema_version: 1; target_binary_digest: string; target_build_digest: string;
};
export type AgentRepairManifest = {
  schema_version: 2;
  kind: "agent-upgrade-repair";
  node_id: string;
  authority_sha256: string;
  package: AgentUpgradePackage;
};
export type AgentUpgradePlan = {
  authority_revision: string; node_ids: string[]; package: AgentUpgradePackage;
  plan_digest: string; repair_manifest?: AgentRepairManifest; strategy: AgentUpgradeStrategy;
};
export type AgentSummary = components["schemas"]["AgentSummary"];
export type AgentsResponse = components["schemas"]["AgentsResponse"];
export type EnrollmentSummary = components["schemas"]["EnrollmentSummary"];
export type EnrollmentListResponse = components["schemas"]["EnrollmentListResponse"];
export type EnrollmentGrantResponse = components["schemas"]["EnrollmentGrantResponse"];
export type JobDetail = components["schemas"]["JobDetailResponse"];
export type JobResumeResponse = components["schemas"]["JobResumeResponse"];
export type JobSummary = components["schemas"]["JobSummary"];
export type JobsResponse = components["schemas"]["JobsResponse"];
export type ProposalInput = {base_revision: string; changes: {path: string; document: Record<string, unknown>}[]};
export type ProposalPreview = {base_revision: string; digest: string; patch: string; affected_documents: string[]; validation_results: string[]};
export type AuditSummary = {request_id: string; actor: string; action: string; authority_revision?: string; targets: string[]; occurred_at?: string | null};
export type AuditResponse = {events: AuditSummary[]};
export type ModelDefinition = components["schemas"]["ModelDefinition"];
export type RecipeDefinition = components["schemas"]["RecipeDefinition"];
export type LibraryRecipeModel = components["schemas"]["LibraryRecipeModel"];
export type SourceBundleReceipt = {sha256: string; archive_bytes: number; total_bytes: number; file_count: number; files: string[]};
export type SourcePolicyFinding = {code: string; path: string; line: number | null; detail: string};
export type SourcePolicyReport = {passed: boolean; source_bundle_sha256: string; dockerfile: string; findings: SourcePolicyFinding[]};
export type RecipeMappingPlan = {recipe_revision_id: string; recipe_content_sha256: string; topology_name: string; generation: number; parameters: Record<string, unknown>; nodes: Array<{node_id: string; rank: number; role: string; endpoint_owner: boolean}>; placement_digest: string};
export type RecipeBuildPlan = {build_id: string; recipe_revision_id: string; recipe_content_sha256: string; builder_node_id: string; source_bundle_sha256: string; build_input_sha256: string};
export type RecipeOperation = {id: string; kind: string; owner_id: string; state: string; plan_digest: string; nodes: string[]; result: Record<string, unknown> | null};
export type LibrarySnapshot = components["schemas"]["LibrarySnapshot"];
export type LibraryRecipeDetail = components["schemas"]["LibraryRecipeDetail"];
export type LibraryRecipeSummary = components["schemas"]["LibraryRecipeSummary"];
export type LibraryModel = components["schemas"]["LibraryModel"];
export type LibraryBuildPreviewInput = components["schemas"]["BuildPreviewRequest"];
export type LibraryBuildPlan = components["schemas"]["BuildPlanResponse"];
export type LibraryBuildApplyInput = components["schemas"]["BuildRequest"];
export type LibraryMappingPreviewInput = components["schemas"]["MappingPreviewRequest"];
export type LibraryMappingPlan = components["schemas"]["MappingPlanResponse"];
export type LibraryMappingApplyInput = components["schemas"]["MappingRequest"];
export type LibraryMappingResult = components["schemas"]["MappingResponse"];
export type LibraryImageDistributionPreviewInput = components["schemas"]["ImageDistributionPreviewRequest"];
export type LibraryImageDistributionPlan = components["schemas"]["ImageDistributionPlanResponse"];
export type LibraryImageDistributionApplyInput = components["schemas"]["ImageDistributionRequest"];
export type LibraryInstallPreviewInput = components["schemas"]["InstallPreviewRequest"];
export type LibraryInstallPlan = components["schemas"]["InstallPlanResponse"];
export type LibraryInstallApplyInput = components["schemas"]["InstallRequest"];
export type LibraryLoadPreviewInput = components["schemas"]["RunPreviewRequest"];
export type LibraryLoadPlan = components["schemas"]["RunPlanResponse"];
export type LibraryLoadApplyInput = components["schemas"]["RunRequest"];
export type LibraryStopApplyInput = components["schemas"]["StopRequest"];
export type LibraryUninstallApplyInput = components["schemas"]["UninstallRequest"];
export type LibraryStopPlan = components["schemas"]["StopPlanResponse"];
export type LibraryUninstallPlan = components["schemas"]["UninstallPlanResponse"];
export type LibraryOperation = components["schemas"]["OperationResponse"];
export type LibraryRunStatus = components["schemas"]["RunStatusResponse"];
export type ArtifactJobInterface = "audio-job" | "video-job" | "image-job" | "mesh-job" | "artifact-job";
export type ArtifactJobFile = {name: string; media_type: string; size_bytes: number; sha256: string};
export type ArtifactJobInputFile = ArtifactJobFile & {slot: string};
export type ArtifactJobOutputLimits = {
  max_files: number;
  max_file_bytes: number;
  max_total_bytes: number;
  allowed_media_types: string[];
};
export type ArtifactJobCreateInput = {
  interface: ArtifactJobInterface;
  parameters: Record<string, string | number | boolean>;
  inputs: ArtifactJobInputFile[];
  output_limits: ArtifactJobOutputLimits;
  timeout_seconds: number;
};
export type ArtifactJob = {
  id: string;
  run_id: string;
  operation_id: string | null;
  interface: ArtifactJobInterface;
  state: "draft" | "ready" | "queued" | "running" | "succeeded" | "failed" | "cancelled";
  contract_sha256: string;
  compiled_contract: Record<string, unknown>;
  input_manifest_sha256: string;
  input_total_bytes: number;
  input_declarations: ArtifactJobInputFile[];
  input_files: ArtifactJobInputFile[];
  output_limits: ArtifactJobOutputLimits;
  output_manifest_sha256: string | null;
  output_files: ArtifactJobFile[];
  result_evidence: {elapsed_milliseconds?: number; peak_memory_bytes?: number} | null;
  status_reason: string | null;
  timeout_seconds: number;
  created_at: string;
  updated_at: string;
};
export type ArtifactJobList = {jobs: ArtifactJob[]};
export type ArtifactJobCapabilities = {
  schema_version: 1;
  transport: {
    max_input_files: number; max_input_file_bytes: number; max_input_total_bytes: number;
    max_output_files: number; max_output_file_bytes: number; max_output_total_bytes: number;
    max_timeout_seconds: number; reserved_input_names: string[];
  };
  storage: {max_stored_bytes: number; used_bytes: number; remaining_bytes: number};
};
export type ArtifactTransferProgress = {loaded: number; total: number};
export type FleetProfile = components["schemas"]["FleetProfileView"];
export type FleetProfileInput = components["schemas"]["FleetProfileInput"];
export type FleetProfileApplyInput = components["schemas"]["FleetProfileApplyRequest"];
export type FleetProfileList = components["schemas"]["FleetProfileList"];
export type FleetProfilePreview = components["schemas"]["FleetProfilePreview"];
export type FleetProfileApplication = components["schemas"]["FleetProfileApplicationView"];
export type FleetProfileStatus = components["schemas"]["FleetProfileStatusView"];
export type FleetProfileCaptureInput = components["schemas"]["FleetProfileCaptureInput"];
export type FleetProfileDuplicateInput = components["schemas"]["FleetProfileDuplicateInput"];
// These operation and response contracts are generated from the Controller
// OpenAPI document. Keep the UI aliases pointed at the generated source so a
// contract change is caught by the client build instead of being hidden by a
// second, hand-maintained DTO.
export type RunSwitchPhaseKind = components["schemas"]["RunSwitchPhase"]["kind"];
export type RunSwitchInvocation = components["schemas"]["InvocationMetadata"];
export type RunSwitchSparkNode = components["schemas"]["SparkGroupNode"];
export type RunSwitchSparkGroup = components["schemas"]["SparkGroup"];
export type RunSwitchPreviewRequest = components["schemas"]["RunSwitchPreviewRequest"];
export type RunSwitchApplyRequest = components["schemas"]["RunSwitchApplyRequest"];
export type RunSwitchReason = components["schemas"]["RunSwitchReason"];
export type RunSwitchCapabilityEvidence = components["schemas"]["CapabilityEvidence"];
export type RunSwitchPlanPhase = components["schemas"]["RunSwitchPhase"];
export type RunSwitchPlan = components["schemas"]["RunSwitchPlan"];
export type RunSwitchMemberProgress = components["schemas"]["RunSwitchMemberProgress"];
export type RunSwitchProgress = components["schemas"]["RunSwitchProgress"];
export type RunSwitchOperation = components["schemas"]["RunSwitchOperation"];
export type TelemetryScope = components["schemas"]["TelemetrySeries"]["scope"];
export type TelemetrySupport = components["schemas"]["TelemetrySeries"]["support_status"];
export type TelemetryFreshness = components["schemas"]["TelemetrySeries"]["freshness"];
export type TelemetryMeasurementKind = components["schemas"]["TelemetrySeries"]["measurement_kind"];
export type TelemetrySeries = components["schemas"]["TelemetrySeries"];
export type TelemetryCapability = components["schemas"]["TelemetryCapability"];
export type TelemetryProvenance = components["schemas"]["TelemetryProvenance"];
export type TelemetryRuntime = components["schemas"]["TelemetryRuntime"];
export type TelemetryWorkload = components["schemas"]["TelemetryWorkload"];
export type TelemetryMetrics = components["schemas"]["TelemetryMetrics"];
export type RichTelemetryPoint = TelemetryPoint;
export type TelemetryCurrentResponse = components["schemas"]["TelemetryCurrentResponse"];
export type TelemetryCapabilitiesResponse = components["schemas"]["TelemetryCapabilitiesResponse"];
export type TelemetryWorkloadsResponse = components["schemas"]["TelemetryWorkloadsResponse"];
export type ModelCacheState = components["schemas"]["CacheEntryResponse"]["state"];
export type ModelCacheArtifactState = components["schemas"]["CacheArtifactResponse"]["state"];
export type ModelCacheOperationState = components["schemas"]["ModelCacheOperationResponse"]["state"];
export type ModelCacheStorageResponse = components["schemas"]["CacheStorageResponse"];
export type CacheArtifactResponse = components["schemas"]["CacheArtifactResponse"];
export type CacheEntryResponse = components["schemas"]["CacheEntryResponse"];
export type ModelCacheInventoryResponse = components["schemas"]["ModelCacheInventoryResponse"];
export type ModelCacheOperationProgress = components["schemas"]["ModelCacheOperationProgress"];
export type ModelCacheOperationResponse = components["schemas"]["ModelCacheOperationResponse"];
export type ModelCacheDownloadPreviewInput = components["schemas"]["ModelCacheDownloadPreviewRequest"];
export type ModelCacheDownloadInput = components["schemas"]["ModelCacheDownloadRequest"];
export type ModelCacheDownloadPreviewResponse = components["schemas"]["ModelCacheDownloadPreviewResponse"];
export type ModelCacheRepairPreviewInput = components["schemas"]["ModelCacheRepairPreviewRequest"];
export type ModelCacheRepairInput = components["schemas"]["ModelCacheRepairRequest"];
export type ModelCacheRepairPreviewResponse = components["schemas"]["ModelCacheRepairPreviewResponse"];
export type ModelCacheEvictionPreviewInput = components["schemas"]["ModelCacheEvictionPreviewRequest"];
export type ModelCacheEvictInput = components["schemas"]["ModelCacheEvictRequest"];
export type ModelCacheEvictionEntry = components["schemas"]["ModelCacheEvictionEntry"];
export type ModelCacheEvictionPreviewResponse = components["schemas"]["ModelCacheEvictionPreviewResponse"];
export type ModelCacheUpdateResponse = components["schemas"]["ModelCacheUpdateResponse"];
export type ModelCacheUpdatesResponse = components["schemas"]["ModelCacheUpdatesResponse"];
export type ModelCacheOperationsResponse = components["schemas"]["ModelCacheOperationsResponse"];
export type LibraryPlacementPreviewInput = components["schemas"]["LibraryPlacementPreviewRequest"];
export type LibraryPlacementPreview = components["schemas"]["LibraryPlacementPreview"];
export type LibraryPlacementApplyInput = components["schemas"]["LibraryPlacementApplyRequest"];
export type LibraryPlacementApplication = components["schemas"]["LibraryPlacementApplication"];
export type LibraryModelDeletionPlan = components["schemas"]["ModelDeletionPlanResponse"];
export interface CatalogApi {
}
export interface LibraryApi {
  librarySnapshot(cursor?: string, signal?: AbortSignal): Promise<LibrarySnapshot>;
  libraryRecipe(recipeId: string, signal?: AbortSignal): Promise<LibraryRecipeDetail>;
  previewLibraryPlacement(input: LibraryPlacementPreviewInput, signal?: AbortSignal): Promise<LibraryPlacementPreview>;
  applyLibraryPlacement(input: LibraryPlacementApplyInput, signal?: AbortSignal): Promise<LibraryPlacementApplication>;
  libraryPlacement(placementId: string, signal?: AbortSignal): Promise<LibraryPlacementApplication>;
  previewLibraryModelDeletion(modelVersionSha256: string, signal?: AbortSignal): Promise<LibraryModelDeletionPlan>;
  deleteLibraryModel(modelVersionSha256: string, input: LibraryUninstallApplyInput, signal?: AbortSignal): Promise<LibraryOperation>;
  previewLibraryBuild(input: LibraryBuildPreviewInput, signal?: AbortSignal): Promise<LibraryBuildPlan>;
  applyLibraryBuild(input: LibraryBuildApplyInput, signal?: AbortSignal): Promise<LibraryOperation>;
  previewLibraryMapping(input: LibraryMappingPreviewInput, signal?: AbortSignal): Promise<LibraryMappingPlan>;
  applyLibraryMapping(input: LibraryMappingApplyInput, signal?: AbortSignal): Promise<LibraryMappingResult>;
  previewLibraryImageDistribution(input: LibraryImageDistributionPreviewInput, signal?: AbortSignal): Promise<LibraryImageDistributionPlan>;
  applyLibraryImageDistribution(input: LibraryImageDistributionApplyInput, signal?: AbortSignal): Promise<LibraryOperation>;
  previewLibraryInstall(input: LibraryInstallPreviewInput, signal?: AbortSignal): Promise<LibraryInstallPlan>;
  applyLibraryInstall(input: LibraryInstallApplyInput, signal?: AbortSignal): Promise<LibraryOperation>;
  previewLibraryLoad(input: LibraryLoadPreviewInput, signal?: AbortSignal): Promise<LibraryLoadPlan>;
  applyLibraryLoad(input: LibraryLoadApplyInput, signal?: AbortSignal): Promise<LibraryOperation>;
  previewLibraryStop(runId: string, signal?: AbortSignal): Promise<LibraryStopPlan>;
  applyLibraryStop(runId: string, input: LibraryStopApplyInput, signal?: AbortSignal): Promise<LibraryOperation>;
  previewLibraryUninstall(installationId: string, signal?: AbortSignal): Promise<LibraryUninstallPlan>;
  applyLibraryUninstall(installationId: string, input: LibraryUninstallApplyInput, signal?: AbortSignal): Promise<LibraryOperation>;
  libraryOperation(operationId: string, signal?: AbortSignal): Promise<LibraryOperation>;
  retryLibraryOperation(operationId: string, signal?: AbortSignal): Promise<LibraryOperation>;
  libraryRunStatus(runId: string, signal?: AbortSignal): Promise<LibraryRunStatus>;
  libraryJobProgress(jobId: string, signal?: AbortSignal): Promise<JobDetail>;
  artifactJobsForRun(runId: string, signal?: AbortSignal): Promise<ArtifactJobList>;
  artifactJobCapabilities(signal?: AbortSignal): Promise<ArtifactJobCapabilities>;
  createArtifactJob(runId: string, input: ArtifactJobCreateInput, signal?: AbortSignal): Promise<ArtifactJob>;
  uploadArtifactJobInput(jobId: string, file: ArtifactJobInputFile, content: Blob, signal?: AbortSignal, onProgress?: (progress: ArtifactTransferProgress) => void): Promise<ArtifactJob>;
  finalizeArtifactJob(jobId: string, signal?: AbortSignal): Promise<ArtifactJob>;
  submitArtifactJob(jobId: string, signal?: AbortSignal): Promise<ArtifactJob>;
  artifactJob(jobId: string, signal?: AbortSignal): Promise<ArtifactJob>;
  cancelArtifactJob(jobId: string, reason: string, signal?: AbortSignal): Promise<ArtifactJob>;
  artifactJobResult(jobId: string, signal?: AbortSignal): Promise<ArtifactJob>;
  artifactJobResultUrl(jobId: string, sha256: string): string;
}
export interface ControlApi extends LibraryApi {
  fleetProfiles(signal?: AbortSignal): Promise<FleetProfileList>;
  fleetProfile(profileId: string, signal?: AbortSignal): Promise<FleetProfile>;
  createFleetProfile(input: FleetProfileInput, signal?: AbortSignal): Promise<FleetProfile>;
  updateFleetProfile(profileId: string, input: FleetProfileInput, signal?: AbortSignal): Promise<FleetProfile>;
  deleteFleetProfile(profileId: string, signal?: AbortSignal): Promise<void>;
  previewFleetProfile(profileId: string, signal?: AbortSignal): Promise<FleetProfilePreview>;
  applyFleetProfile(profileId: string, input: FleetProfileApplyInput, signal?: AbortSignal): Promise<FleetProfileApplication>;
  fleetProfileApplication(applicationId: string, signal?: AbortSignal): Promise<FleetProfileApplication>;
  previewRecipeRunSwitch(input: RunSwitchPreviewRequest, signal?: AbortSignal): Promise<RunSwitchPlan>;
  applyRecipeRunSwitch(input: RunSwitchApplyRequest, signal?: AbortSignal): Promise<RunSwitchOperation>;
  getRecipeRunSwitchOperation(operationId: string, signal?: AbortSignal): Promise<RunSwitchOperation>;
  captureCurrentFleetProfile(input: FleetProfileCaptureInput, signal?: AbortSignal): Promise<FleetProfile>;
  duplicateFleetProfile(profileId: string, input: FleetProfileDuplicateInput, signal?: AbortSignal): Promise<FleetProfile>;
  fleetProfileStatus(profileId: string, signal?: AbortSignal): Promise<FleetProfileStatus>;
  modelCacheInventory(cursor?: string, signal?: AbortSignal): Promise<ModelCacheInventoryResponse>;
  modelCacheEntry(artifactSetSha256: string, signal?: AbortSignal): Promise<CacheEntryResponse>;
  previewModelCacheDownload(input: ModelCacheDownloadPreviewInput, signal?: AbortSignal): Promise<ModelCacheDownloadPreviewResponse>;
  downloadModelCache(input: ModelCacheDownloadInput, signal?: AbortSignal): Promise<ModelCacheOperationResponse>;
  previewModelCacheRepair(input: ModelCacheRepairPreviewInput, signal?: AbortSignal): Promise<ModelCacheRepairPreviewResponse>;
  repairModelCache(input: ModelCacheRepairInput, signal?: AbortSignal): Promise<ModelCacheOperationResponse>;
  previewModelCacheEviction(input: ModelCacheEvictionPreviewInput, signal?: AbortSignal): Promise<ModelCacheEvictionPreviewResponse>;
  evictModelCache(input: ModelCacheEvictInput, signal?: AbortSignal): Promise<ModelCacheOperationResponse>;
  modelCacheUpdates(signal?: AbortSignal): Promise<ModelCacheUpdatesResponse>;
  modelCacheOperations(cursor?: string, signal?: AbortSignal): Promise<ModelCacheOperationsResponse>;
  modelCacheOperation(operationId: string, signal?: AbortSignal): Promise<ModelCacheOperationResponse>;
  visualFleet(signal?: AbortSignal): Promise<VisualFleetSnapshot>;
  fleetEvidence(signal?: AbortSignal): Promise<FleetEvidenceResponse>;
  nodeStatuses(signal?: AbortSignal): Promise<FleetEvidenceResponse>;
  nodeTelemetryHistory(nodeId: string, start: string, end: string, resolution: TelemetryResolution, maximumPoints: number, signal?: AbortSignal): Promise<TelemetryHistory>;
  nodeTelemetryCurrent(nodeId: string, signal?: AbortSignal): Promise<TelemetryCurrentResponse>;
  nodeTelemetryCapabilities(nodeId: string, signal?: AbortSignal): Promise<TelemetryCapabilitiesResponse>;
  nodeTelemetryWorkloads(nodeId: string, runId?: string, state?: string, signal?: AbortSignal): Promise<TelemetryWorkloadsResponse>;
  updateNodeProfile(nodeId: string, input: NodeProfileUpdate, signal?: AbortSignal): Promise<FleetNodeIdentity>;
  jobs(cursor?: string): Promise<JobsResponse>;
  job(jobId: string, operationCursor?: string, targetCursor?: string): Promise<JobDetail>;
  resumeJob(jobId: string): Promise<JobResumeResponse>;
  audit(): Promise<AuditResponse>;
  preview(input: ProposalInput): Promise<ProposalPreview>; submit(digest: string): Promise<Record<string, unknown>>;
  agents(): Promise<AgentsResponse>;
  enrollments(): Promise<EnrollmentListResponse>;
  createEnrollmentGrant(ttlSeconds: number, signal?: AbortSignal): Promise<EnrollmentGrantResponse>;
  createReenrollmentGrant(nodeId: string | undefined, ttlSeconds: number, signal?: AbortSignal): Promise<EnrollmentGrantResponse>;
  revokeAgentNode(nodeId: string): Promise<void>;
  previewAgentUpgrade(nodeIds: string[] | undefined, strategy: AgentUpgradeStrategy, repairManifest?: AgentRepairManifest, signal?: AbortSignal): Promise<AgentUpgradePlan>;
  applyAgentUpgrade(plan: AgentUpgradePlan, signal?: AbortSignal): Promise<{id: string; state: string}>;
}
