import type {components} from "./generated";

export type NodeSummary = components["schemas"]["NodeStatus"];
export type AuthSession = components["schemas"]["AuthSession"];
export type VisualFleetSnapshot = components["schemas"]["FleetSnapshot"];
export type VisualFleetNode = components["schemas"]["FleetNode"];
export type FleetNodeIdentity = components["schemas"]["FleetNodeIdentity"];
export type NodeProfileUpdate = components["schemas"]["NodeProfileUpdateRequest"];
export type FleetEvidenceResponse = components["schemas"]["FleetStatusResponse"];
export type TelemetryHistory = components["schemas"]["TelemetryHistoryResponse"];
export type TelemetryPoint = components["schemas"]["TelemetryPoint"];
export type TelemetryResolution = "raw" | "minute" | "fifteen-minute";
export type TelemetryHistoryPoint = TelemetryHistory["points"][number];
export type AgentUpgradeStrategy = "one-at-a-time" | "all-at-once";
export type AgentUpgradePackage = {
  architecture: "linux-arm64"; package_bytes: number; package_sha256: string;
  package_signature: string; package_url: string; package_version: string;
  schema_version: 1; target_binary_digest: string; target_build_digest: string;
};
export type AgentUpgradePlan = {
  authority_revision: string; node_ids: string[]; package: AgentUpgradePackage;
  plan_digest: string; strategy: AgentUpgradeStrategy;
};
export type AgentSummary = components["schemas"]["AgentSummary"];
export type AgentsResponse = components["schemas"]["AgentsResponse"];
export type EnrollmentSummary = components["schemas"]["EnrollmentSummary"];
export type EnrollmentListResponse = components["schemas"]["EnrollmentListResponse"];
export type EnrollmentGrantResponse = components["schemas"]["EnrollmentGrantResponse"];
export type JobDetail = components["schemas"]["JobDetailResponse"];
export type JobResumeResponse = components["schemas"]["JobResumeResponse"];
export type JobSummary = components["schemas"]["JobSummary"];
export type JobsResponse = components["schemas"]["JobsResponse"];
export type ProposalInput = {base_revision: string; changes: {path: string; document: Record<string, unknown>}[]};
export type ProposalPreview = {base_revision: string; digest: string; patch: string; affected_documents: string[]; validation_results: string[]};
export type AuditSummary = {request_id: string; actor: string; action: string; authority_revision?: string; targets: string[]; occurred_at?: string | null};
export type AuditResponse = {events: AuditSummary[]};
export type CatalogRecipeSummary = components["schemas"]["RecipeSummaryResponse"];
export type CatalogRecipeRevision = components["schemas"]["RecipeRevisionResponse"];
export type CatalogRecipeList = components["schemas"]["RecipeListResponse"];
export type CatalogRecipeDocument = Record<string, unknown>;
export type SourceBundleReceipt = {sha256: string; archive_bytes: number; total_bytes: number; file_count: number; files: string[]};
export type SourcePolicyFinding = {code: string; path: string; line: number | null; detail: string};
export type SourcePolicyReport = {passed: boolean; source_bundle_sha256: string; dockerfile: string; findings: SourcePolicyFinding[]};
export type RecipeMappingPlan = {recipe_revision_id: string; recipe_content_sha256: string; topology_name: string; generation: number; parameters: Record<string, unknown>; nodes: Array<{node_id: string; rank: number; role: string; endpoint_owner: boolean}>; placement_digest: string};
export type RecipeBuildPlan = {build_id: string; recipe_revision_id: string; recipe_content_sha256: string; builder_node_id: string; source_bundle_sha256: string; build_input_sha256: string};
export type RecipeOperation = {id: string; kind: string; owner_id: string; state: string; plan_digest: string; nodes: string[]; result: Record<string, unknown> | null};
export type LibrarySnapshot = components["schemas"]["LibrarySnapshot"];
export type LibraryRecipeDetail = components["schemas"]["LibraryRecipeDetail"];
export type LibraryRecipeSummary = components["schemas"]["LibraryRecipeSummary"];
export type LibraryModel = components["schemas"]["LibraryModel"];
export type LibraryBuildPreviewInput = components["schemas"]["BuildPreviewRequest"];
export type LibraryBuildPlan = components["schemas"]["BuildPlanResponse"];
export type LibraryBuildApplyInput = components["schemas"]["BuildRequest"];
export type LibraryMappingPreviewInput = components["schemas"]["MappingPreviewRequest"];
export type LibraryMappingPlan = components["schemas"]["MappingPlanResponse"];
export type LibraryMappingApplyInput = components["schemas"]["MappingRequest"];
export type LibraryMappingResult = components["schemas"]["MappingResponse"];
export type LibraryImageDistributionPreviewInput = components["schemas"]["ImageDistributionPreviewRequest"];
export type LibraryImageDistributionPlan = components["schemas"]["ImageDistributionPlanResponse"];
export type LibraryImageDistributionApplyInput = components["schemas"]["ImageDistributionRequest"];
export type LibraryInstallPreviewInput = components["schemas"]["InstallPreviewRequest"];
export type LibraryInstallPlan = components["schemas"]["InstallPlanResponse"];
export type LibraryInstallApplyInput = components["schemas"]["InstallRequest"];
export type LibraryLoadPreviewInput = components["schemas"]["RunPreviewRequest"];
export type LibraryLoadPlan = components["schemas"]["RunPlanResponse"];
export type LibraryLoadApplyInput = components["schemas"]["RunRequest"];
export type LibraryStopApplyInput = components["schemas"]["StopRequest"];
export type LibraryUninstallApplyInput = components["schemas"]["UninstallRequest"];
export type LibraryStopPlan = components["schemas"]["StopPlanResponse"];
export type LibraryUninstallPlan = components["schemas"]["UninstallPlanResponse"];
export type LibraryOperation = components["schemas"]["OperationResponse"];
export type LibraryRunStatus = components["schemas"]["RunStatusResponse"];
export type GlobalRecipeRevision = {
  publisher: string; slug: string; recipe_id: string; revision_number: number; revision_id: string;
  content_sha256: string; published_at: string; document: Record<string, unknown>;
};
export type PublicRecipeCapability = "chat" | "reasoning" | "vision" | "image-generation" | "image-editing" | "video" | "audio" | "3d";
export type PublicRecipeExecutionReadiness = "executable" | "not-executable" | "integration-required" | "not-declared";
export type PublicRecipeExecutionReadinessBasis = "explicit-executable-metadata" | "explicit-non-executable-metadata" | "explicit-integration-required-metadata" | "missing-readiness-metadata" | "conflicting-readiness-metadata";
export type PublicRecipeQualificationBasis = "explicit-accepted-metadata" | "explicit-candidate-metadata" | "missing-accepted-metadata" | "conflicting-metadata";
export type PublicRecipeChange = {kind: "initial" | "model" | "runtime" | "performance" | "fix" | "security" | "compatibility" | "breaking" | "metadata"; summary: string; details: string | null; references: string[]};
export type PublicRecipeRelease = {version: string; released_at: string; content_sha256: string; upgrade_effect: "metadata-only" | "restart" | "reinstall" | "rebuild"; changes: PublicRecipeChange[]};
export type PublicRecipeLocalState = {status: "not-imported" | "current" | "update-available" | "local-ahead" | "different-revision" | "conflict"; recipe_id: string | null; revision_number: number | null; content_sha256: string | null; release_version: string | null};
export type PublicRecipe = {
  publisher: string; slug: string; title: string; description: string; tags: string[];
  uri: string; content_sha256: string;
  model_publisher: string; model_slug: string; model_title: string;
  source_owner: string | null; source_repository: string | null;
  capabilities: PublicRecipeCapability[]; qualification: "candidate" | "cataloged";
  qualification_basis: PublicRecipeQualificationBasis; qualification_detail: string; precision: string | null;
  execution_readiness: PublicRecipeExecutionReadiness; execution_readiness_basis: PublicRecipeExecutionReadinessBasis; execution_readiness_detail: string;
  execution_harness: string; runtime_distribution: string; source_bundle_sha256: string; artifact_count: number;
  topology_name: string; topology_mode: string; node_count: number;
  topology_roles: Array<{name: string; count: number; endpoint_owner: boolean}>;
  fabric: {connectivity: "none" | "connected" | "full_mesh" | "switch"; minimum_bandwidth_mbps: number};
  expected_download_bytes: number; maximum_installed_bytes_per_node: number; maximum_runtime_memory_bytes_per_node: number;
  release_version: string | null; release_released_at: string | null; local: PublicRecipeLocalState;
};
export type PublicRecipeList = {repository: string; commit: string; recipes: PublicRecipe[]};
export type PublicRecipePreview = PublicRecipe & {source: "global" | "recipe_library"; changes_since_local: PublicRecipeRelease[]};
export interface CatalogApi {
  catalogRecipes(cursor?: string): Promise<CatalogRecipeList>;
  catalogRecipe(recipeId: string): Promise<CatalogRecipeRevision>;
  createCatalogRecipe(input: {slug: string; document: CatalogRecipeDocument}): Promise<CatalogRecipeRevision>;
  updateCatalogRecipe(recipeId: string, expectedRevision: number, document: CatalogRecipeDocument): Promise<CatalogRecipeRevision>;
  resolveCatalogRecipe(recipeId: string, expectedRevision: number): Promise<CatalogRecipeRevision>;
  forkCatalogRecipe(recipeId: string, revision: number, slug: string): Promise<CatalogRecipeRevision>;
  previewGlobalRecipe(uri: string): Promise<GlobalRecipeRevision>;
  importGlobalRecipe(uri: string, expectedContentSha256: string): Promise<CatalogRecipeRevision>;
  listPublicRecipes(signal?: AbortSignal): Promise<PublicRecipeList>;
  previewPublicRecipe(uri: string, signal?: AbortSignal): Promise<PublicRecipePreview>;
  importPublicRecipe(uri: string, expectedContentSha256: string, signal?: AbortSignal): Promise<CatalogRecipeRevision>;
  attachPublicationReport(recipeId: string, report: Record<string, unknown>): Promise<void>;
  publicationExport(recipeId: string, publisher: string): Promise<Record<string, unknown>>;
  uploadSourceBundle(sha256: string, archive: Uint8Array): Promise<SourceBundleReceipt>;
  checkRecipeSource(recipeRevisionId: string): Promise<SourcePolicyReport>;
  previewRecipeBuild(recipeRevisionId: string, builderNodeId: string): Promise<RecipeBuildPlan>;
  buildRecipe(plan: RecipeBuildPlan): Promise<RecipeOperation>;
  previewRecipeMapping(recipeRevisionId: string, nodeIds: string[]): Promise<RecipeMappingPlan>;
  createRecipeMapping(plan: RecipeMappingPlan): Promise<{mapping_id: string; generation: number; placement_digest: string}>;
}
export type ImportDisposition = "imported" | "transformed" | "resolution_required" | "overlay_required" | "unsupported_blocking" | "dropped_redundant";
export type ImportReportItem = {source_path: string; disposition: ImportDisposition; destination_path: string | null; reason_code: string; detail: string; blocking: boolean};
export type WorkloadRunPreview = {draft_document: Record<string, unknown>; report: ImportReportItem[]; source_sha256: string; report_digest: string; redacted_source: Record<string, unknown>; runnable: boolean};
export type WorkloadRunApplied = {recipe_id: string; revision_number: number; lifecycle: string};
export interface WorkloadRunApi {
  previewWorkloadRun(sourceYaml: string): Promise<WorkloadRunPreview>;
  applyWorkloadRun(sourceYaml: string, sourceSha256: string, reportDigest: string): Promise<WorkloadRunApplied>;
}
export interface LibraryApi {
  librarySnapshot(cursor?: string, signal?: AbortSignal): Promise<LibrarySnapshot>;
  libraryRecipe(recipeId: string, signal?: AbortSignal): Promise<LibraryRecipeDetail>;
  previewLibraryBuild(input: LibraryBuildPreviewInput, signal?: AbortSignal): Promise<LibraryBuildPlan>;
  applyLibraryBuild(input: LibraryBuildApplyInput, signal?: AbortSignal): Promise<LibraryOperation>;
  previewLibraryMapping(input: LibraryMappingPreviewInput, signal?: AbortSignal): Promise<LibraryMappingPlan>;
  applyLibraryMapping(input: LibraryMappingApplyInput, signal?: AbortSignal): Promise<LibraryMappingResult>;
  previewLibraryImageDistribution(input: LibraryImageDistributionPreviewInput, signal?: AbortSignal): Promise<LibraryImageDistributionPlan>;
  applyLibraryImageDistribution(input: LibraryImageDistributionApplyInput, signal?: AbortSignal): Promise<LibraryOperation>;
  previewLibraryInstall(input: LibraryInstallPreviewInput, signal?: AbortSignal): Promise<LibraryInstallPlan>;
  applyLibraryInstall(input: LibraryInstallApplyInput, signal?: AbortSignal): Promise<LibraryOperation>;
  previewLibraryLoad(input: LibraryLoadPreviewInput, signal?: AbortSignal): Promise<LibraryLoadPlan>;
  applyLibraryLoad(input: LibraryLoadApplyInput, signal?: AbortSignal): Promise<LibraryOperation>;
  previewLibraryStop(runId: string, signal?: AbortSignal): Promise<LibraryStopPlan>;
  applyLibraryStop(runId: string, input: LibraryStopApplyInput, signal?: AbortSignal): Promise<LibraryOperation>;
  previewLibraryUninstall(installationId: string, signal?: AbortSignal): Promise<LibraryUninstallPlan>;
  applyLibraryUninstall(installationId: string, input: LibraryUninstallApplyInput, signal?: AbortSignal): Promise<LibraryOperation>;
  libraryOperation(operationId: string, signal?: AbortSignal): Promise<LibraryOperation>;
  retryLibraryOperation(operationId: string, signal?: AbortSignal): Promise<LibraryOperation>;
  libraryRunStatus(runId: string, signal?: AbortSignal): Promise<LibraryRunStatus>;
  libraryJobProgress(jobId: string, signal?: AbortSignal): Promise<JobDetail>;
}
export interface ControlApi extends LibraryApi {
  visualFleet(signal?: AbortSignal): Promise<VisualFleetSnapshot>;
  fleetEvidence(signal?: AbortSignal): Promise<FleetEvidenceResponse>;
  nodeStatuses(signal?: AbortSignal): Promise<FleetEvidenceResponse>;
  nodeTelemetryHistory(nodeId: string, start: string, end: string, resolution: TelemetryResolution, maximumPoints: number, signal?: AbortSignal): Promise<TelemetryHistory>;
  updateNodeProfile(nodeId: string, input: NodeProfileUpdate, signal?: AbortSignal): Promise<FleetNodeIdentity>;
  jobs(cursor?: string): Promise<JobsResponse>;
  job(jobId: string, operationCursor?: string, targetCursor?: string): Promise<JobDetail>;
  resumeJob(jobId: string): Promise<JobResumeResponse>;
  audit(): Promise<AuditResponse>;
  preview(input: ProposalInput): Promise<ProposalPreview>; submit(digest: string): Promise<Record<string, unknown>>;
  agents(): Promise<AgentsResponse>;
  enrollments(): Promise<EnrollmentListResponse>;
  createEnrollmentGrant(ttlSeconds: number, signal?: AbortSignal): Promise<EnrollmentGrantResponse>;
  createReenrollmentGrant(nodeId: string | undefined, ttlSeconds: number, signal?: AbortSignal): Promise<EnrollmentGrantResponse>;
  revokeAgentNode(nodeId: string): Promise<void>;
  previewAgentUpgrade(nodeIds: string[] | undefined, strategy: AgentUpgradeStrategy, signal?: AbortSignal): Promise<AgentUpgradePlan>;
  applyAgentUpgrade(plan: AgentUpgradePlan, signal?: AbortSignal): Promise<{id: string; state: string}>;
}
