import type {components} from "./generated";

export type NodeSummary = components["schemas"]["NodeStatus"];
export type AuthSession = components["schemas"]["AuthSession"];
export type VisualFleetSnapshot = components["schemas"]["FleetSnapshot"];
export type VisualFleetNode = components["schemas"]["FleetNode"];
export type FleetNodeIdentity = components["schemas"]["FleetNodeIdentity"];
export type NodeProfileUpdate = components["schemas"]["NodeProfileUpdateRequest"];
export type FleetEvidenceResponse = components["schemas"]["FleetStatusResponse"];
export type TelemetryHistory = components["schemas"]["TelemetryHistoryResponse"];
export type TelemetryPoint = components["schemas"]["TelemetryPoint"];
export type TelemetryResolution = "raw" | "minute" | "fifteen-minute";
export type TelemetryHistoryPoint = TelemetryHistory["points"][number];
export type AgentUpgradeStrategy = "one-at-a-time" | "all-at-once";
export type AgentUpgradePackage = {
  architecture: "linux-arm64"; package_bytes: number; package_sha256: string;
  package_signature: string; package_url: string; package_version: string;
  schema_version: 1; target_binary_digest: string; target_build_digest: string;
};
export type AgentRepairManifest = {
  schema_version: 2;
  kind: "agent-upgrade-repair";
  node_id: string;
  authority_sha256: string;
  package: AgentUpgradePackage;
};
export type AgentUpgradePlan = {
  authority_revision: string; node_ids: string[]; package: AgentUpgradePackage;
  plan_digest: string; repair_manifest?: AgentRepairManifest; strategy: AgentUpgradeStrategy;
};
export type AgentSummary = components["schemas"]["AgentSummary"];
export type AgentsResponse = components["schemas"]["AgentsResponse"];
export type EnrollmentSummary = components["schemas"]["EnrollmentSummary"];
export type EnrollmentListResponse = components["schemas"]["EnrollmentListResponse"];
export type EnrollmentGrantResponse = components["schemas"]["EnrollmentGrantResponse"];
export type JobDetail = components["schemas"]["JobDetailResponse"];
export type JobResumeResponse = components["schemas"]["JobResumeResponse"];
export type JobSummary = components["schemas"]["JobSummary"];
export type JobsResponse = components["schemas"]["JobsResponse"];
export type ProposalInput = {base_revision: string; changes: {path: string; document: Record<string, unknown>}[]};
export type ProposalPreview = {base_revision: string; digest: string; patch: string; affected_documents: string[]; validation_results: string[]};
export type AuditSummary = {request_id: string; actor: string; action: string; authority_revision?: string; targets: string[]; occurred_at?: string | null};
export type AuditResponse = {events: AuditSummary[]};
export type CatalogRecipeSummary = components["schemas"]["RecipeSummaryResponse"];
export type CatalogRecipeRevision = components["schemas"]["RecipeRevisionResponse"];
export type CatalogRecipeList = components["schemas"]["RecipeListResponse"];
export type CatalogRecipeDocument = Record<string, unknown>;
export type SourceBundleReceipt = {sha256: string; archive_bytes: number; total_bytes: number; file_count: number; files: string[]};
export type SourcePolicyFinding = {code: string; path: string; line: number | null; detail: string};
export type SourcePolicyReport = {passed: boolean; source_bundle_sha256: string; dockerfile: string; findings: SourcePolicyFinding[]};
export type RecipeMappingPlan = {recipe_revision_id: string; recipe_content_sha256: string; topology_name: string; generation: number; parameters: Record<string, unknown>; nodes: Array<{node_id: string; rank: number; role: string; endpoint_owner: boolean}>; placement_digest: string};
export type RecipeBuildPlan = {build_id: string; recipe_revision_id: string; recipe_content_sha256: string; builder_node_id: string; source_bundle_sha256: string; build_input_sha256: string};
export type RecipeOperation = {id: string; kind: string; owner_id: string; state: string; plan_digest: string; nodes: string[]; result: Record<string, unknown> | null};
export type LibrarySnapshot = components["schemas"]["LibrarySnapshot"];
export type LibraryRecipeDetail = components["schemas"]["LibraryRecipeDetail"];
export type LibraryRecipeSummary = components["schemas"]["LibraryRecipeSummary"];
export type LibraryModel = components["schemas"]["LibraryModel"];
export type LibraryBuildPreviewInput = components["schemas"]["BuildPreviewRequest"];
export type LibraryBuildPlan = components["schemas"]["BuildPlanResponse"];
export type LibraryBuildApplyInput = components["schemas"]["BuildRequest"];
export type LibraryMappingPreviewInput = components["schemas"]["MappingPreviewRequest"];
export type LibraryMappingPlan = components["schemas"]["MappingPlanResponse"];
export type LibraryMappingApplyInput = components["schemas"]["MappingRequest"];
export type LibraryMappingResult = components["schemas"]["MappingResponse"];
export type LibraryImageDistributionPreviewInput = components["schemas"]["ImageDistributionPreviewRequest"];
export type LibraryImageDistributionPlan = components["schemas"]["ImageDistributionPlanResponse"];
export type LibraryImageDistributionApplyInput = components["schemas"]["ImageDistributionRequest"];
export type LibraryInstallPreviewInput = components["schemas"]["InstallPreviewRequest"];
export type LibraryInstallPlan = components["schemas"]["InstallPlanResponse"];
export type LibraryInstallApplyInput = components["schemas"]["InstallRequest"];
export type LibraryLoadPreviewInput = components["schemas"]["RunPreviewRequest"];
export type LibraryLoadPlan = components["schemas"]["RunPlanResponse"];
export type LibraryLoadApplyInput = components["schemas"]["RunRequest"];
export type LibraryStopApplyInput = components["schemas"]["StopRequest"];
export type LibraryUninstallApplyInput = components["schemas"]["UninstallRequest"];
export type LibraryStopPlan = components["schemas"]["StopPlanResponse"];
export type LibraryUninstallPlan = components["schemas"]["UninstallPlanResponse"];
export type LibraryOperation = components["schemas"]["OperationResponse"];
export type LibraryRunStatus = components["schemas"]["RunStatusResponse"];
export type ArtifactJobInterface = "audio-job" | "video-job" | "image-job" | "mesh-job" | "artifact-job";
export type ArtifactJobFile = {name: string; media_type: string; size_bytes: number; sha256: string};
export type ArtifactJobInputFile = ArtifactJobFile & {slot: string};
export type ArtifactJobOutputLimits = {
  max_files: number;
  max_file_bytes: number;
  max_total_bytes: number;
  allowed_media_types: string[];
};
export type ArtifactJobCreateInput = {
  interface: ArtifactJobInterface;
  parameters: Record<string, string | number | boolean>;
  inputs: ArtifactJobInputFile[];
  output_limits: ArtifactJobOutputLimits;
  timeout_seconds: number;
};
export type ArtifactJob = {
  id: string;
  run_id: string;
  operation_id: string | null;
  interface: ArtifactJobInterface;
  state: "draft" | "ready" | "queued" | "running" | "succeeded" | "failed" | "cancelled";
  contract_sha256: string;
  compiled_contract: Record<string, unknown>;
  input_manifest_sha256: string;
  input_total_bytes: number;
  input_declarations: ArtifactJobInputFile[];
  input_files: ArtifactJobInputFile[];
  output_limits: ArtifactJobOutputLimits;
  output_manifest_sha256: string | null;
  output_files: ArtifactJobFile[];
  result_evidence: {elapsed_milliseconds?: number; peak_memory_bytes?: number} | null;
  status_reason: string | null;
  timeout_seconds: number;
  created_at: string;
  updated_at: string;
};
export type ArtifactJobList = {jobs: ArtifactJob[]};
export type ArtifactJobCapabilities = {
  schema_version: 1;
  transport: {
    max_input_files: number; max_input_file_bytes: number; max_input_total_bytes: number;
    max_output_files: number; max_output_file_bytes: number; max_output_total_bytes: number;
    max_timeout_seconds: number; reserved_input_names: string[];
  };
  storage: {max_stored_bytes: number; used_bytes: number; remaining_bytes: number};
};
export type ArtifactTransferProgress = {loaded: number; total: number};
export type FleetProfile = components["schemas"]["FleetProfileView"];
export type FleetProfileInput = components["schemas"]["FleetProfileInput"];
export type FleetProfileApplyInput = components["schemas"]["FleetProfileApplyRequest"];
export type FleetProfileList = components["schemas"]["FleetProfileList"];
export type FleetProfilePreview = components["schemas"]["FleetProfilePreview"];
export type FleetProfileApplication = components["schemas"]["FleetProfileApplicationView"];
export type RunSwitchPhaseKind = "transfer" | "verify" | "prepare" | "cleanup" | "stop" | "start" | "final_verify";
export type RunSwitchInvocation = {
  origin?: string;
  correlation_id?: string | null;
  reason?: string | null;
  context?: Record<string, string>;
};
export type RunSwitchSparkNode = {node_id: string; rank: number; role: string; endpoint_owner: boolean};
export type RunSwitchSparkGroup = {nodes: RunSwitchSparkNode[]};
export type RunSwitchPreviewRequest = {
  schema_version: 2;
  model_version_sha256: string;
  recipe_revision_id: string;
  spark_group: RunSwitchSparkGroup;
  alias: string;
  action: "run" | "switch";
  retention: "retain-cached" | "reclaim-unreferenced";
  invocation: RunSwitchInvocation;
};
export type RunSwitchApplyRequest = RunSwitchPreviewRequest & {plan_digest: string; request_key: string};
export type RunSwitchReason = {
  code: string;
  detail: string;
  severity: "blocker" | "warning" | "info";
  scope: "model" | "recipe" | "mapping" | "group" | "node" | "artifact" | "freshness" | "conflict" | "operation";
  node_ids: string[];
  stale: boolean;
};
export type RunSwitchCapabilityEvidence = {
  name: string;
  declared: boolean | null;
  evidence: "tested" | "observed" | "not-tested" | "unknown";
  support: "supported" | "unsupported" | "unknown";
  evidence_digest?: string | null;
  detail?: string | null;
};
export type RunSwitchPlanPhase = {
  index: number;
  kind: RunSwitchPhaseKind;
  state: "planned" | "retained" | "skipped" | "blocked";
  node_ids: string[];
  operation_digest?: string | null;
  detail: string;
};
export type RunSwitchPlan = {
  schema_version: 2;
  generated_at: string;
  action: "run" | "switch" | "stop";
  model_version_sha256: string | null;
  recipe_revision_id: string | null;
  recipe_content_sha256: string | null;
  alias: string | null;
  run_id: string | null;
  spark_group: RunSwitchSparkGroup;
  mapping: Record<string, unknown> | null;
  installation_id: string | null;
  installation_state: string | null;
  recipe_build_id: string | null;
  image_digest: string | null;
  start_plan_digest: string | null;
  model_capabilities: RunSwitchCapabilityEvidence[];
  recipe_capabilities: RunSwitchCapabilityEvidence[];
  freshness: Array<Record<string, unknown>>;
  fit_current?: Record<string, unknown>;
  fit_after_stop?: Record<string, unknown> | null;
  fit?: Record<string, unknown>;
  storage?: Record<string, unknown>;
  runtime_storage?: Record<string, unknown>;
  build?: Record<string, unknown>;
  preparation?: Record<string, unknown> | null;
  conflicts: RunSwitchReason[];
  stops: Array<Record<string, unknown>>;
  reclaimed_bytes: number;
  phases: RunSwitchPlanPhase[];
  allowed: boolean;
  blockers: RunSwitchReason[];
  warnings: RunSwitchReason[];
  invocation: RunSwitchInvocation;
  plan_digest: string;
  stop_before_prepare: boolean;
  stop_before_transfer: boolean;
};
export type RunSwitchMemberProgress = {
  node_id: string;
  phase: RunSwitchPhaseKind | null;
  state: "pending" | "running" | "succeeded" | "failed" | "unknown";
  completed_bytes: number;
  total_bytes: number | null;
  error?: string | null;
};
export type RunSwitchProgress = {
  phase_index: number;
  phase_count: number;
  phase: RunSwitchPhaseKind | null;
  state: "queued" | "running" | "succeeded" | "failed" | "unknown";
  completed_bytes: number;
  total_bytes: number | null;
  total_bytes_known: boolean;
  members: RunSwitchMemberProgress[];
};
export type RunSwitchOperation = {
  schema_version: 2;
  operation_id: string;
  kind: "recipe.run-switch.v2" | "recipe.stop.v2";
  action: "run" | "switch" | "stop";
  state: string;
  plan_digest: string;
  request_key: string;
  node_ids: string[];
  current_phase: RunSwitchPhaseKind | null;
  completed_phases: RunSwitchPhaseKind[];
  progress: RunSwitchProgress;
  status_reason?: string | null;
  result?: Record<string, unknown> | null;
};
export type TelemetryScope = "node" | "accelerator" | "memory" | "storage" | "network" | "runtime" | "workload" | "service" | "benchmark";
export type TelemetrySupport = "available" | "unsupported" | "unavailable" | "stale";
export type TelemetryFreshness = "fresh" | "delayed" | "stale";
export type TelemetryMeasurementKind = "measured" | "derived" | "estimated" | "configured";
export type TelemetrySeries = {
  node_id?: string | null;
  key: string;
  scope: TelemetryScope;
  device_id?: string | null;
  process_id?: number | null;
  process_name?: string | null;
  interface_name?: string | null;
  run_id?: string | null;
  value: number | string | boolean | null;
  unit: string;
  source: string;
  measurement_kind: TelemetryMeasurementKind;
  observed_at: string;
  received_at?: string | null;
  freshness: TelemetryFreshness;
  freshness_threshold_seconds: number;
  support_status: TelemetrySupport;
  reason?: string | null;
  aggregation: string;
};
export type TelemetryCapability = {
  node_id?: string | null;
  key: string;
  scope: TelemetryScope;
  device_id?: string | null;
  interface_name?: string | null;
  run_id?: string | null;
  unit: string;
  source: string;
  measurement_kind: TelemetryMeasurementKind;
  supported: boolean;
  freshness_threshold_seconds: number;
  reason?: string | null;
};
export type TelemetryProvenance = {collector: string; collector_version: string; host_uptime_seconds?: number | null; source_observed_at?: string | null};
export type TelemetryRuntime = {
  run_id: string;
  engine_id: string;
  backend: string;
  version?: string | null;
  endpoint?: string | null;
  model?: string | null;
  model_version?: string | null;
  recipe_revision?: string | null;
  context_limit_tokens?: number | null;
  serving_node_ids: string[];
  ranks: number[];
  readiness: "starting" | "ready" | "running" | "queued" | "stopped" | "failed" | "unknown";
  error?: string | null;
  adapter: string;
  adapter_version?: string | null;
  adapter_supported: boolean;
  adapter_reason?: string | null;
};
export type TelemetryWorkload = {
  request_id?: string | null;
  job_id?: string | null;
  run_id: string;
  model?: string | null;
  recipe_revision?: string | null;
  engine_id: string;
  state: "queued" | "running" | "completed" | "failed" | "cancelled" | "unknown";
  origin_node_id?: string | null;
  executor_node_ids: string[];
  created_at?: string | null;
  started_at?: string | null;
  ended_at?: string | null;
  elapsed_seconds?: number | null;
  failure?: string | null;
  title?: string | null;
  progress_value?: number | null;
  progress_max?: number | null;
  eta_seconds?: number | null;
  eta_source?: string | null;
};
export type TelemetryMetrics = {schema_version: 2; series: TelemetrySeries[]; capabilities: TelemetryCapability[]; runtimes: TelemetryRuntime[]; workloads: TelemetryWorkload[]; provenance: TelemetryProvenance};
export type RichTelemetryPoint = TelemetryPoint & {metrics?: TelemetryMetrics | null};
export type TelemetryCurrentResponse = {schema_version: 2; node_id: string; observed_at: string; received_at: string; freshness: "live" | "delayed" | "stale"; sample: RichTelemetryPoint};
export type TelemetryCapabilitiesResponse = {schema_version: 2; node_id: string; observed_at: string; received_at: string; freshness: "live" | "delayed" | "stale"; capabilities: TelemetryCapability[]};
export type TelemetryWorkloadsResponse = {schema_version: 2; node_id: string; observed_at: string; received_at: string; freshness: "live" | "delayed" | "stale"; run_id?: string | null; state?: string | null; runtimes: TelemetryRuntime[]; workloads: TelemetryWorkload[]};
export type ModelCacheState = "incomplete" | "downloading" | "verifying" | "cached" | "needs-repair" | "failed";
export type ModelCacheArtifactState = "partial" | "verified" | "missing" | "corrupt";
export type ModelCacheOperationState = "queued" | "running" | "partial" | "succeeded" | "failed" | "cancelled";
export type ModelCacheStorageResponse = {
  schema_version: 2;
  total_bytes: number;
  free_bytes: number;
  reserve_bytes: number;
  available_bytes: number;
  unique_used_bytes: number;
  in_flight_bytes: number;
  protected_bytes: number;
  reclaimable_bytes: number;
};
export type CacheArtifactResponse = {
  schema_version: 2;
  key: string;
  id: string;
  path: string;
  sha256: string;
  expected_bytes: number;
  actual_bytes: number;
  roles: string[];
  state: ModelCacheArtifactState;
  source: string;
};
export type CacheEntryResponse = {
  schema_version: 2;
  artifact_set_sha256: string;
  model_version_sha256: string | null;
  recipe_revision_sha256: string | null;
  state: ModelCacheState;
  coverage: "complete" | "incomplete";
  expected_bytes: number;
  verified_bytes: number;
  unique_bytes: number;
  artifacts: CacheArtifactResponse[];
  protected: boolean;
  protected_reasons: string[];
  update_available: boolean;
  recipe_update_available: boolean;
  created_at: string;
  updated_at: string;
  verified_at: string | null;
  last_error: string | null;
};
export type ModelCacheInventoryResponse = {
  schema_version: 2;
  source_policy: "nas-first";
  entries: CacheEntryResponse[];
  storage: ModelCacheStorageResponse;
  total: number;
  next_cursor: string | null;
};
export type ModelCacheOperationProgress = {
  schema_version: 2;
  phase: "queued" | "downloading" | "verifying" | "reclaiming" | "completed" | "failed";
  completed_artifacts: number;
  total_artifacts: number;
  downloaded_bytes: number;
  expected_bytes: number;
  current_artifact_key: string | null;
};
export type ModelCacheOperationResponse = {
  schema_version: 2;
  id: string;
  request_key: string;
  kind: "download" | "repair" | "evict";
  state: ModelCacheOperationState;
  artifact_set_sha256: string | null;
  plan_digest: string | null;
  progress: ModelCacheOperationProgress;
  result: Record<string, unknown> | null;
  last_error: string | null;
  created_at: string;
  updated_at: string;
  completed_at: string | null;
};
export type ModelCacheDownloadPreviewInput = {
  schema_version: 2;
  artifact_set_sha256?: string;
  model_version_sha256?: string;
  recipe_revision_sha256?: string;
  recipe_revision_id?: string;
  source_policy?: "nas-first";
};
export type ModelCacheDownloadInput = ModelCacheDownloadPreviewInput & {request_key: string; plan_digest: string};
export type ModelCacheDownloadPreviewResponse = {
  schema_version: 2;
  artifact_set_sha256: string;
  plan_digest: string;
  source_policy: "nas-first";
  artifact_count: number;
  expected_bytes: number;
  already_cached_bytes: number;
  new_bytes: number;
  blockers: string[];
  warnings: string[];
};
export type ModelCacheRepairPreviewInput = {schema_version: 2; artifact_set_sha256: string};
export type ModelCacheRepairInput = ModelCacheRepairPreviewInput & {request_key: string; plan_digest: string; source_policy?: "nas-first"};
export type ModelCacheRepairPreviewResponse = {
  schema_version: 2;
  artifact_set_sha256: string;
  plan_digest: string;
  source_policy: "nas-first";
  artifact_count: number;
  current_state: ModelCacheState;
  expected_bytes: number;
  verified_bytes: number;
};
export type ModelCacheEvictionPreviewInput = {schema_version: 2; target_bytes: number};
export type ModelCacheEvictInput = ModelCacheEvictionPreviewInput & {request_key: string; plan_digest: string};
export type ModelCacheEvictionEntry = {schema_version: 2; artifact_set_sha256: string; reclaimable_bytes: number; protected: boolean; protected_reasons: string[]; last_accessed_at: string};
export type ModelCacheEvictionPreviewResponse = {
  schema_version: 2;
  plan_digest: string;
  target_bytes: number;
  include_protected: false;
  selected: ModelCacheEvictionEntry[];
  protected_entries: ModelCacheEvictionEntry[];
  reclaimable_bytes: number;
  selected_bytes: number;
  storage_before: ModelCacheStorageResponse;
  storage_after: ModelCacheStorageResponse;
  blockers: string[];
};
export type ModelCacheUpdateResponse = {schema_version: 2; artifact_set_sha256: string; model_version_sha256: string | null; latest_model_version_sha256: string | null; recipe_revision_sha256: string | null; latest_recipe_revision_sha256: string | null; model_update_available: boolean; recipe_update_available: boolean};
export type ModelCacheUpdatesResponse = {schema_version: 2; source_policy: "nas-first"; updates: ModelCacheUpdateResponse[]};
export type ModelCacheOperationsResponse = {schema_version: 2; operations: ModelCacheOperationResponse[]; total: number; next_cursor: string | null};
export type GlobalRecipeRevision = {
  publisher: string; slug: string; recipe_id: string; revision_number: number; revision_id: string;
  content_sha256: string; published_at: string; document: Record<string, unknown>;
};
export type PublicRecipeCapability = "chat" | "reasoning" | "vision" | "image-generation" | "image-editing" | "video" | "audio" | "3d";
export type PublicRecipeExecutionReadiness = "executable" | "not-executable" | "integration-required" | "not-declared";
export type PublicRecipeExecutionReadinessBasis = "explicit-executable-metadata" | "explicit-non-executable-metadata" | "explicit-integration-required-metadata" | "missing-readiness-metadata" | "conflicting-readiness-metadata";
export type PublicRecipeQualificationBasis = "explicit-accepted-metadata" | "explicit-candidate-metadata" | "missing-accepted-metadata" | "conflicting-metadata";
export type PublicRecipeAlignment = "standard" | "abliterated" | "derisked" | "other-modified" | "unspecified";
export type PublicRecipeChange = {kind: "initial" | "model" | "runtime" | "performance" | "fix" | "security" | "compatibility" | "breaking" | "metadata"; summary: string; details: string | null; references: string[]};
export type PublicRecipeRelease = {version: string; released_at: string; content_sha256: string; upgrade_effect: "metadata-only" | "restart" | "reinstall" | "rebuild"; changes: PublicRecipeChange[]};
export type PublicRecipeLocalState = {status: "not-imported" | "current" | "update-available" | "local-ahead" | "different-revision" | "conflict"; recipe_id: string | null; revision_number: number | null; content_sha256: string | null; release_version: string | null};
export type PublicRecipe = {
  publisher: string; slug: string; title: string; description: string; tags: string[];
  uri: string; content_sha256: string;
  model_publisher: string; model_slug: string; model_title: string;
  model_version_publisher: string; model_version_slug: string; model_version_title: string;
  source_owner: string | null; source_repository: string | null;
  alignment: PublicRecipeAlignment;
  capabilities: PublicRecipeCapability[]; qualification: "candidate" | "cataloged";
  qualification_basis: PublicRecipeQualificationBasis; qualification_detail: string; precision: string | null;
  quantizations: string[];
  execution_readiness: PublicRecipeExecutionReadiness; execution_readiness_basis: PublicRecipeExecutionReadinessBasis; execution_readiness_detail: string;
  execution_harness: string; runtime_distribution: string; source_bundle_sha256: string; artifact_count: number;
  topology_name: string; topology_mode: string; node_count: number;
  topology_roles: Array<{name: string; count: number; endpoint_owner: boolean}>;
  fabric: {connectivity: "none" | "connected" | "full_mesh" | "switch"; minimum_bandwidth_mbps: number};
  expected_download_bytes: number; maximum_installed_bytes_per_node: number; maximum_runtime_memory_bytes_per_node: number;
  release_version: string | null; release_released_at: string | null; local: PublicRecipeLocalState;
};
export type PublicRecipeList = {repository: string; commit: string; recipes: PublicRecipe[]};
export type PublicRecipePreview = PublicRecipe & {source: "global" | "recipe_library"; changes_since_local: PublicRecipeRelease[]};
export type ManagedCatalogSyncSummary = components["schemas"]["ManagedCatalogSyncResponse"];
export type ManagedCatalogSyncInput = components["schemas"]["ManagedCatalogSyncRequest"];
export type LibraryPlacementPreviewInput = components["schemas"]["LibraryPlacementPreviewRequest"];
export type LibraryPlacementPreview = components["schemas"]["LibraryPlacementPreview"];
export type LibraryPlacementApplyInput = components["schemas"]["LibraryPlacementApplyRequest"];
export type LibraryPlacementApplication = components["schemas"]["LibraryPlacementApplication"];
export type LibraryModelDeletionPlan = components["schemas"]["ModelDeletionPlanResponse"];
export interface CatalogApi {
  catalogRecipes(cursor?: string): Promise<CatalogRecipeList>;
  catalogRecipe(recipeId: string): Promise<CatalogRecipeRevision>;
  createCatalogRecipe(input: {slug: string; document: CatalogRecipeDocument}): Promise<CatalogRecipeRevision>;
  updateCatalogRecipe(recipeId: string, expectedRevision: number, document: CatalogRecipeDocument): Promise<CatalogRecipeRevision>;
  resolveCatalogRecipe(recipeId: string, expectedRevision: number): Promise<CatalogRecipeRevision>;
  forkCatalogRecipe(recipeId: string, revision: number, slug: string): Promise<CatalogRecipeRevision>;
  previewGlobalRecipe(uri: string): Promise<GlobalRecipeRevision>;
  importGlobalRecipe(uri: string, expectedContentSha256: string): Promise<CatalogRecipeRevision>;
  listPublicRecipes(signal?: AbortSignal): Promise<PublicRecipeList>;
  previewPublicRecipe(uri: string, signal?: AbortSignal): Promise<PublicRecipePreview>;
  importPublicRecipe(uri: string, expectedContentSha256: string, signal?: AbortSignal): Promise<CatalogRecipeRevision>;
  syncManagedRecipeCatalog(input?: ManagedCatalogSyncInput, signal?: AbortSignal): Promise<ManagedCatalogSyncSummary>;
  managedRecipeCatalogSyncStatus(signal?: AbortSignal): Promise<ManagedCatalogSyncSummary>;
  attachPublicationReport(recipeId: string, report: Record<string, unknown>): Promise<void>;
  publicationExport(recipeId: string, publisher: string): Promise<Record<string, unknown>>;
  uploadSourceBundle(sha256: string, archive: Uint8Array): Promise<SourceBundleReceipt>;
  checkRecipeSource(recipeRevisionId: string): Promise<SourcePolicyReport>;
  previewRecipeBuild(recipeRevisionId: string, builderNodeId: string): Promise<RecipeBuildPlan>;
  buildRecipe(plan: RecipeBuildPlan): Promise<RecipeOperation>;
  previewRecipeMapping(recipeRevisionId: string, nodeIds: string[]): Promise<RecipeMappingPlan>;
  createRecipeMapping(plan: RecipeMappingPlan): Promise<{mapping_id: string; generation: number; placement_digest: string}>;
}
export type ImportDisposition = "imported" | "transformed" | "resolution_required" | "overlay_required" | "unsupported_blocking" | "dropped_redundant";
export type ImportReportItem = {source_path: string; disposition: ImportDisposition; destination_path: string | null; reason_code: string; detail: string; blocking: boolean};
export type WorkloadRunPreview = {draft_document: Record<string, unknown>; report: ImportReportItem[]; source_sha256: string; report_digest: string; redacted_source: Record<string, unknown>; runnable: boolean};
export type WorkloadRunApplied = {recipe_id: string; revision_number: number; lifecycle: string};
export interface WorkloadRunApi {
  previewWorkloadRun(sourceYaml: string): Promise<WorkloadRunPreview>;
  applyWorkloadRun(sourceYaml: string, sourceSha256: string, reportDigest: string): Promise<WorkloadRunApplied>;
}
export interface LibraryApi {
  librarySnapshot(cursor?: string, signal?: AbortSignal): Promise<LibrarySnapshot>;
  libraryRecipe(recipeId: string, signal?: AbortSignal): Promise<LibraryRecipeDetail>;
  previewLibraryPlacement(input: LibraryPlacementPreviewInput, signal?: AbortSignal): Promise<LibraryPlacementPreview>;
  applyLibraryPlacement(input: LibraryPlacementApplyInput, signal?: AbortSignal): Promise<LibraryPlacementApplication>;
  libraryPlacement(placementId: string, signal?: AbortSignal): Promise<LibraryPlacementApplication>;
  previewLibraryModelDeletion(modelVersionSha256: string, signal?: AbortSignal): Promise<LibraryModelDeletionPlan>;
  deleteLibraryModel(modelVersionSha256: string, input: LibraryUninstallApplyInput, signal?: AbortSignal): Promise<LibraryOperation>;
  previewLibraryBuild(input: LibraryBuildPreviewInput, signal?: AbortSignal): Promise<LibraryBuildPlan>;
  applyLibraryBuild(input: LibraryBuildApplyInput, signal?: AbortSignal): Promise<LibraryOperation>;
  previewLibraryMapping(input: LibraryMappingPreviewInput, signal?: AbortSignal): Promise<LibraryMappingPlan>;
  applyLibraryMapping(input: LibraryMappingApplyInput, signal?: AbortSignal): Promise<LibraryMappingResult>;
  previewLibraryImageDistribution(input: LibraryImageDistributionPreviewInput, signal?: AbortSignal): Promise<LibraryImageDistributionPlan>;
  applyLibraryImageDistribution(input: LibraryImageDistributionApplyInput, signal?: AbortSignal): Promise<LibraryOperation>;
  previewLibraryInstall(input: LibraryInstallPreviewInput, signal?: AbortSignal): Promise<LibraryInstallPlan>;
  applyLibraryInstall(input: LibraryInstallApplyInput, signal?: AbortSignal): Promise<LibraryOperation>;
  previewLibraryLoad(input: LibraryLoadPreviewInput, signal?: AbortSignal): Promise<LibraryLoadPlan>;
  applyLibraryLoad(input: LibraryLoadApplyInput, signal?: AbortSignal): Promise<LibraryOperation>;
  previewLibraryStop(runId: string, signal?: AbortSignal): Promise<LibraryStopPlan>;
  applyLibraryStop(runId: string, input: LibraryStopApplyInput, signal?: AbortSignal): Promise<LibraryOperation>;
  previewLibraryUninstall(installationId: string, signal?: AbortSignal): Promise<LibraryUninstallPlan>;
  applyLibraryUninstall(installationId: string, input: LibraryUninstallApplyInput, signal?: AbortSignal): Promise<LibraryOperation>;
  libraryOperation(operationId: string, signal?: AbortSignal): Promise<LibraryOperation>;
  retryLibraryOperation(operationId: string, signal?: AbortSignal): Promise<LibraryOperation>;
  libraryRunStatus(runId: string, signal?: AbortSignal): Promise<LibraryRunStatus>;
  libraryJobProgress(jobId: string, signal?: AbortSignal): Promise<JobDetail>;
  artifactJobsForRun(runId: string, signal?: AbortSignal): Promise<ArtifactJobList>;
  artifactJobCapabilities(signal?: AbortSignal): Promise<ArtifactJobCapabilities>;
  createArtifactJob(runId: string, input: ArtifactJobCreateInput, signal?: AbortSignal): Promise<ArtifactJob>;
  uploadArtifactJobInput(jobId: string, file: ArtifactJobInputFile, content: Blob, signal?: AbortSignal, onProgress?: (progress: ArtifactTransferProgress) => void): Promise<ArtifactJob>;
  finalizeArtifactJob(jobId: string, signal?: AbortSignal): Promise<ArtifactJob>;
  submitArtifactJob(jobId: string, signal?: AbortSignal): Promise<ArtifactJob>;
  artifactJob(jobId: string, signal?: AbortSignal): Promise<ArtifactJob>;
  cancelArtifactJob(jobId: string, reason: string, signal?: AbortSignal): Promise<ArtifactJob>;
  artifactJobResult(jobId: string, signal?: AbortSignal): Promise<ArtifactJob>;
  artifactJobResultUrl(jobId: string, sha256: string): string;
}
export interface ControlApi extends LibraryApi {
  fleetProfiles(signal?: AbortSignal): Promise<FleetProfileList>;
  fleetProfile(profileId: string, signal?: AbortSignal): Promise<FleetProfile>;
  createFleetProfile(input: FleetProfileInput, signal?: AbortSignal): Promise<FleetProfile>;
  updateFleetProfile(profileId: string, input: FleetProfileInput, signal?: AbortSignal): Promise<FleetProfile>;
  deleteFleetProfile(profileId: string, signal?: AbortSignal): Promise<void>;
  previewFleetProfile(profileId: string, signal?: AbortSignal): Promise<FleetProfilePreview>;
  applyFleetProfile(profileId: string, input: FleetProfileApplyInput, signal?: AbortSignal): Promise<FleetProfileApplication>;
  fleetProfileApplication(applicationId: string, signal?: AbortSignal): Promise<FleetProfileApplication>;
  previewRecipeRunSwitch(input: RunSwitchPreviewRequest, signal?: AbortSignal): Promise<RunSwitchPlan>;
  applyRecipeRunSwitch(input: RunSwitchApplyRequest, signal?: AbortSignal): Promise<RunSwitchOperation>;
  getRecipeRunSwitchOperation(operationId: string, signal?: AbortSignal): Promise<RunSwitchOperation>;
  captureCurrentFleetProfile(input: {name: string; description: string; installation_policy: FleetProfileInput["installation_policy"]; labels?: Record<string, string>; favorite: boolean}, signal?: AbortSignal): Promise<FleetProfile>;
  duplicateFleetProfile(profileId: string, input: {name: string; description?: string | null}, signal?: AbortSignal): Promise<FleetProfile>;
  fleetProfileStatus(profileId: string, signal?: AbortSignal): Promise<{schema_version: 2; profile_id: string; profile_digest: string; state: string; matched: boolean; drifted: boolean; scope: {node_ids: string[]; idle_node_ids?: string[]}; reasons: Array<{code: string; detail: string; severity: "info" | "warning" | "error"}>; generated_at: string}>;
  modelCacheInventory(cursor?: string, signal?: AbortSignal): Promise<ModelCacheInventoryResponse>;
  modelCacheEntry(artifactSetSha256: string, signal?: AbortSignal): Promise<CacheEntryResponse>;
  previewModelCacheDownload(input: ModelCacheDownloadPreviewInput, signal?: AbortSignal): Promise<ModelCacheDownloadPreviewResponse>;
  downloadModelCache(input: ModelCacheDownloadInput, signal?: AbortSignal): Promise<ModelCacheOperationResponse>;
  previewModelCacheRepair(input: ModelCacheRepairPreviewInput, signal?: AbortSignal): Promise<ModelCacheRepairPreviewResponse>;
  repairModelCache(input: ModelCacheRepairInput, signal?: AbortSignal): Promise<ModelCacheOperationResponse>;
  previewModelCacheEviction(input: ModelCacheEvictionPreviewInput, signal?: AbortSignal): Promise<ModelCacheEvictionPreviewResponse>;
  evictModelCache(input: ModelCacheEvictInput, signal?: AbortSignal): Promise<ModelCacheOperationResponse>;
  modelCacheUpdates(signal?: AbortSignal): Promise<ModelCacheUpdatesResponse>;
  modelCacheOperations(cursor?: string, signal?: AbortSignal): Promise<ModelCacheOperationsResponse>;
  modelCacheOperation(operationId: string, signal?: AbortSignal): Promise<ModelCacheOperationResponse>;
  visualFleet(signal?: AbortSignal): Promise<VisualFleetSnapshot>;
  fleetEvidence(signal?: AbortSignal): Promise<FleetEvidenceResponse>;
  nodeStatuses(signal?: AbortSignal): Promise<FleetEvidenceResponse>;
  nodeTelemetryHistory(nodeId: string, start: string, end: string, resolution: TelemetryResolution, maximumPoints: number, signal?: AbortSignal): Promise<TelemetryHistory>;
  nodeTelemetryCurrent(nodeId: string, signal?: AbortSignal): Promise<TelemetryCurrentResponse>;
  nodeTelemetryCapabilities(nodeId: string, signal?: AbortSignal): Promise<TelemetryCapabilitiesResponse>;
  nodeTelemetryWorkloads(nodeId: string, runId?: string, state?: string, signal?: AbortSignal): Promise<TelemetryWorkloadsResponse>;
  updateNodeProfile(nodeId: string, input: NodeProfileUpdate, signal?: AbortSignal): Promise<FleetNodeIdentity>;
  jobs(cursor?: string): Promise<JobsResponse>;
  job(jobId: string, operationCursor?: string, targetCursor?: string): Promise<JobDetail>;
  resumeJob(jobId: string): Promise<JobResumeResponse>;
  audit(): Promise<AuditResponse>;
  preview(input: ProposalInput): Promise<ProposalPreview>; submit(digest: string): Promise<Record<string, unknown>>;
  agents(): Promise<AgentsResponse>;
  enrollments(): Promise<EnrollmentListResponse>;
  createEnrollmentGrant(ttlSeconds: number, signal?: AbortSignal): Promise<EnrollmentGrantResponse>;
  createReenrollmentGrant(nodeId: string | undefined, ttlSeconds: number, signal?: AbortSignal): Promise<EnrollmentGrantResponse>;
  revokeAgentNode(nodeId: string): Promise<void>;
  previewAgentUpgrade(nodeIds: string[] | undefined, strategy: AgentUpgradeStrategy, repairManifest?: AgentRepairManifest, signal?: AbortSignal): Promise<AgentUpgradePlan>;
  applyAgentUpgrade(plan: AgentUpgradePlan, signal?: AbortSignal): Promise<{id: string; state: string}>;
}
