// Generated by scripts/generate-control-clients from
// vonk_agent_protocol.lifecycle_vocabulary. Do not edit.

export const LifecycleState = {
  QUEUED: "queued",
  RUNNING: "running",
  OBSERVING: "observing",
  BACKOFF: "backoff",
  SUCCEEDED: "succeeded",
  FAILED: "failed",
  CANCELLED: "cancelled",
  NEEDS_OPERATOR: "needs-operator",
} as const;
export type LifecycleState = (typeof LifecycleState)[keyof typeof LifecycleState];

export const AgentResultState = {
  SUCCEEDED: "succeeded",
  FAILED: "failed",
  CANCELLED: "cancelled",
  WAITING_FOR_OPERATOR: "waiting-for-operator",
} as const;
export type AgentResultState = (typeof AgentResultState)[keyof typeof AgentResultState];

export const LifecycleEffect = {
  UNKNOWN: "unknown",
  NONE: "none",
  ISSUED: "issued",
  ESTABLISHED: "established",
  STOPPED: "stopped",
} as const;
export type LifecycleEffect = (typeof LifecycleEffect)[keyof typeof LifecycleEffect];

export const OutcomeKind = {
  DONE: "done",
  FAILED: "failed",
  CANCELLED: "cancelled",
  UNKNOWN: "unknown",
} as const;
export type OutcomeKind = (typeof OutcomeKind)[keyof typeof OutcomeKind];

export const StopOutcome = {
  CONFIRMED: "confirmed",
  UNCONFIRMED: "unconfirmed",
} as const;
export type StopOutcome = (typeof StopOutcome)[keyof typeof StopOutcome];

export const LifecycleEventKind = {
  SUBMITTED: "submitted",
  CLAIMED: "claimed",
  HEARTBEAT: "heartbeat",
  REPORTED: "reported",
  LEASE_LAPSED: "lease-lapsed",
  CANCEL_REQUESTED: "cancel-requested",
  OBSERVED: "observed",
  OPERATOR_ACTION: "operator-action",
  TICK: "tick",
} as const;
export type LifecycleEventKind = (typeof LifecycleEventKind)[keyof typeof LifecycleEventKind];

export const OperatorActionName = {
  RESUME: "resume",
  RETIRE: "retire",
  RETRY: "retry",
  STOP: "stop",
} as const;
export type OperatorActionName = (typeof OperatorActionName)[keyof typeof OperatorActionName];

export const OperatorSurface = {
  RESUME: "resume",
  RETIRE: "retire",
  RETRY: "retry",
  STOP: "stop",
  AUTOMATIC: "automatic",
} as const;
export type OperatorSurface = (typeof OperatorSurface)[keyof typeof OperatorSurface];

export const BlockerCategory = {
  SECURITY_EDGE: "security-edge",
  INPUT_VALIDATION: "input-validation",
  ALREADY_RETRIED: "already-retried",
  BOOKKEEPING_DEBT: "bookkeeping-debt",
} as const;
export type BlockerCategory = (typeof BlockerCategory)[keyof typeof BlockerCategory];

export const WaitVerdict = {
  KEEP: "KEEP",
  SELF_HEAL: "SELF-HEAL",
  FIX_ACTION: "FIX-ACTION",
  DERIVED: "DERIVED",
} as const;
export type WaitVerdict = (typeof WaitVerdict)[keyof typeof WaitVerdict];

export const LifecycleSubject = {
  JOB: "Job",
  JOB_ATTEMPT: "JobAttempt",
  AGENT_OPERATION: "AgentOperation",
  AGENT_OPERATION_ATTEMPT: "AgentOperationAttempt",
  MODEL_CACHE_OPERATION: "ModelCacheOperation",
  ARTIFACT_JOB: "ArtifactJob",
  FLEET_PROFILE_APPLICATION: "FleetProfileApplication",
} as const;
export type LifecycleSubject = (typeof LifecycleSubject)[keyof typeof LifecycleSubject];

export const StateWriteKind = {
  ATTRIBUTE: "attribute",
  DICT_ITEM: "dict-item",
  BULK_UPDATE: "bulk-update",
  CONSTRUCTOR: "constructor",
  HELPER_CALL: "helper-call",
} as const;
export type StateWriteKind = (typeof StateWriteKind)[keyof typeof StateWriteKind];

export const MigrationStep = {
  STEP_2: "step-2",
  STEP_3: "step-3",
  STEP_4: "step-4",
  STEP_5: "step-5",
  STEP_6: "step-6",
  STEP_7: "step-7",
} as const;
export type MigrationStep = (typeof MigrationStep)[keyof typeof MigrationStep];

export const ErrorCategory = {
  SECURITY_REFUSAL: "security-refusal",
  INVALID_REQUEST: "invalid-request",
  UNKNOWN: "unknown",
} as const;
export type ErrorCategory = (typeof ErrorCategory)[keyof typeof ErrorCategory];

export const WaitReason = {
  OPERATION_NOT_ENABLED: "operation-not-enabled",
  UPGRADE_AWAITING_IDENTITY: "agent-upgrade-awaiting-identity",
  AGENT_RESTART_INTERRUPTED: "agent-restart-interrupted",
  STOP_UNCONFIRMED: "stop-unconfirmed",
  CLEANUP_UNCONFIRMED: "cleanup-unconfirmed",
  STOP_METADATA_UNCONFIRMED: "stop-metadata-unconfirmed",
  RETAINED_IDENTITY_MISMATCH: "retained-identity-mismatch",
  MODEL_CUSTODY_UNCONFIRMED: "model-custody-unconfirmed",
  RUNTIME_EFFECT_UNCONFIRMED: "runtime-effect-unconfirmed",
  JOB_STOP_UNCONFIRMED: "job-stop-unconfirmed",
  JOB_STATE_UNCERTAIN: "job-state-uncertain",
  LEASE_LAPSED: "lease-lapsed",
  REPORT_UNCERTAIN: "report-uncertain",
  OBSERVATION_UNAVAILABLE: "observation-unavailable",
  RECEIPT_MISSING: "receipt-missing",
  STALE_PLAN: "stale-plan",
  SCOPE_CHANGED: "scope-changed",
  LEGACY_UNCLASSIFIED: "legacy-unclassified",
} as const;
export type WaitReason = (typeof WaitReason)[keyof typeof WaitReason];

export const InvalidRequestReason = {
  MALFORMED: "malformed",
  OUT_OF_RANGE: "out-of-range",
  LIMIT_EXCEEDED: "limit-exceeded",
  UNKNOWN_FIELD: "unknown-field",
  INCOMPLETE: "incomplete",
  IMMUTABLE: "immutable",
  DUPLICATE: "duplicate",
  CONFLICT: "conflict",
  NOT_FOUND: "not-found",
  NOT_READY: "not-ready",
  SUPERSEDED: "superseded",
  UNSUPPORTED: "unsupported",
} as const;
export type InvalidRequestReason = (typeof InvalidRequestReason)[keyof typeof InvalidRequestReason];

export const SecurityRefusalReason = {
  HTTP_401: "401",
  HTTP_403: "403",
  AGENT_CERTIFICATE_ROTATION_CONFLICT: "agent.certificate.rotation.conflict",
  AGENT_ENROLLMENT_SUBMIT_REJECTED: "agent.enrollment.submit.rejected",
  AGENT_IDENTITY_MISMATCH: "agent.identity_mismatch",
  AGENT_TOMBSTONE_FENCED: "agent.tombstone_fenced",
  CATALOG_AUTHENTICATION_REQUIRED: "catalog.authentication_required",
  CONTROLLER_AUTHENTICATION_REQUIRED: "controller.authentication_required",
  CONTROLLER_FLEET_ENROLLMENT_DENIED: "controller.fleet.enrollment_denied",
  CONTROLLER_REQUEST_REJECTED: "controller.request_rejected",
  DISTRIBUTION_REVOKED: "distribution.revoked",
  FORBIDDEN: "forbidden",
  GRANT_INVALID: "grant_invalid",
  GRANT_NODE_MISMATCH: "grant_node_mismatch",
  GRANT_UNAUTHORIZED: "grant_unauthorized",
  HELPER_AUTHORIZATION_INVALID: "helper.authorization_invalid",
  HELPER_GRANT_INVALID: "helper_grant_invalid",
  HELPER_GRANT_NODE_MISMATCH: "helper_grant_node_mismatch",
  HELPER_GRANT_UNAUTHORIZED: "helper_grant_unauthorized",
  HELPER_OPERATION_INVALID_ARTIFACT: "helper_operation_invalid_artifact",
  HELPER_PEER_IDENTITY_INVALID: "helper_peer_identity_invalid",
  HELPER_REQUEST_INSTALLATION_IDENTITY_INVALID: "helper_request_installation_identity_invalid",
  HELPER_REQUEST_PLAN_BINDING_INVALID: "helper_request_plan_binding_invalid",
  HELPER_REQUEST_REPLAYED: "helper_request_replayed",
  HELPER_RUNTIME_IMAGE_IDENTITY_INVALID: "helper_runtime_image_identity_invalid",
  HOST_HELPER_AUTHORITY_DENIED: "host_helper.authority_denied",
  LOCAL_IDENTITY_EXPIRED: "local.identity_expired",
  LOCAL_IDENTITY_FAILED: "local.identity_failed",
  MODEL_CACHE_CREDENTIALS_DENIED: "model_cache.credentials_denied",
  MODEL_CACHE_CREDENTIALS_INVALID: "model_cache.credentials_invalid",
  MODEL_CACHE_SOURCE_ACCESS_DENIED: "model_cache.source_access_denied",
  OPERATION_INVALID_ARTIFACT: "operation_invalid_artifact",
  PEER_IDENTITY_INVALID: "peer_identity_invalid",
  PERMISSION_DENIED: "permission_denied",
  RECIPE_UPDATE_AUTHORITY_DENIED: "recipe_update.authority_denied",
  REQUEST_REPLAYED: "request_replayed",
  RUN_SWITCH_ARTIFACT_DIGEST_VERIFICATION_FAILED: "run-switch.artifact-digest-verification-failed",
  RUN_SWITCH_CLEANUP_NAS_EVICTION_FORBIDDEN: "run-switch.cleanup-nas-eviction-forbidden",
  RUN_SWITCH_CLEANUP_RECLAIMED_DIGEST_NOT_PLANNED: "run-switch.cleanup-reclaimed-digest-not-planned",
  RUN_SWITCH_RUNTIME_IMAGE_PREPARATION_DIGEST_MISMATCH: "run-switch.runtime-image-preparation-digest-mismatch",
  RUNTIME_IMAGE_AUTHORIZATION_INVALID: "runtime_image.authorization_invalid",
  RUNTIME_IMAGE_AUTHORIZATION_REVOKED: "runtime_image.authorization_revoked",
  RUNTIME_IMAGE_IDENTITY_INVALID: "runtime_image_identity_invalid",
  TUF_METADATA_INVALID: "tuf.metadata_invalid",
  TUF_SIGNATURE_INVALID: "tuf.signature_invalid",
  UNAUTHORIZED: "unauthorized",
} as const;
export type SecurityRefusalReason = (typeof SecurityRefusalReason)[keyof typeof SecurityRefusalReason];

export const FailureCode = {
  OPERATION_FAILED: "operation_failed",
  OPERATION_CANCELLED: "operation_cancelled",
  AGENT_UPGRADE_FAILED: "agent_upgrade_failed",
  ARTIFACT_DISTRIBUTION_FAILED: "artifact_distribution_failed",
  RECIPE_BUILD_FAILED: "recipe_build_failed",
  RECIPE_JOB_RUN_FAILED: "recipe_job_run_failed",
  RECIPE_INSTALL_FAILED: "recipe_install_failed",
  RECIPE_START_FAILED: "recipe_start_failed",
  RECIPE_STOP_FAILED: "recipe_stop_failed",
  RECIPE_UNINSTALL_FAILED: "recipe_uninstall_failed",
  RUNTIME_OBSERVATION_UNAVAILABLE: "runtime_observation_unavailable",
  INSTALLATION_RECONCILIATION_BUSY: "installation_reconciliation_busy",
  RECIPE_RECONCILIATION_DEPENDENCY_UNAVAILABLE: "recipe_reconciliation_dependency_unavailable",
} as const;
export type FailureCode = (typeof FailureCode)[keyof typeof FailureCode];

/** The stored spelling of an agent result that waits for an operator. */
export const LEGACY_WAIT_STATE = AgentResultState.WAITING_FOR_OPERATOR;
