""" Contains all the data models used in inputs/outputs """

from .activation_marker import ActivationMarker
from .activation_marker_state import ActivationMarkerState
from .admission_code import AdmissionCode
from .agent_client_decision import AgentClientDecision
from .agent_diagnostic_operation import AgentDiagnosticOperation
from .agent_evidence_code import AgentEvidenceCode
from .agent_failure_kind import AgentFailureKind
from .agent_failure_result import AgentFailureResult
from .agent_install_result import AgentInstallResult
from .agent_operation import AgentOperation
from .agent_operation_change import AgentOperationChange
from .agent_operation_payload import AgentOperationPayload
from .agent_package_source import AgentPackageSource
from .agent_result_state import AgentResultState
from .agent_transport_kind import AgentTransportKind
from .agent_upgrade_diagnostics_response import AgentUpgradeDiagnosticsResponse
from .agent_upgrade_identity_response import AgentUpgradeIdentityResponse
from .agent_upgrade_package import AgentUpgradePackage
from .agent_upgrade_payload import AgentUpgradePayload
from .agent_upgrade_repair_manifest import AgentUpgradeRepairManifest
from .agent_upgrade_request_intent import AgentUpgradeRequestIntent
from .agent_upgrade_result import AgentUpgradeResult
from .agent_upgrade_rollout_payload import AgentUpgradeRolloutPayload
from .agent_upgrade_rollout_payload_sources import AgentUpgradeRolloutPayloadSources
from .agent_upgrade_rollout_result import AgentUpgradeRolloutResult
from .agent_upgrade_rollout_result_skipped_type_0 import AgentUpgradeRolloutResultSkippedType0
from .agent_upgrade_target_diagnostics_response import AgentUpgradeTargetDiagnosticsResponse
from .api_runtime_observation import ApiRuntimeObservation
from .artifact_distribution_payload import ArtifactDistributionPayload
from .artifact_distribution_result import ArtifactDistributionResult
from .artifact_file_declaration import ArtifactFileDeclaration
from .artifact_input_contract import ArtifactInputContract
from .artifact_input_projection import ArtifactInputProjection
from .artifact_job_capabilities_response import ArtifactJobCapabilitiesResponse
from .artifact_job_create import ArtifactJobCreate
from .artifact_job_create_parameters import ArtifactJobCreateParameters
from .artifact_job_list_response import ArtifactJobListResponse
from .artifact_job_response import ArtifactJobResponse
from .artifact_job_response_interface import ArtifactJobResponseInterface
from .artifact_job_response_preparation_type_0 import ArtifactJobResponsePreparationType0
from .artifact_job_response_state_type_0 import ArtifactJobResponseStateType0
from .artifact_job_result_evidence import ArtifactJobResultEvidence
from .artifact_job_result_evidence_failure_kind_type_0 import ArtifactJobResultEvidenceFailureKindType0
from .artifact_job_storage_capabilities import ArtifactJobStorageCapabilities
from .artifact_job_transport_capabilities import ArtifactJobTransportCapabilities
from .artifact_lifecycle_code import ArtifactLifecycleCode
from .artifact_output_contract import ArtifactOutputContract
from .artifact_output_file import ArtifactOutputFile
from .artifact_output_limits import ArtifactOutputLimits
from .artifact_preparation import ArtifactPreparation
from .artifact_slot_contract import ArtifactSlotContract
from .artifact_storage_impact import ArtifactStorageImpact
from .artifact_storage_impact_missing_spark_bytes_by_node_type_0 import ArtifactStorageImpactMissingSparkBytesByNodeType0
from .artifact_storage_impact_nas_coverage import ArtifactStorageImpactNasCoverage
from .artifact_storage_impact_retention import ArtifactStorageImpactRetention
from .artifact_storage_impact_running_coverage import ArtifactStorageImpactRunningCoverage
from .artifact_storage_impact_spark_coverage import ArtifactStorageImpactSparkCoverage
from .artifact_verification_evidence import ArtifactVerificationEvidence
from .asset_availability import AssetAvailability
from .availability_job_payload import AvailabilityJobPayload
from .availability_job_result import AvailabilityJobResult
from .availability_model_child import AvailabilityModelChild
from .availability_model_child_state import AvailabilityModelChildState
from .availability_operation_failure import AvailabilityOperationFailure
from .availability_recovery_action import AvailabilityRecoveryAction
from .availability_retry import AvailabilityRetry
from .availability_runtime import AvailabilityRuntime
from .availability_runtime_placement_environment_type_0 import AvailabilityRuntimePlacementEnvironmentType0
from .availability_supersession import AvailabilitySupersession
from .blocker_category import BlockerCategory
from .bookkeeping_reason import BookkeepingReason
from .boolean_parameter import BooleanParameter
from .bounded_error_response import BoundedErrorResponse
from .build_cleanup_phase_operation import BuildCleanupPhaseOperation
from .build_compatibility_evidence import BuildCompatibilityEvidence
from .build_compatibility_evidence_state import BuildCompatibilityEvidenceState
from .build_context import BuildContext
from .build_model_artifact_projection import BuildModelArtifactProjection
from .build_network import BuildNetwork
from .build_patch import BuildPatch
from .build_phase_operation import BuildPhaseOperation
from .build_resources_projection import BuildResourcesProjection
from .build_security_projection import BuildSecurityProjection
from .build_source_evidence import BuildSourceEvidence
from .build_source_evidence_state import BuildSourceEvidenceState
from .cache_manifest import CacheManifest
from .cache_manifest_artifact import CacheManifestArtifact
from .cache_manifest_artifact_part import CacheManifestArtifactPart
from .cache_reference_reason import CacheReferenceReason
from .cache_removal_asset import CacheRemovalAsset
from .cache_removal_asset_disposition import CacheRemovalAssetDisposition
from .cache_removal_asset_kind import CacheRemovalAssetKind
from .cache_removal_blocker import CacheRemovalBlocker
from .cache_removal_finding import CacheRemovalFinding
from .cache_removal_finding_asset_kind import CacheRemovalFindingAssetKind
from .cache_removal_finding_classification import CacheRemovalFindingClassification
from .cache_removal_review import CacheRemovalReview
from .cache_removal_review_resource_kind import CacheRemovalReviewResourceKind
from .cached_resource_estimate import CachedResourceEstimate
from .cancel_request import CancelRequest
from .capability_availability import CapabilityAvailability
from .capability_reason import CapabilityReason
from .capability_status import CapabilityStatus
from .capability_unavailable_reply import CapabilityUnavailableReply
from .capacity_reservations import CapacityReservations
from .catalog_code import CatalogCode
from .catalog_problem import CatalogProblem
from .catalog_sync_code import CatalogSyncCode
from .catalog_sync_state import CatalogSyncState
from .certificate_code import CertificateCode
from .certificate_issuance_binding import CertificateIssuanceBinding
from .certificate_issuance_purpose import CertificateIssuancePurpose
from .certificate_journal_state import CertificateJournalState
from .certificate_record_state import CertificateRecordState
from .certificate_request_mode import CertificateRequestMode
from .certificate_rotation_state import CertificateRotationState
from .certificate_state import CertificateState
from .cli_token_download import CliTokenDownload
from .cli_update_contract import CliUpdateContract
from .cli_update_contract_worker_compatibility import CliUpdateContractWorkerCompatibility
from .cli_update_contract_worker_issue_type_0 import CliUpdateContractWorkerIssueType0
from .cluster_mapping_code import ClusterMappingCode
from .compatibility_identity import CompatibilityIdentity
from .compatibility_preparation import CompatibilityPreparation
from .compatibility_preparation_kind import CompatibilityPreparationKind
from .compatibility_preparation_stage import CompatibilityPreparationStage
from .compatibility_preparation_state import CompatibilityPreparationState
from .compiled_artifact import CompiledArtifact
from .compiled_artifact_contract import CompiledArtifactContract
from .compiled_artifact_contract_interface import CompiledArtifactContractInterface
from .compiled_artifact_mount import CompiledArtifactMount
from .compiled_endpoint import CompiledEndpoint
from .compiled_environment_entry import CompiledEnvironmentEntry
from .compiled_execution_plan import CompiledExecutionPlan
from .compiled_identity import CompiledIdentity
from .compiled_job import CompiledJob
from .compiled_job_input import CompiledJobInput
from .compiled_job_input_slot import CompiledJobInputSlot
from .compiled_job_interface import CompiledJobInterface
from .compiled_lifecycle import CompiledLifecycle
from .compiled_model_identity import CompiledModelIdentity
from .compiled_placement import CompiledPlacement
from .compiled_runtime import CompiledRuntime
from .compiled_runtime_image import CompiledRuntimeImage
from .compiled_security import CompiledSecurity
from .compiled_security_mount import CompiledSecurityMount
from .compiled_security_mount_source import CompiledSecurityMountSource
from .compiled_security_network_mode import CompiledSecurityNetworkMode
from .compiled_topology import CompiledTopology
from .conditional_post_stop_memory_check import ConditionalPostStopMemoryCheck
from .controller_asset_state import ControllerAssetState
from .controller_asset_state_source import ControllerAssetStateSource
from .controller_asset_state_state import ControllerAssetStateState
from .controller_capability import ControllerCapability
from .controller_error_code import ControllerErrorCode
from .desired_assignment_state import DesiredAssignmentState
from .distributed_recovery_marker import DistributedRecoveryMarker
from .distribution_assignment_state import DistributionAssignmentState
from .distribution_code import DistributionCode
from .distribution_job_payload import DistributionJobPayload
from .distribution_job_payload_assignments import DistributionJobPayloadAssignments
from .distribution_job_payload_phase import DistributionJobPayloadPhase
from .distribution_job_payload_target_totals import DistributionJobPayloadTargetTotals
from .distribution_object import DistributionObject
from .distribution_transfer_progress import DistributionTransferProgress
from .distribution_transfer_progress_phase import DistributionTransferProgressPhase
from .effective_parallelism import EffectiveParallelism
from .effective_settings_selection import EffectiveSettingsSelection
from .effective_settings_selection_change_effects import EffectiveSettingsSelectionChangeEffects
from .effective_settings_selection_change_effects_additional_property import EffectiveSettingsSelectionChangeEffectsAdditionalProperty
from .effective_settings_selection_kind import EffectiveSettingsSelectionKind
from .effective_settings_selection_knobs import EffectiveSettingsSelectionKnobs
from .empty_job_result import EmptyJobResult
from .endpoint_response import EndpointResponse
from .endpoint_state import EndpointState
from .enrollment_grant_response import EnrollmentGrantResponse
from .enrollment_grant_response_installer_url import EnrollmentGrantResponseInstallerUrl
from .enrollment_grant_state import EnrollmentGrantState
from .enrollment_grant_status import EnrollmentGrantStatus
from .enrollment_observation_outcome import EnrollmentObservationOutcome
from .enrollment_profile_state import EnrollmentProfileState
from .enrollment_purpose import EnrollmentPurpose
from .enrollment_record_state import EnrollmentRecordState
from .enrollment_revocation_status import EnrollmentRevocationStatus
from .enum_parameter import EnumParameter
from .error_catalog import ErrorCatalog
from .error_category import ErrorCategory
from .error_context_response import ErrorContextResponse
from .error_context_response_decision import ErrorContextResponseDecision
from .error_context_response_source import ErrorContextResponseSource
from .evidence_context import EvidenceContext
from .evidence_context_source import EvidenceContextSource
from .failure_code import FailureCode
from .failure_diagnostics import FailureDiagnostics
from .failure_diagnostics_category import FailureDiagnosticsCategory
from .failure_evidence_bundle import FailureEvidenceBundle
from .failure_log_tail import FailureLogTail
from .failure_property import FailureProperty
from .failure_stage import FailureStage
from .fleet_action_response import FleetActionResponse
from .fleet_action_response_action import FleetActionResponseAction
from .fleet_assignment_model_view import FleetAssignmentModelView
from .fleet_assignment_recipe_view import FleetAssignmentRecipeView
from .fleet_cache_summary import FleetCacheSummary
from .fleet_change_event import FleetChangeEvent
from .fleet_enroll_request import FleetEnrollRequest
from .fleet_frame_issue import FleetFrameIssue
from .fleet_frame_issue_reason_code import FleetFrameIssueReasonCode
from .fleet_lock_holder import FleetLockHolder
from .fleet_locks_response import FleetLocksResponse
from .fleet_log_entry import FleetLogEntry
from .fleet_log_entry_level import FleetLogEntryLevel
from .fleet_log_entry_source import FleetLogEntrySource
from .fleet_log_response import FleetLogResponse
from .fleet_node import FleetNode
from .fleet_node_identity import FleetNodeIdentity
from .fleet_node_labels_type_0 import FleetNodeLabelsType0
from .fleet_node_view import FleetNodeView
from .fleet_open_transaction import FleetOpenTransaction
from .fleet_profile_admission_decision import FleetProfileAdmissionDecision
from .fleet_profile_adopted_application_effect import FleetProfileAdoptedApplicationEffect
from .fleet_profile_adopted_stop_effect import FleetProfileAdoptedStopEffect
from .fleet_profile_application_cancel_request import FleetProfileApplicationCancelRequest
from .fleet_profile_application_cancellation_intent import FleetProfileApplicationCancellationIntent
from .fleet_profile_application_cancellation_intent_cause import FleetProfileApplicationCancellationIntentCause
from .fleet_profile_application_cancellation_intent_state import FleetProfileApplicationCancellationIntentState
from .fleet_profile_application_cancellation_view import FleetProfileApplicationCancellationView
from .fleet_profile_application_cancellation_view_cause import FleetProfileApplicationCancellationViewCause
from .fleet_profile_application_cancellation_view_state import FleetProfileApplicationCancellationViewState
from .fleet_profile_application_effect import FleetProfileApplicationEffect
from .fleet_profile_application_effect_kind import FleetProfileApplicationEffectKind
from .fleet_profile_application_effect_outcome import FleetProfileApplicationEffectOutcome
from .fleet_profile_application_progress import FleetProfileApplicationProgress
from .fleet_profile_application_progress_step_results import FleetProfileApplicationProgressStepResults
from .fleet_profile_application_projection_issue import FleetProfileApplicationProjectionIssue
from .fleet_profile_application_result import FleetProfileApplicationResult
from .fleet_profile_application_view import FleetProfileApplicationView
from .fleet_profile_application_view_state import FleetProfileApplicationViewState
from .fleet_profile_assignment import FleetProfileAssignment
from .fleet_profile_assignment_assessment import FleetProfileAssignmentAssessment
from .fleet_profile_assignment_failure import FleetProfileAssignmentFailure
from .fleet_profile_assignment_input import FleetProfileAssignmentInput
from .fleet_profile_assignment_input_option_choices import FleetProfileAssignmentInputOptionChoices
from .fleet_profile_assignment_option_choices import FleetProfileAssignmentOptionChoices
from .fleet_profile_assignment_preparation import FleetProfileAssignmentPreparation
from .fleet_profile_assignment_preview import FleetProfileAssignmentPreview
from .fleet_profile_assignment_preview_actions_item import FleetProfileAssignmentPreviewActionsItem
from .fleet_profile_assignment_preview_option_choices import FleetProfileAssignmentPreviewOptionChoices
from .fleet_profile_assignment_view import FleetProfileAssignmentView
from .fleet_profile_assignment_view_option_choices import FleetProfileAssignmentViewOptionChoices
from .fleet_profile_child_progress import FleetProfileChildProgress
from .fleet_profile_child_progress_phase import FleetProfileChildProgressPhase
from .fleet_profile_compatibility_decision import FleetProfileCompatibilityDecision
from .fleet_profile_compatibility_decision_kind import FleetProfileCompatibilityDecisionKind
from .fleet_profile_compatibility_decision_stage import FleetProfileCompatibilityDecisionStage
from .fleet_profile_definition import FleetProfileDefinition
from .fleet_profile_definition_installation_policy import FleetProfileDefinitionInstallationPolicy
from .fleet_profile_definition_labels import FleetProfileDefinitionLabels
from .fleet_profile_definition_view import FleetProfileDefinitionView
from .fleet_profile_effect_progress import FleetProfileEffectProgress
from .fleet_profile_effect_progress_kind import FleetProfileEffectProgressKind
from .fleet_profile_effect_progress_state import FleetProfileEffectProgressState
from .fleet_profile_effects import FleetProfileEffects
from .fleet_profile_endpoint_assignment_view import FleetProfileEndpointAssignmentView
from .fleet_profile_endpoint_projection_issue import FleetProfileEndpointProjectionIssue
from .fleet_profile_endpoints_view import FleetProfileEndpointsView
from .fleet_profile_endpoints_view_application_state_type_0 import FleetProfileEndpointsViewApplicationStateType0
from .fleet_profile_input import FleetProfileInput
from .fleet_profile_input_installation_policy import FleetProfileInputInstallationPolicy
from .fleet_profile_input_labels import FleetProfileInputLabels
from .fleet_profile_installation_effect import FleetProfileInstallationEffect
from .fleet_profile_installation_effect_action import FleetProfileInstallationEffectAction
from .fleet_profile_intended_configuration import FleetProfileIntendedConfiguration
from .fleet_profile_intended_configuration_installation_policy import FleetProfileIntendedConfigurationInstallationPolicy
from .fleet_profile_list import FleetProfileList
from .fleet_profile_load_request import FleetProfileLoadRequest
from .fleet_profile_node import FleetProfileNode
from .fleet_profile_pending_effect import FleetProfilePendingEffect
from .fleet_profile_pending_effect_kind import FleetProfilePendingEffectKind
from .fleet_profile_plan_step import FleetProfilePlanStep
from .fleet_profile_plan_step_kind import FleetProfilePlanStepKind
from .fleet_profile_plan_summary import FleetProfilePlanSummary
from .fleet_profile_preparation_decision import FleetProfilePreparationDecision
from .fleet_profile_preview import FleetProfilePreview
from .fleet_profile_reason import FleetProfileReason
from .fleet_profile_reason_severity import FleetProfileReasonSeverity
from .fleet_profile_resource_requirement import FleetProfileResourceRequirement
from .fleet_profile_resource_requirement_memory_kind_type_0 import FleetProfileResourceRequirementMemoryKindType0
from .fleet_profile_resource_requirement_memory_pool_type_0 import FleetProfileResourceRequirementMemoryPoolType0
from .fleet_profile_run_effect import FleetProfileRunEffect
from .fleet_profile_run_effect_action import FleetProfileRunEffectAction
from .fleet_profile_scope import FleetProfileScope
from .fleet_profile_scope_preview import FleetProfileScopePreview
from .fleet_profile_step_result import FleetProfileStepResult
from .fleet_profile_switch_adapter_result import FleetProfileSwitchAdapterResult
from .fleet_profile_switch_adapter_state import FleetProfileSwitchAdapterState
from .fleet_profile_switch_adapter_state_state import FleetProfileSwitchAdapterStateState
from .fleet_profile_switch_child_result import FleetProfileSwitchChildResult
from .fleet_profile_switch_child_state import FleetProfileSwitchChildState
from .fleet_profile_switch_child_state_kind import FleetProfileSwitchChildStateKind
from .fleet_profile_switch_child_state_state import FleetProfileSwitchChildStateState
from .fleet_profile_switch_pending_child import FleetProfileSwitchPendingChild
from .fleet_profile_switch_pending_child_kind import FleetProfileSwitchPendingChildKind
from .fleet_profile_switch_queue_item import FleetProfileSwitchQueueItem
from .fleet_profile_switch_queue_item_kind import FleetProfileSwitchQueueItemKind
from .fleet_profile_verification_result import FleetProfileVerificationResult
from .fleet_profile_view import FleetProfileView
from .fleet_profile_view_installation_policy import FleetProfileViewInstallationPolicy
from .fleet_profile_view_labels import FleetProfileViewLabels
from .fleet_reenroll_request import FleetReenrollRequest
from .fleet_refresh_event import FleetRefreshEvent
from .fleet_refresh_event_reset_reason import FleetRefreshEventResetReason
from .fleet_rename_request import FleetRenameRequest
from .fleet_snapshot import FleetSnapshot
from .fleet_telemetry_event import FleetTelemetryEvent
from .fleet_upgrade_request import FleetUpgradeRequest
from .float_parameter import FloatParameter
from .freshness_evidence import FreshnessEvidence
from .freshness_evidence_state import FreshnessEvidenceState
from .freshness_policy import FreshnessPolicy
from .gateway_key_create_request import GatewayKeyCreateRequest
from .gateway_key_created import GatewayKeyCreated
from .gateway_key_list import GatewayKeyList
from .gateway_key_revoked import GatewayKeyRevoked
from .gateway_key_view import GatewayKeyView
from .gateway_route_state import GatewayRouteState
from .get_fleet_log_info_source_type_0 import GetFleetLogInfoSourceType0
from .git_hub_release_asset import GitHubReleaseAsset
from .git_hub_release_source import GitHubReleaseSource
from .gpu_unavailable_reason import GpuUnavailableReason
from .helper_error_code import HelperErrorCode
from .helper_operation_code import HelperOperationCode
from .host_helper_response_status import HostHelperResponseStatus
from .image_store_code import ImageStoreCode
from .install_admission_code import InstallAdmissionCode
from .install_degraded_reason import InstallDegradedReason
from .install_partial_evidence import InstallPartialEvidence
from .install_phase_operation import InstallPhaseOperation
from .installation_node_change import InstallationNodeChange
from .installation_node_payload import InstallationNodePayload
from .installation_node_state import InstallationNodeState
from .installation_reconcile_request import InstallationReconcileRequest
from .installation_state import InstallationState
from .integer_parameter import IntegerParameter
from .invalid_request import InvalidRequest
from .invalid_request_reason import InvalidRequestReason
from .inventory_state import InventoryState
from .inventory_state_freshness import InventoryStateFreshness
from .invocation_metadata import InvocationMetadata
from .invocation_metadata_context import InvocationMetadataContext
from .job_change import JobChange
from .job_detail_response import JobDetailResponse
from .job_operation_response import JobOperationResponse
from .job_payload import JobPayload
from .job_progress import JobProgress
from .job_resume_request import JobResumeRequest
from .job_resume_request_disposition import JobResumeRequestDisposition
from .job_resume_response import JobResumeResponse
from .job_run_phase_operation import JobRunPhaseOperation
from .job_run_stop_scope import JobRunStopScope
from .journal_repair_purpose import JournalRepairPurpose
from .library_assessment_code import LibraryAssessmentCode
from .library_facet_values import LibraryFacetValues
from .library_filter_values import LibraryFilterValues
from .library_filter_values_sort_type_0 import LibraryFilterValuesSortType0
from .library_local_progress import LibraryLocalProgress
from .library_local_progress_state import LibraryLocalProgressState
from .library_local_state import LibraryLocalState
from .library_local_state_controller import LibraryLocalStateController
from .library_model_identity import LibraryModelIdentity
from .library_model_projection import LibraryModelProjection
from .library_projection_code import LibraryProjectionCode
from .library_recipe_identity import LibraryRecipeIdentity
from .library_recipe_model import LibraryRecipeModel
from .library_recipe_projection import LibraryRecipeProjection
from .library_release import LibraryRelease
from .library_resource_projection import LibraryResourceProjection
from .lifecycle_code_failure_result import LifecycleCodeFailureResult
from .lifecycle_effect import LifecycleEffect
from .lifecycle_event_kind import LifecycleEventKind
from .lifecycle_preflight_checkpoint import LifecyclePreflightCheckpoint
from .lifecycle_preflight_checkpoint_attempts import LifecyclePreflightCheckpointAttempts
from .lifecycle_preflight_checkpoint_receipts import LifecyclePreflightCheckpointReceipts
from .lifecycle_state import LifecycleState
from .lifecycle_subject import LifecycleSubject
from .lifecycle_vocabulary import LifecycleVocabulary
from .list_model_library_sort import ListModelLibrarySort
from .list_recipe_library_sort import ListRecipeLibrarySort
from .managed_catalog_stale_recipe import ManagedCatalogStaleRecipe
from .managed_catalog_sync_failure import ManagedCatalogSyncFailure
from .managed_catalog_sync_problem import ManagedCatalogSyncProblem
from .managed_catalog_sync_response import ManagedCatalogSyncResponse
from .managed_catalog_sync_response_trigger import ManagedCatalogSyncResponseTrigger
from .managed_catalog_sync_result import ManagedCatalogSyncResult
from .managed_catalog_sync_result_state import ManagedCatalogSyncResultState
from .managed_catalog_withdrawn_recipe import ManagedCatalogWithdrawnRecipe
from .mapping_selection import MappingSelection
from .mapping_selection_action import MappingSelectionAction
from .mapping_selection_option_choices import MappingSelectionOptionChoices
from .mapping_selection_parameters import MappingSelectionParameters
from .memory_usage_uncertainty import MemoryUsageUncertainty
from .migration_step import MigrationStep
from .model_artifact_identity import ModelArtifactIdentity
from .model_artifact_preparation import ModelArtifactPreparation
from .model_artifact_preparation_completeness import ModelArtifactPreparationCompleteness
from .model_cache_access_recheck import ModelCacheAccessRecheck
from .model_cache_blocker_code import ModelCacheBlockerCode
from .model_cache_cancellation import ModelCacheCancellation
from .model_cache_cancellation_observation import ModelCacheCancellationObservation
from .model_cache_cancellation_observation_effect import ModelCacheCancellationObservationEffect
from .model_cache_cancellation_request import ModelCacheCancellationRequest
from .model_cache_claim import ModelCacheClaim
from .model_cache_code import ModelCacheCode
from .model_cache_download_payload import ModelCacheDownloadPayload
from .model_cache_download_result import ModelCacheDownloadResult
from .model_cache_missing_source_observation import ModelCacheMissingSourceObservation
from .model_cache_missing_source_observation_status import ModelCacheMissingSourceObservationStatus
from .model_cache_operation_progress import ModelCacheOperationProgress
from .model_cache_operation_progress_phase import ModelCacheOperationProgressPhase
from .model_cache_operator_request import ModelCacheOperatorRequest
from .model_cache_operator_response import ModelCacheOperatorResponse
from .model_cache_operator_response_action import ModelCacheOperatorResponseAction
from .model_cache_operator_response_state_type_1 import ModelCacheOperatorResponseStateType1
from .model_cache_operator_status import ModelCacheOperatorStatus
from .model_cache_removal_payload import ModelCacheRemovalPayload
from .model_cache_removal_request import ModelCacheRemovalRequest
from .model_cache_removal_result import ModelCacheRemovalResult
from .model_cache_repair_checkpoint import ModelCacheRepairCheckpoint
from .model_cache_repair_payload import ModelCacheRepairPayload
from .model_cache_retry import ModelCacheRetry
from .model_cache_transfer import ModelCacheTransfer
from .model_cache_transfer_artifact import ModelCacheTransferArtifact
from .model_cache_transfer_artifacts import ModelCacheTransferArtifacts
from .model_definition import ModelDefinition
from .model_definition_modalities_item import ModelDefinitionModalitiesItem
from .model_detail_response import ModelDetailResponse
from .model_family import ModelFamily
from .model_file import ModelFile
from .model_file_part import ModelFilePart
from .model_file_state import ModelFileState
from .model_format import ModelFormat
from .model_identity import ModelIdentity
from .model_library_response import ModelLibraryResponse
from .model_license import ModelLicense
from .model_metadata import ModelMetadata
from .model_record import ModelRecord
from .model_reference import ModelReference
from .model_revision_projection import ModelRevisionProjection
from .model_revision_projection_modalities_item import ModelRevisionProjectionModalitiesItem
from .model_source import ModelSource
from .model_territorial_restrictions import ModelTerritorialRestrictions
from .native_progress_witness import NativeProgressWitness
from .network_interface import NetworkInterface
from .network_interface_kind import NetworkInterfaceKind
from .node_connection import NodeConnection
from .node_connection_agent_state import NodeConnectionAgentState
from .node_connection_online_state import NodeConnectionOnlineState
from .node_distribution_assignment import NodeDistributionAssignment
from .node_identity_state import NodeIdentityState
from .node_offline_reason import NodeOfflineReason
from .node_profile_change import NodeProfileChange
from .node_profile_payload import NodeProfilePayload
from .node_telemetry_payload import NodeTelemetryPayload
from .observation_cause import ObservationCause
from .observation_transfer_chunk import ObservationTransferChunk
from .observation_transfer_complete import ObservationTransferComplete
from .observation_transfer_error import ObservationTransferError
from .observation_transfer_start import ObservationTransferStart
from .observation_transfer_start_resource import ObservationTransferStartResource
from .observed_assignment_state import ObservedAssignmentState
from .oci_failure_category import OciFailureCategory
from .offline_stop_intent import OfflineStopIntent
from .operation_blocker import OperationBlocker
from .operation_blocker_severity import OperationBlockerSeverity
from .operation_checkpoint import OperationCheckpoint
from .operation_detail_response import OperationDetailResponse
from .operation_evidence_download import OperationEvidenceDownload
from .operation_failure_code import OperationFailureCode
from .operation_failure_evidence import OperationFailureEvidence
from .operation_member_progress import OperationMemberProgress
from .operation_member_progress_activity_type_0 import OperationMemberProgressActivityType0
from .operation_owner_reference import OperationOwnerReference
from .operation_progress import OperationProgress
from .operation_progress_activity_type_0 import OperationProgressActivityType0
from .operation_projection_issue import OperationProjectionIssue
from .operation_projection_issue_field import OperationProjectionIssueField
from .operation_recovery import OperationRecovery
from .operation_recovery_action import OperationRecoveryAction
from .operations_response import OperationsResponse
from .operator_action_name import OperatorActionName
from .operator_surface import OperatorSurface
from .outcome_done import OutcomeDone
from .outcome_evidence import OutcomeEvidence
from .outcome_failed import OutcomeFailed
from .outcome_kind import OutcomeKind
from .outcome_unknown import OutcomeUnknown
from .output_limits import OutputLimits
from .package_activation_phase import PackageActivationPhase
from .package_activation_receipt import PackageActivationReceipt
from .package_rollback_authority import PackageRollbackAuthority
from .package_rollback_source import PackageRollbackSource
from .placement_install_state import PlacementInstallState
from .placement_load_state import PlacementLoadState
from .platform_observation import PlatformObservation
from .platform_observation_worker_issue_type_0 import PlatformObservationWorkerIssueType0
from .prebuilt_image import PrebuiltImage
from .prebuilt_image_code import PrebuiltImageCode
from .preparation_reason import PreparationReason
from .preparation_reason_severity import PreparationReasonSeverity
from .profile_action import ProfileAction
from .profile_cancellation_cause import ProfileCancellationCause
from .profile_child_job_kind import ProfileChildJobKind
from .profile_child_phase import ProfileChildPhase
from .profile_child_source import ProfileChildSource
from .profile_document_state import ProfileDocumentState
from .profile_effect_state import ProfileEffectState
from .profile_installation_policy import ProfileInstallationPolicy
from .profile_job_run_stop_authorization import ProfileJobRunStopAuthorization
from .profile_job_run_stop_job import ProfileJobRunStopJob
from .profile_job_run_stop_phase_item import ProfileJobRunStopPhaseItem
from .profile_job_run_stop_target import ProfileJobRunStopTarget
from .profile_operation_kind import ProfileOperationKind
from .profile_partial_stop import ProfilePartialStop
from .profile_projection_kind import ProfileProjectionKind
from .profile_reason_code import ProfileReasonCode
from .profile_reason_severity import ProfileReasonSeverity
from .profile_reported_phase import ProfileReportedPhase
from .profile_retry_disposition import ProfileRetryDisposition
from .profile_stop_owner_binding import ProfileStopOwnerBinding
from .profile_switch_child_kind import ProfileSwitchChildKind
from .progress_phase import ProgressPhase
from .projection_code import ProjectionCode
from .projection_reason import ProjectionReason
from .projection_reason_severity import ProjectionReasonSeverity
from .reason_code_vocabulary import ReasonCodeVocabulary
from .recipe_alternative import RecipeAlternative
from .recipe_alternative_cache import RecipeAlternativeCache
from .recipe_alternative_fits_fleet import RecipeAlternativeFitsFleet
from .recipe_build_adapter import RecipeBuildAdapter
from .recipe_build_adapter_definition import RecipeBuildAdapterDefinition
from .recipe_build_additional_context import RecipeBuildAdditionalContext
from .recipe_build_base_image import RecipeBuildBaseImage
from .recipe_build_cleanup_evidence import RecipeBuildCleanupEvidence
from .recipe_build_cleanup_parent import RecipeBuildCleanupParent
from .recipe_build_cleanup_parent_owner_kind import RecipeBuildCleanupParentOwnerKind
from .recipe_build_cleanup_request import RecipeBuildCleanupRequest
from .recipe_build_code import RecipeBuildCode
from .recipe_build_definition import RecipeBuildDefinition
from .recipe_build_dependency import RecipeBuildDependency
from .recipe_build_environment_argument import RecipeBuildEnvironmentArgument
from .recipe_build_evidence import RecipeBuildEvidence
from .recipe_build_intent import RecipeBuildIntent
from .recipe_build_intent_kind import RecipeBuildIntentKind
from .recipe_build_limits import RecipeBuildLimits
from .recipe_build_metadata import RecipeBuildMetadata
from .recipe_build_network import RecipeBuildNetwork
from .recipe_build_options import RecipeBuildOptions
from .recipe_build_options_format import RecipeBuildOptionsFormat
from .recipe_build_options_layer_compression import RecipeBuildOptionsLayerCompression
from .recipe_build_options_squash import RecipeBuildOptionsSquash
from .recipe_build_parent import RecipeBuildParent
from .recipe_build_parent_owner_kind import RecipeBuildParentOwnerKind
from .recipe_build_request import RecipeBuildRequest
from .recipe_cache_removal_checkpoint import RecipeCacheRemovalCheckpoint
from .recipe_cache_removal_intent import RecipeCacheRemovalIntent
from .recipe_cache_removal_model_child import RecipeCacheRemovalModelChild
from .recipe_cache_removal_owner import RecipeCacheRemovalOwner
from .recipe_cache_removal_plan import RecipeCacheRemovalPlan
from .recipe_cache_removal_result import RecipeCacheRemovalResult
from .recipe_cancellation_request import RecipeCancellationRequest
from .recipe_definition import RecipeDefinition
from .recipe_detail_response import RecipeDetailResponse
from .recipe_disk_resources import RecipeDiskResources
from .recipe_download_request import RecipeDownloadRequest
from .recipe_embedding_settings import RecipeEmbeddingSettings
from .recipe_embedding_settings_knobs import RecipeEmbeddingSettingsKnobs
from .recipe_execution import RecipeExecution
from .recipe_generation_settings import RecipeGenerationSettings
from .recipe_generation_settings_knobs import RecipeGenerationSettingsKnobs
from .recipe_http_serving_request import RecipeHttpServingRequest
from .recipe_http_serving_request_body_type_0 import RecipeHttpServingRequestBodyType0
from .recipe_http_serving_request_method import RecipeHttpServingRequestMethod
from .recipe_identity import RecipeIdentity
from .recipe_image import RecipeImage
from .recipe_image_availability_action import RecipeImageAvailabilityAction
from .recipe_image_availability_artifact import RecipeImageAvailabilityArtifact
from .recipe_image_availability_child import RecipeImageAvailabilityChild
from .recipe_image_availability_child_kind import RecipeImageAvailabilityChildKind
from .recipe_image_availability_child_state import RecipeImageAvailabilityChildState
from .recipe_image_availability_response import RecipeImageAvailabilityResponse
from .recipe_image_availability_response_state import RecipeImageAvailabilityResponseState
from .recipe_image_availability_result import RecipeImageAvailabilityResult
from .recipe_image_code import RecipeImageCode
from .recipe_input_slot import RecipeInputSlot
from .recipe_install_parent import RecipeInstallParent
from .recipe_install_parent_owner_kind import RecipeInstallParentOwnerKind
from .recipe_install_payload import RecipeInstallPayload
from .recipe_installation_change import RecipeInstallationChange
from .recipe_installation_payload import RecipeInstallationPayload
from .recipe_integer_setting import RecipeIntegerSetting
from .recipe_integer_setting_change_effect import RecipeIntegerSettingChangeEffect
from .recipe_job_activate_parent import RecipeJobActivateParent
from .recipe_job_activate_parent_owner_kind import RecipeJobActivateParentOwnerKind
from .recipe_job_evidence import RecipeJobEvidence
from .recipe_job_file import RecipeJobFile
from .recipe_job_input import RecipeJobInput
from .recipe_job_input_file import RecipeJobInputFile
from .recipe_job_input_manifest import RecipeJobInputManifest
from .recipe_job_interface import RecipeJobInterface
from .recipe_job_interface_adapter import RecipeJobInterfaceAdapter
from .recipe_job_output import RecipeJobOutput
from .recipe_job_output_limits import RecipeJobOutputLimits
from .recipe_job_output_manifest import RecipeJobOutputManifest
from .recipe_job_output_mapping import RecipeJobOutputMapping
from .recipe_job_run_parent import RecipeJobRunParent
from .recipe_job_run_parent_owner_kind import RecipeJobRunParentOwnerKind
from .recipe_job_run_request import RecipeJobRunRequest
from .recipe_job_run_result import RecipeJobRunResult
from .recipe_job_serving_request import RecipeJobServingRequest
from .recipe_job_serving_request_input_slots import RecipeJobServingRequestInputSlots
from .recipe_job_settings import RecipeJobSettings
from .recipe_job_settings_knobs import RecipeJobSettingsKnobs
from .recipe_library_response import RecipeLibraryResponse
from .recipe_lifecycle import RecipeLifecycle
from .recipe_memory_resources import RecipeMemoryResources
from .recipe_metadata import RecipeMetadata
from .recipe_metadata_alignment_type_0 import RecipeMetadataAlignmentType0
from .recipe_model_file import RecipeModelFile
from .recipe_model_selection import RecipeModelSelection
from .recipe_mount import RecipeMount
from .recipe_open_ai_interface import RecipeOpenAIInterface
from .recipe_operation_activated_result import RecipeOperationActivatedResult
from .recipe_operation_cancellation_result import RecipeOperationCancellationResult
from .recipe_operation_cancellation_result_launch_evidence_type_0 import RecipeOperationCancellationResultLaunchEvidenceType0
from .recipe_operation_cancellation_result_node_evidence_type_0 import RecipeOperationCancellationResultNodeEvidenceType0
from .recipe_operation_code import RecipeOperationCode
from .recipe_operation_progress_result import RecipeOperationProgressResult
from .recipe_operation_progress_result_launch_evidence_type_0 import RecipeOperationProgressResultLaunchEvidenceType0
from .recipe_operation_progress_result_node_evidence_type_0 import RecipeOperationProgressResultNodeEvidenceType0
from .recipe_operation_result import RecipeOperationResult
from .recipe_operation_result_launch_evidence_type_0 import RecipeOperationResultLaunchEvidenceType0
from .recipe_operation_result_node_evidence import RecipeOperationResultNodeEvidence
from .recipe_operation_stopped_result import RecipeOperationStoppedResult
from .recipe_operator_request import RecipeOperatorRequest
from .recipe_operator_response import RecipeOperatorResponse
from .recipe_operator_response_state import RecipeOperatorResponseState
from .recipe_option import RecipeOption
from .recipe_option_choice import RecipeOptionChoice
from .recipe_option_choice_env import RecipeOptionChoiceEnv
from .recipe_output_slot import RecipeOutputSlot
from .recipe_package_code import RecipePackageCode
from .recipe_package_handle_projection import RecipePackageHandleProjection
from .recipe_parallelism import RecipeParallelism
from .recipe_presence import RecipePresence
from .recipe_provenance import RecipeProvenance
from .recipe_readiness import RecipeReadiness
from .recipe_readiness_check import RecipeReadinessCheck
from .recipe_readiness_check_state import RecipeReadinessCheckState
from .recipe_reconcile_parent import RecipeReconcileParent
from .recipe_reconcile_parent_owner_kind import RecipeReconcileParentOwnerKind
from .recipe_reconcile_payload import RecipeReconcilePayload
from .recipe_reconcile_result import RecipeReconcileResult
from .recipe_release import RecipeRelease
from .recipe_removal_projection_issue import RecipeRemovalProjectionIssue
from .recipe_removal_unavailable_view import RecipeRemovalUnavailableView
from .recipe_retry_intent import RecipeRetryIntent
from .recipe_revision_intent import RecipeRevisionIntent
from .recipe_revision_projection import RecipeRevisionProjection
from .recipe_role_resources import RecipeRoleResources
from .recipe_run_change import RecipeRunChange
from .recipe_run_disposition_value import RecipeRunDispositionValue
from .recipe_run_payload import RecipeRunPayload
from .recipe_runtime import RecipeRuntime
from .recipe_runtime_argument import RecipeRuntimeArgument
from .recipe_runtime_environment import RecipeRuntimeEnvironment
from .recipe_selector_intent import RecipeSelectorIntent
from .recipe_serving_validation import RecipeServingValidation
from .recipe_serving_validation_interface import RecipeServingValidationInterface
from .recipe_setting import RecipeSetting
from .recipe_setting_change_effect import RecipeSettingChangeEffect
from .recipe_start_parent import RecipeStartParent
from .recipe_start_parent_owner_kind import RecipeStartParentOwnerKind
from .recipe_start_payload import RecipeStartPayload
from .recipe_start_payload_phase_type_0 import RecipeStartPayloadPhaseType0
from .recipe_start_result import RecipeStartResult
from .recipe_stop_parent import RecipeStopParent
from .recipe_stop_parent_owner_kind import RecipeStopParentOwnerKind
from .recipe_stop_payload import RecipeStopPayload
from .recipe_stop_result import RecipeStopResult
from .recipe_topology import RecipeTopology
from .recipe_topology_role import RecipeTopologyRole
from .recipe_uninstall_parent import RecipeUninstallParent
from .recipe_uninstall_parent_owner_kind import RecipeUninstallParentOwnerKind
from .recipe_uninstall_payload import RecipeUninstallPayload
from .recipe_uninstall_result import RecipeUninstallResult
from .recipe_update_child import RecipeUpdateChild
from .recipe_update_child_state import RecipeUpdateChildState
from .recipe_update_code import RecipeUpdateCode
from .recipe_update_document import RecipeUpdateDocument
from .recipe_update_failure import RecipeUpdateFailure
from .recipe_update_notice import RecipeUpdateNotice
from .recipe_update_request import RecipeUpdateRequest
from .recipe_update_response import RecipeUpdateResponse
from .recipe_update_response_state import RecipeUpdateResponseState
from .recipe_update_scope import RecipeUpdateScope
from .recipe_validation import RecipeValidation
from .recipe_validation_check import RecipeValidationCheck
from .recipe_validation_check_assertions_item import RecipeValidationCheckAssertionsItem
from .recipe_validation_check_kind import RecipeValidationCheckKind
from .reconcile_code import ReconcileCode
from .reconcile_phase_operation import ReconcilePhaseOperation
from .recovery_start_item import RecoveryStartItem
from .removed_recipe_node_result import RemovedRecipeNodeResult
from .request_validation_issue import RequestValidationIssue
from .request_validation_problem import RequestValidationProblem
from .reservation_state import ReservationState
from .residue import Residue
from .resource_blocker_code import ResourceBlockerCode
from .resource_demand_evidence import ResourceDemandEvidence
from .resource_demand_evidence_evidence_state import ResourceDemandEvidenceEvidenceState
from .resource_planning_code import ResourcePlanningCode
from .resource_term import ResourceTerm
from .resource_term_problem import ResourceTermProblem
from .rollout_preparation import RolloutPreparation
from .route_claim_marker import RouteClaimMarker
from .route_publication_state import RoutePublicationState
from .route_state import RouteState
from .run_admission_code import RunAdmissionCode
from .run_degraded_reason import RunDegradedReason
from .run_memory_residual_range import RunMemoryResidualRange
from .run_memory_residual_range_reservation_kind import RunMemoryResidualRangeReservationKind
from .run_node_change import RunNodeChange
from .run_node_payload import RunNodePayload
from .run_presence import RunPresence
from .run_presence_group_state import RunPresenceGroupState
from .run_presence_option_choices import RunPresenceOptionChoices
from .run_state import RunState
from .run_switch_apply_request import RunSwitchApplyRequest
from .run_switch_apply_request_action import RunSwitchApplyRequestAction
from .run_switch_apply_request_option_choices import RunSwitchApplyRequestOptionChoices
from .run_switch_apply_request_retention import RunSwitchApplyRequestRetention
from .run_switch_assessment import RunSwitchAssessment
from .run_switch_build_evidence import RunSwitchBuildEvidence
from .run_switch_build_evidence_state import RunSwitchBuildEvidenceState
from .run_switch_cached_transfer_result import RunSwitchCachedTransferResult
from .run_switch_cached_transfer_result_cached_target_totals import RunSwitchCachedTransferResultCachedTargetTotals
from .run_switch_cancellation import RunSwitchCancellation
from .run_switch_child_progress import RunSwitchChildProgress
from .run_switch_child_progress_phase_type_0 import RunSwitchChildProgressPhaseType0
from .run_switch_cleanup_intent import RunSwitchCleanupIntent
from .run_switch_cleanup_intent_cleanup_mode import RunSwitchCleanupIntentCleanupMode
from .run_switch_cleanup_result import RunSwitchCleanupResult
from .run_switch_cleanup_result_subphase_type_0 import RunSwitchCleanupResultSubphaseType0
from .run_switch_cleanup_verify_result import RunSwitchCleanupVerifyResult
from .run_switch_cleanup_verify_result_cleanup_mode import RunSwitchCleanupVerifyResultCleanupMode
from .run_switch_cleanup_verify_result_subphase_type_0 import RunSwitchCleanupVerifyResultSubphaseType0
from .run_switch_code import RunSwitchCode
from .run_switch_container_build_result import RunSwitchContainerBuildResult
from .run_switch_container_build_result_state import RunSwitchContainerBuildResultState
from .run_switch_distribution_child_result import RunSwitchDistributionChildResult
from .run_switch_distribution_ended_result import RunSwitchDistributionEndedResult
from .run_switch_final_verify_result import RunSwitchFinalVerifyResult
from .run_switch_final_verify_result_subphase_type_0 import RunSwitchFinalVerifyResultSubphaseType0
from .run_switch_installation_verify_result import RunSwitchInstallationVerifyResult
from .run_switch_installation_verify_result_subphase_type_0 import RunSwitchInstallationVerifyResultSubphaseType0
from .run_switch_job_payload import RunSwitchJobPayload
from .run_switch_job_payload_action import RunSwitchJobPayloadAction
from .run_switch_job_payload_operation_kind import RunSwitchJobPayloadOperationKind
from .run_switch_journal_repair_end_evidence import RunSwitchJournalRepairEndEvidence
from .run_switch_journal_repair_evidence import RunSwitchJournalRepairEvidence
from .run_switch_journal_repair_pending_state import RunSwitchJournalRepairPendingState
from .run_switch_member_progress import RunSwitchMemberProgress
from .run_switch_member_progress_phase_type_0 import RunSwitchMemberProgressPhaseType0
from .run_switch_member_progress_state import RunSwitchMemberProgressState
from .run_switch_member_receipt import RunSwitchMemberReceipt
from .run_switch_member_receipt_phase_type_0 import RunSwitchMemberReceiptPhaseType0
from .run_switch_member_receipt_state import RunSwitchMemberReceiptState
from .run_switch_model_download_pending_result import RunSwitchModelDownloadPendingResult
from .run_switch_model_download_result import RunSwitchModelDownloadResult
from .run_switch_operation import RunSwitchOperation
from .run_switch_operation_action import RunSwitchOperationAction
from .run_switch_operation_cleanup_mode_type_0 import RunSwitchOperationCleanupModeType0
from .run_switch_operation_completed_phases_item import RunSwitchOperationCompletedPhasesItem
from .run_switch_operation_current_phase_type_0 import RunSwitchOperationCurrentPhaseType0
from .run_switch_operation_kind import RunSwitchOperationKind
from .run_switch_operation_result import RunSwitchOperationResult
from .run_switch_operation_result_completed_phases_item import RunSwitchOperationResultCompletedPhasesItem
from .run_switch_operation_result_failed_phase_type_0 import RunSwitchOperationResultFailedPhaseType0
from .run_switch_operation_result_phase_type_0 import RunSwitchOperationResultPhaseType0
from .run_switch_operation_result_subphase_type_0 import RunSwitchOperationResultSubphaseType0
from .run_switch_operation_state import RunSwitchOperationState
from .run_switch_phase import RunSwitchPhase
from .run_switch_phase_kind import RunSwitchPhaseKind
from .run_switch_phase_state import RunSwitchPhaseState
from .run_switch_phase_subphase_type_0 import RunSwitchPhaseSubphaseType0
from .run_switch_plan import RunSwitchPlan
from .run_switch_plan_action import RunSwitchPlanAction
from .run_switch_plan_cleanup_disposition import RunSwitchPlanCleanupDisposition
from .run_switch_plan_cleanup_mode import RunSwitchPlanCleanupMode
from .run_switch_prepared_result import RunSwitchPreparedResult
from .run_switch_profile_stop_intent import RunSwitchProfileStopIntent
from .run_switch_profile_stop_scope import RunSwitchProfileStopScope
from .run_switch_progress import RunSwitchProgress
from .run_switch_progress_phase_type_0 import RunSwitchProgressPhaseType0
from .run_switch_progress_state import RunSwitchProgressState
from .run_switch_progress_subphase_type_0 import RunSwitchProgressSubphaseType0
from .run_switch_rank_receipt import RunSwitchRankReceipt
from .run_switch_reason import RunSwitchReason
from .run_switch_reason_scope import RunSwitchReasonScope
from .run_switch_reason_severity import RunSwitchReasonSeverity
from .run_switch_reconciliation_authority import RunSwitchReconciliationAuthority
from .run_switch_reconciliation_target import RunSwitchReconciliationTarget
from .run_switch_reconciliation_target_state import RunSwitchReconciliationTargetState
from .run_switch_run_intent import RunSwitchRunIntent
from .run_switch_runtime_image_reference_intent import RunSwitchRuntimeImageReferenceIntent
from .run_switch_runtime_image_result import RunSwitchRuntimeImageResult
from .run_switch_runtime_install_result import RunSwitchRuntimeInstallResult
from .run_switch_runtime_plan_result import RunSwitchRuntimePlanResult
from .run_switch_start_result import RunSwitchStartResult
from .run_switch_start_result_subphase_type_0 import RunSwitchStartResultSubphaseType0
from .run_switch_stop_intent import RunSwitchStopIntent
from .run_switch_stop_result import RunSwitchStopResult
from .run_switch_stop_result_subphase_type_0 import RunSwitchStopResultSubphaseType0
from .run_switch_target_transfer_evidence_result import RunSwitchTargetTransferEvidenceResult
from .run_switch_target_transfer_result import RunSwitchTargetTransferResult
from .run_switch_target_transfer_result_assignments import RunSwitchTargetTransferResultAssignments
from .run_switch_uninstall_result import RunSwitchUninstallResult
from .run_switch_uninstall_result_disposition import RunSwitchUninstallResultDisposition
from .run_switch_uninstall_result_subphase_type_0 import RunSwitchUninstallResultSubphaseType0
from .run_switch_verify_result import RunSwitchVerifyResult
from .run_switch_verify_result_cached_target_totals import RunSwitchVerifyResultCachedTargetTotals
from .runtime_argument import RuntimeArgument
from .runtime_environment_entry import RuntimeEnvironmentEntry
from .runtime_image_code import RuntimeImageCode
from .runtime_image_identity import RuntimeImageIdentity
from .runtime_image_preparation import RuntimeImagePreparation
from .runtime_image_receipt import RuntimeImageReceipt
from .runtime_image_reference_intent import RuntimeImageReferenceIntent
from .runtime_image_storage_impact import RuntimeImageStorageImpact
from .runtime_image_storage_impact_missing_image_distribution_bytes_by_node_type_0 import RuntimeImageStorageImpactMissingImageDistributionBytesByNodeType0
from .runtime_image_storage_impact_nas_coverage import RuntimeImageStorageImpactNasCoverage
from .runtime_image_storage_impact_running_coverage import RuntimeImageStorageImpactRunningCoverage
from .runtime_image_storage_impact_spark_coverage import RuntimeImageStorageImpactSparkCoverage
from .runtime_preflight_code import RuntimePreflightCode
from .runtime_preflight_finding import RuntimePreflightFinding
from .runtime_preflight_finding_code import RuntimePreflightFindingCode
from .runtime_preflight_finding_status import RuntimePreflightFindingStatus
from .runtime_preflight_request import RuntimePreflightRequest
from .runtime_preflight_request_fabric_connectivity import RuntimePreflightRequestFabricConnectivity
from .runtime_preflight_result import RuntimePreflightResult
from .runtime_telemetry_projection import RuntimeTelemetryProjection
from .saved_profile_projection_issue import SavedProfileProjectionIssue
from .security_refusal import SecurityRefusal
from .security_refusal_reason import SecurityRefusalReason
from .service_run_stop_review import ServiceRunStopReview
from .service_run_stop_review_exact_payloads_type_0 import ServiceRunStopReviewExactPayloadsType0
from .service_run_stop_review_stage import ServiceRunStopReviewStage
from .source_bundle_code import SourceBundleCode
from .source_bundle_file import SourceBundleFile
from .source_bundle_file_mode import SourceBundleFileMode
from .source_bundle_manifest import SourceBundleManifest
from .source_policy_code import SourcePolicyCode
from .spark_fit import SparkFit
from .spark_fit_node import SparkFitNode
from .spark_fit_node_memory_kind_type_0 import SparkFitNodeMemoryKindType0
from .spark_fit_node_memory_pool_type_0 import SparkFitNodeMemoryPoolType0
from .spark_group import SparkGroup
from .spark_group_node import SparkGroupNode
from .start_phase_operation import StartPhaseOperation
from .state_alias import StateAlias
from .state_write_kind import StateWriteKind
from .stop_impact import StopImpact
from .stop_outcome import StopOutcome
from .stop_phase_operation import StopPhaseOperation
from .stop_plan_code import StopPlanCode
from .storage_demand_code import StorageDemandCode
from .stored_admission_reason import StoredAdmissionReason
from .stored_build_policy_report import StoredBuildPolicyReport
from .stored_install_node_plan import StoredInstallNodePlan
from .stored_installation_plan import StoredInstallationPlan
from .stored_installation_plan_compiled_execution_plans import StoredInstallationPlanCompiledExecutionPlans
from .stored_policy_finding import StoredPolicyFinding
from .stored_prebuilt_decision import StoredPrebuiltDecision
from .stored_run_endpoint import StoredRunEndpoint
from .stored_run_node_plan import StoredRunNodePlan
from .stored_run_node_plan_memory_kind import StoredRunNodePlanMemoryKind
from .stored_run_node_plan_memory_pool import StoredRunNodePlanMemoryPool
from .stored_run_plan import StoredRunPlan
from .string_parameter import StringParameter
from .supersede_code import SupersedeCode
from .target_asset_state import TargetAssetState
from .target_asset_state_state import TargetAssetStateState
from .telemetry_point import TelemetryPoint
from .telemetry_state import TelemetryState
from .telemetry_state_freshness import TelemetryStateFreshness
from .topology_code import TopologyCode
from .unavailable_fleet_profile_view import UnavailableFleetProfileView
from .unavailable_recipe_presence import UnavailableRecipePresence
from .unavailable_run_presence import UnavailableRunPresence
from .uninstall_phase_operation import UninstallPhaseOperation
from .uninstall_plan_code import UninstallPlanCode
from .unknown_error import UnknownError
from .unprojected_revision import UnprojectedRevision
from .wait_reason import WaitReason
from .wait_verdict import WaitVerdict
from .worker_runtime_observation import WorkerRuntimeObservation
from .writable_path import WritablePath

__all__ = (
    "ActivationMarker",
    "ActivationMarkerState",
    "AdmissionCode",
    "AgentClientDecision",
    "AgentDiagnosticOperation",
    "AgentEvidenceCode",
    "AgentFailureKind",
    "AgentFailureResult",
    "AgentInstallResult",
    "AgentOperation",
    "AgentOperationChange",
    "AgentOperationPayload",
    "AgentPackageSource",
    "AgentResultState",
    "AgentTransportKind",
    "AgentUpgradeDiagnosticsResponse",
    "AgentUpgradeIdentityResponse",
    "AgentUpgradePackage",
    "AgentUpgradePayload",
    "AgentUpgradeRepairManifest",
    "AgentUpgradeRequestIntent",
    "AgentUpgradeResult",
    "AgentUpgradeRolloutPayload",
    "AgentUpgradeRolloutPayloadSources",
    "AgentUpgradeRolloutResult",
    "AgentUpgradeRolloutResultSkippedType0",
    "AgentUpgradeTargetDiagnosticsResponse",
    "ApiRuntimeObservation",
    "ArtifactDistributionPayload",
    "ArtifactDistributionResult",
    "ArtifactFileDeclaration",
    "ArtifactInputContract",
    "ArtifactInputProjection",
    "ArtifactJobCapabilitiesResponse",
    "ArtifactJobCreate",
    "ArtifactJobCreateParameters",
    "ArtifactJobListResponse",
    "ArtifactJobResponse",
    "ArtifactJobResponseInterface",
    "ArtifactJobResponsePreparationType0",
    "ArtifactJobResponseStateType0",
    "ArtifactJobResultEvidence",
    "ArtifactJobResultEvidenceFailureKindType0",
    "ArtifactJobStorageCapabilities",
    "ArtifactJobTransportCapabilities",
    "ArtifactLifecycleCode",
    "ArtifactOutputContract",
    "ArtifactOutputFile",
    "ArtifactOutputLimits",
    "ArtifactPreparation",
    "ArtifactSlotContract",
    "ArtifactStorageImpact",
    "ArtifactStorageImpactMissingSparkBytesByNodeType0",
    "ArtifactStorageImpactNasCoverage",
    "ArtifactStorageImpactRetention",
    "ArtifactStorageImpactRunningCoverage",
    "ArtifactStorageImpactSparkCoverage",
    "ArtifactVerificationEvidence",
    "AssetAvailability",
    "AvailabilityJobPayload",
    "AvailabilityJobResult",
    "AvailabilityModelChild",
    "AvailabilityModelChildState",
    "AvailabilityOperationFailure",
    "AvailabilityRecoveryAction",
    "AvailabilityRetry",
    "AvailabilityRuntime",
    "AvailabilityRuntimePlacementEnvironmentType0",
    "AvailabilitySupersession",
    "BlockerCategory",
    "BookkeepingReason",
    "BooleanParameter",
    "BoundedErrorResponse",
    "BuildCleanupPhaseOperation",
    "BuildCompatibilityEvidence",
    "BuildCompatibilityEvidenceState",
    "BuildContext",
    "BuildModelArtifactProjection",
    "BuildNetwork",
    "BuildPatch",
    "BuildPhaseOperation",
    "BuildResourcesProjection",
    "BuildSecurityProjection",
    "BuildSourceEvidence",
    "BuildSourceEvidenceState",
    "CachedResourceEstimate",
    "CacheManifest",
    "CacheManifestArtifact",
    "CacheManifestArtifactPart",
    "CacheReferenceReason",
    "CacheRemovalAsset",
    "CacheRemovalAssetDisposition",
    "CacheRemovalAssetKind",
    "CacheRemovalBlocker",
    "CacheRemovalFinding",
    "CacheRemovalFindingAssetKind",
    "CacheRemovalFindingClassification",
    "CacheRemovalReview",
    "CacheRemovalReviewResourceKind",
    "CancelRequest",
    "CapabilityAvailability",
    "CapabilityReason",
    "CapabilityStatus",
    "CapabilityUnavailableReply",
    "CapacityReservations",
    "CatalogCode",
    "CatalogProblem",
    "CatalogSyncCode",
    "CatalogSyncState",
    "CertificateCode",
    "CertificateIssuanceBinding",
    "CertificateIssuancePurpose",
    "CertificateJournalState",
    "CertificateRecordState",
    "CertificateRequestMode",
    "CertificateRotationState",
    "CertificateState",
    "CliTokenDownload",
    "CliUpdateContract",
    "CliUpdateContractWorkerCompatibility",
    "CliUpdateContractWorkerIssueType0",
    "ClusterMappingCode",
    "CompatibilityIdentity",
    "CompatibilityPreparation",
    "CompatibilityPreparationKind",
    "CompatibilityPreparationStage",
    "CompatibilityPreparationState",
    "CompiledArtifact",
    "CompiledArtifactContract",
    "CompiledArtifactContractInterface",
    "CompiledArtifactMount",
    "CompiledEndpoint",
    "CompiledEnvironmentEntry",
    "CompiledExecutionPlan",
    "CompiledIdentity",
    "CompiledJob",
    "CompiledJobInput",
    "CompiledJobInputSlot",
    "CompiledJobInterface",
    "CompiledLifecycle",
    "CompiledModelIdentity",
    "CompiledPlacement",
    "CompiledRuntime",
    "CompiledRuntimeImage",
    "CompiledSecurity",
    "CompiledSecurityMount",
    "CompiledSecurityMountSource",
    "CompiledSecurityNetworkMode",
    "CompiledTopology",
    "ConditionalPostStopMemoryCheck",
    "ControllerAssetState",
    "ControllerAssetStateSource",
    "ControllerAssetStateState",
    "ControllerCapability",
    "ControllerErrorCode",
    "DesiredAssignmentState",
    "DistributedRecoveryMarker",
    "DistributionAssignmentState",
    "DistributionCode",
    "DistributionJobPayload",
    "DistributionJobPayloadAssignments",
    "DistributionJobPayloadPhase",
    "DistributionJobPayloadTargetTotals",
    "DistributionObject",
    "DistributionTransferProgress",
    "DistributionTransferProgressPhase",
    "EffectiveParallelism",
    "EffectiveSettingsSelection",
    "EffectiveSettingsSelectionChangeEffects",
    "EffectiveSettingsSelectionChangeEffectsAdditionalProperty",
    "EffectiveSettingsSelectionKind",
    "EffectiveSettingsSelectionKnobs",
    "EmptyJobResult",
    "EndpointResponse",
    "EndpointState",
    "EnrollmentGrantResponse",
    "EnrollmentGrantResponseInstallerUrl",
    "EnrollmentGrantState",
    "EnrollmentGrantStatus",
    "EnrollmentObservationOutcome",
    "EnrollmentProfileState",
    "EnrollmentPurpose",
    "EnrollmentRecordState",
    "EnrollmentRevocationStatus",
    "EnumParameter",
    "ErrorCatalog",
    "ErrorCategory",
    "ErrorContextResponse",
    "ErrorContextResponseDecision",
    "ErrorContextResponseSource",
    "EvidenceContext",
    "EvidenceContextSource",
    "FailureCode",
    "FailureDiagnostics",
    "FailureDiagnosticsCategory",
    "FailureEvidenceBundle",
    "FailureLogTail",
    "FailureProperty",
    "FailureStage",
    "FleetActionResponse",
    "FleetActionResponseAction",
    "FleetAssignmentModelView",
    "FleetAssignmentRecipeView",
    "FleetCacheSummary",
    "FleetChangeEvent",
    "FleetEnrollRequest",
    "FleetFrameIssue",
    "FleetFrameIssueReasonCode",
    "FleetLockHolder",
    "FleetLocksResponse",
    "FleetLogEntry",
    "FleetLogEntryLevel",
    "FleetLogEntrySource",
    "FleetLogResponse",
    "FleetNode",
    "FleetNodeIdentity",
    "FleetNodeLabelsType0",
    "FleetNodeView",
    "FleetOpenTransaction",
    "FleetProfileAdmissionDecision",
    "FleetProfileAdoptedApplicationEffect",
    "FleetProfileAdoptedStopEffect",
    "FleetProfileApplicationCancellationIntent",
    "FleetProfileApplicationCancellationIntentCause",
    "FleetProfileApplicationCancellationIntentState",
    "FleetProfileApplicationCancellationView",
    "FleetProfileApplicationCancellationViewCause",
    "FleetProfileApplicationCancellationViewState",
    "FleetProfileApplicationCancelRequest",
    "FleetProfileApplicationEffect",
    "FleetProfileApplicationEffectKind",
    "FleetProfileApplicationEffectOutcome",
    "FleetProfileApplicationProgress",
    "FleetProfileApplicationProgressStepResults",
    "FleetProfileApplicationProjectionIssue",
    "FleetProfileApplicationResult",
    "FleetProfileApplicationView",
    "FleetProfileApplicationViewState",
    "FleetProfileAssignment",
    "FleetProfileAssignmentAssessment",
    "FleetProfileAssignmentFailure",
    "FleetProfileAssignmentInput",
    "FleetProfileAssignmentInputOptionChoices",
    "FleetProfileAssignmentOptionChoices",
    "FleetProfileAssignmentPreparation",
    "FleetProfileAssignmentPreview",
    "FleetProfileAssignmentPreviewActionsItem",
    "FleetProfileAssignmentPreviewOptionChoices",
    "FleetProfileAssignmentView",
    "FleetProfileAssignmentViewOptionChoices",
    "FleetProfileChildProgress",
    "FleetProfileChildProgressPhase",
    "FleetProfileCompatibilityDecision",
    "FleetProfileCompatibilityDecisionKind",
    "FleetProfileCompatibilityDecisionStage",
    "FleetProfileDefinition",
    "FleetProfileDefinitionInstallationPolicy",
    "FleetProfileDefinitionLabels",
    "FleetProfileDefinitionView",
    "FleetProfileEffectProgress",
    "FleetProfileEffectProgressKind",
    "FleetProfileEffectProgressState",
    "FleetProfileEffects",
    "FleetProfileEndpointAssignmentView",
    "FleetProfileEndpointProjectionIssue",
    "FleetProfileEndpointsView",
    "FleetProfileEndpointsViewApplicationStateType0",
    "FleetProfileInput",
    "FleetProfileInputInstallationPolicy",
    "FleetProfileInputLabels",
    "FleetProfileInstallationEffect",
    "FleetProfileInstallationEffectAction",
    "FleetProfileIntendedConfiguration",
    "FleetProfileIntendedConfigurationInstallationPolicy",
    "FleetProfileList",
    "FleetProfileLoadRequest",
    "FleetProfileNode",
    "FleetProfilePendingEffect",
    "FleetProfilePendingEffectKind",
    "FleetProfilePlanStep",
    "FleetProfilePlanStepKind",
    "FleetProfilePlanSummary",
    "FleetProfilePreparationDecision",
    "FleetProfilePreview",
    "FleetProfileReason",
    "FleetProfileReasonSeverity",
    "FleetProfileResourceRequirement",
    "FleetProfileResourceRequirementMemoryKindType0",
    "FleetProfileResourceRequirementMemoryPoolType0",
    "FleetProfileRunEffect",
    "FleetProfileRunEffectAction",
    "FleetProfileScope",
    "FleetProfileScopePreview",
    "FleetProfileStepResult",
    "FleetProfileSwitchAdapterResult",
    "FleetProfileSwitchAdapterState",
    "FleetProfileSwitchAdapterStateState",
    "FleetProfileSwitchChildResult",
    "FleetProfileSwitchChildState",
    "FleetProfileSwitchChildStateKind",
    "FleetProfileSwitchChildStateState",
    "FleetProfileSwitchPendingChild",
    "FleetProfileSwitchPendingChildKind",
    "FleetProfileSwitchQueueItem",
    "FleetProfileSwitchQueueItemKind",
    "FleetProfileVerificationResult",
    "FleetProfileView",
    "FleetProfileViewInstallationPolicy",
    "FleetProfileViewLabels",
    "FleetReenrollRequest",
    "FleetRefreshEvent",
    "FleetRefreshEventResetReason",
    "FleetRenameRequest",
    "FleetSnapshot",
    "FleetTelemetryEvent",
    "FleetUpgradeRequest",
    "FloatParameter",
    "FreshnessEvidence",
    "FreshnessEvidenceState",
    "FreshnessPolicy",
    "GatewayKeyCreated",
    "GatewayKeyCreateRequest",
    "GatewayKeyList",
    "GatewayKeyRevoked",
    "GatewayKeyView",
    "GatewayRouteState",
    "GetFleetLogInfoSourceType0",
    "GitHubReleaseAsset",
    "GitHubReleaseSource",
    "GpuUnavailableReason",
    "HelperErrorCode",
    "HelperOperationCode",
    "HostHelperResponseStatus",
    "ImageStoreCode",
    "InstallAdmissionCode",
    "InstallationNodeChange",
    "InstallationNodePayload",
    "InstallationNodeState",
    "InstallationReconcileRequest",
    "InstallationState",
    "InstallDegradedReason",
    "InstallPartialEvidence",
    "InstallPhaseOperation",
    "IntegerParameter",
    "InvalidRequest",
    "InvalidRequestReason",
    "InventoryState",
    "InventoryStateFreshness",
    "InvocationMetadata",
    "InvocationMetadataContext",
    "JobChange",
    "JobDetailResponse",
    "JobOperationResponse",
    "JobPayload",
    "JobProgress",
    "JobResumeRequest",
    "JobResumeRequestDisposition",
    "JobResumeResponse",
    "JobRunPhaseOperation",
    "JobRunStopScope",
    "JournalRepairPurpose",
    "LibraryAssessmentCode",
    "LibraryFacetValues",
    "LibraryFilterValues",
    "LibraryFilterValuesSortType0",
    "LibraryLocalProgress",
    "LibraryLocalProgressState",
    "LibraryLocalState",
    "LibraryLocalStateController",
    "LibraryModelIdentity",
    "LibraryModelProjection",
    "LibraryProjectionCode",
    "LibraryRecipeIdentity",
    "LibraryRecipeModel",
    "LibraryRecipeProjection",
    "LibraryRelease",
    "LibraryResourceProjection",
    "LifecycleCodeFailureResult",
    "LifecycleEffect",
    "LifecycleEventKind",
    "LifecyclePreflightCheckpoint",
    "LifecyclePreflightCheckpointAttempts",
    "LifecyclePreflightCheckpointReceipts",
    "LifecycleState",
    "LifecycleSubject",
    "LifecycleVocabulary",
    "ListModelLibrarySort",
    "ListRecipeLibrarySort",
    "ManagedCatalogStaleRecipe",
    "ManagedCatalogSyncFailure",
    "ManagedCatalogSyncProblem",
    "ManagedCatalogSyncResponse",
    "ManagedCatalogSyncResponseTrigger",
    "ManagedCatalogSyncResult",
    "ManagedCatalogSyncResultState",
    "ManagedCatalogWithdrawnRecipe",
    "MappingSelection",
    "MappingSelectionAction",
    "MappingSelectionOptionChoices",
    "MappingSelectionParameters",
    "MemoryUsageUncertainty",
    "MigrationStep",
    "ModelArtifactIdentity",
    "ModelArtifactPreparation",
    "ModelArtifactPreparationCompleteness",
    "ModelCacheAccessRecheck",
    "ModelCacheBlockerCode",
    "ModelCacheCancellation",
    "ModelCacheCancellationObservation",
    "ModelCacheCancellationObservationEffect",
    "ModelCacheCancellationRequest",
    "ModelCacheClaim",
    "ModelCacheCode",
    "ModelCacheDownloadPayload",
    "ModelCacheDownloadResult",
    "ModelCacheMissingSourceObservation",
    "ModelCacheMissingSourceObservationStatus",
    "ModelCacheOperationProgress",
    "ModelCacheOperationProgressPhase",
    "ModelCacheOperatorRequest",
    "ModelCacheOperatorResponse",
    "ModelCacheOperatorResponseAction",
    "ModelCacheOperatorResponseStateType1",
    "ModelCacheOperatorStatus",
    "ModelCacheRemovalPayload",
    "ModelCacheRemovalRequest",
    "ModelCacheRemovalResult",
    "ModelCacheRepairCheckpoint",
    "ModelCacheRepairPayload",
    "ModelCacheRetry",
    "ModelCacheTransfer",
    "ModelCacheTransferArtifact",
    "ModelCacheTransferArtifacts",
    "ModelDefinition",
    "ModelDefinitionModalitiesItem",
    "ModelDetailResponse",
    "ModelFamily",
    "ModelFile",
    "ModelFilePart",
    "ModelFileState",
    "ModelFormat",
    "ModelIdentity",
    "ModelLibraryResponse",
    "ModelLicense",
    "ModelMetadata",
    "ModelRecord",
    "ModelReference",
    "ModelRevisionProjection",
    "ModelRevisionProjectionModalitiesItem",
    "ModelSource",
    "ModelTerritorialRestrictions",
    "NativeProgressWitness",
    "NetworkInterface",
    "NetworkInterfaceKind",
    "NodeConnection",
    "NodeConnectionAgentState",
    "NodeConnectionOnlineState",
    "NodeDistributionAssignment",
    "NodeIdentityState",
    "NodeOfflineReason",
    "NodeProfileChange",
    "NodeProfilePayload",
    "NodeTelemetryPayload",
    "ObservationCause",
    "ObservationTransferChunk",
    "ObservationTransferComplete",
    "ObservationTransferError",
    "ObservationTransferStart",
    "ObservationTransferStartResource",
    "ObservedAssignmentState",
    "OciFailureCategory",
    "OfflineStopIntent",
    "OperationBlocker",
    "OperationBlockerSeverity",
    "OperationCheckpoint",
    "OperationDetailResponse",
    "OperationEvidenceDownload",
    "OperationFailureCode",
    "OperationFailureEvidence",
    "OperationMemberProgress",
    "OperationMemberProgressActivityType0",
    "OperationOwnerReference",
    "OperationProgress",
    "OperationProgressActivityType0",
    "OperationProjectionIssue",
    "OperationProjectionIssueField",
    "OperationRecovery",
    "OperationRecoveryAction",
    "OperationsResponse",
    "OperatorActionName",
    "OperatorSurface",
    "OutcomeDone",
    "OutcomeEvidence",
    "OutcomeFailed",
    "OutcomeKind",
    "OutcomeUnknown",
    "OutputLimits",
    "PackageActivationPhase",
    "PackageActivationReceipt",
    "PackageRollbackAuthority",
    "PackageRollbackSource",
    "PlacementInstallState",
    "PlacementLoadState",
    "PlatformObservation",
    "PlatformObservationWorkerIssueType0",
    "PrebuiltImage",
    "PrebuiltImageCode",
    "PreparationReason",
    "PreparationReasonSeverity",
    "ProfileAction",
    "ProfileCancellationCause",
    "ProfileChildJobKind",
    "ProfileChildPhase",
    "ProfileChildSource",
    "ProfileDocumentState",
    "ProfileEffectState",
    "ProfileInstallationPolicy",
    "ProfileJobRunStopAuthorization",
    "ProfileJobRunStopJob",
    "ProfileJobRunStopPhaseItem",
    "ProfileJobRunStopTarget",
    "ProfileOperationKind",
    "ProfilePartialStop",
    "ProfileProjectionKind",
    "ProfileReasonCode",
    "ProfileReasonSeverity",
    "ProfileReportedPhase",
    "ProfileRetryDisposition",
    "ProfileStopOwnerBinding",
    "ProfileSwitchChildKind",
    "ProgressPhase",
    "ProjectionCode",
    "ProjectionReason",
    "ProjectionReasonSeverity",
    "ReasonCodeVocabulary",
    "RecipeAlternative",
    "RecipeAlternativeCache",
    "RecipeAlternativeFitsFleet",
    "RecipeBuildAdapter",
    "RecipeBuildAdapterDefinition",
    "RecipeBuildAdditionalContext",
    "RecipeBuildBaseImage",
    "RecipeBuildCleanupEvidence",
    "RecipeBuildCleanupParent",
    "RecipeBuildCleanupParentOwnerKind",
    "RecipeBuildCleanupRequest",
    "RecipeBuildCode",
    "RecipeBuildDefinition",
    "RecipeBuildDependency",
    "RecipeBuildEnvironmentArgument",
    "RecipeBuildEvidence",
    "RecipeBuildIntent",
    "RecipeBuildIntentKind",
    "RecipeBuildLimits",
    "RecipeBuildMetadata",
    "RecipeBuildNetwork",
    "RecipeBuildOptions",
    "RecipeBuildOptionsFormat",
    "RecipeBuildOptionsLayerCompression",
    "RecipeBuildOptionsSquash",
    "RecipeBuildParent",
    "RecipeBuildParentOwnerKind",
    "RecipeBuildRequest",
    "RecipeCacheRemovalCheckpoint",
    "RecipeCacheRemovalIntent",
    "RecipeCacheRemovalModelChild",
    "RecipeCacheRemovalOwner",
    "RecipeCacheRemovalPlan",
    "RecipeCacheRemovalResult",
    "RecipeCancellationRequest",
    "RecipeDefinition",
    "RecipeDetailResponse",
    "RecipeDiskResources",
    "RecipeDownloadRequest",
    "RecipeEmbeddingSettings",
    "RecipeEmbeddingSettingsKnobs",
    "RecipeExecution",
    "RecipeGenerationSettings",
    "RecipeGenerationSettingsKnobs",
    "RecipeHttpServingRequest",
    "RecipeHttpServingRequestBodyType0",
    "RecipeHttpServingRequestMethod",
    "RecipeIdentity",
    "RecipeImage",
    "RecipeImageAvailabilityAction",
    "RecipeImageAvailabilityArtifact",
    "RecipeImageAvailabilityChild",
    "RecipeImageAvailabilityChildKind",
    "RecipeImageAvailabilityChildState",
    "RecipeImageAvailabilityResponse",
    "RecipeImageAvailabilityResponseState",
    "RecipeImageAvailabilityResult",
    "RecipeImageCode",
    "RecipeInputSlot",
    "RecipeInstallationChange",
    "RecipeInstallationPayload",
    "RecipeInstallParent",
    "RecipeInstallParentOwnerKind",
    "RecipeInstallPayload",
    "RecipeIntegerSetting",
    "RecipeIntegerSettingChangeEffect",
    "RecipeJobActivateParent",
    "RecipeJobActivateParentOwnerKind",
    "RecipeJobEvidence",
    "RecipeJobFile",
    "RecipeJobInput",
    "RecipeJobInputFile",
    "RecipeJobInputManifest",
    "RecipeJobInterface",
    "RecipeJobInterfaceAdapter",
    "RecipeJobOutput",
    "RecipeJobOutputLimits",
    "RecipeJobOutputManifest",
    "RecipeJobOutputMapping",
    "RecipeJobRunParent",
    "RecipeJobRunParentOwnerKind",
    "RecipeJobRunRequest",
    "RecipeJobRunResult",
    "RecipeJobServingRequest",
    "RecipeJobServingRequestInputSlots",
    "RecipeJobSettings",
    "RecipeJobSettingsKnobs",
    "RecipeLibraryResponse",
    "RecipeLifecycle",
    "RecipeMemoryResources",
    "RecipeMetadata",
    "RecipeMetadataAlignmentType0",
    "RecipeModelFile",
    "RecipeModelSelection",
    "RecipeMount",
    "RecipeOpenAIInterface",
    "RecipeOperationActivatedResult",
    "RecipeOperationCancellationResult",
    "RecipeOperationCancellationResultLaunchEvidenceType0",
    "RecipeOperationCancellationResultNodeEvidenceType0",
    "RecipeOperationCode",
    "RecipeOperationProgressResult",
    "RecipeOperationProgressResultLaunchEvidenceType0",
    "RecipeOperationProgressResultNodeEvidenceType0",
    "RecipeOperationResult",
    "RecipeOperationResultLaunchEvidenceType0",
    "RecipeOperationResultNodeEvidence",
    "RecipeOperationStoppedResult",
    "RecipeOperatorRequest",
    "RecipeOperatorResponse",
    "RecipeOperatorResponseState",
    "RecipeOption",
    "RecipeOptionChoice",
    "RecipeOptionChoiceEnv",
    "RecipeOutputSlot",
    "RecipePackageCode",
    "RecipePackageHandleProjection",
    "RecipeParallelism",
    "RecipePresence",
    "RecipeProvenance",
    "RecipeReadiness",
    "RecipeReadinessCheck",
    "RecipeReadinessCheckState",
    "RecipeReconcileParent",
    "RecipeReconcileParentOwnerKind",
    "RecipeReconcilePayload",
    "RecipeReconcileResult",
    "RecipeRelease",
    "RecipeRemovalProjectionIssue",
    "RecipeRemovalUnavailableView",
    "RecipeRetryIntent",
    "RecipeRevisionIntent",
    "RecipeRevisionProjection",
    "RecipeRoleResources",
    "RecipeRunChange",
    "RecipeRunDispositionValue",
    "RecipeRunPayload",
    "RecipeRuntime",
    "RecipeRuntimeArgument",
    "RecipeRuntimeEnvironment",
    "RecipeSelectorIntent",
    "RecipeServingValidation",
    "RecipeServingValidationInterface",
    "RecipeSetting",
    "RecipeSettingChangeEffect",
    "RecipeStartParent",
    "RecipeStartParentOwnerKind",
    "RecipeStartPayload",
    "RecipeStartPayloadPhaseType0",
    "RecipeStartResult",
    "RecipeStopParent",
    "RecipeStopParentOwnerKind",
    "RecipeStopPayload",
    "RecipeStopResult",
    "RecipeTopology",
    "RecipeTopologyRole",
    "RecipeUninstallParent",
    "RecipeUninstallParentOwnerKind",
    "RecipeUninstallPayload",
    "RecipeUninstallResult",
    "RecipeUpdateChild",
    "RecipeUpdateChildState",
    "RecipeUpdateCode",
    "RecipeUpdateDocument",
    "RecipeUpdateFailure",
    "RecipeUpdateNotice",
    "RecipeUpdateRequest",
    "RecipeUpdateResponse",
    "RecipeUpdateResponseState",
    "RecipeUpdateScope",
    "RecipeValidation",
    "RecipeValidationCheck",
    "RecipeValidationCheckAssertionsItem",
    "RecipeValidationCheckKind",
    "ReconcileCode",
    "ReconcilePhaseOperation",
    "RecoveryStartItem",
    "RemovedRecipeNodeResult",
    "RequestValidationIssue",
    "RequestValidationProblem",
    "ReservationState",
    "Residue",
    "ResourceBlockerCode",
    "ResourceDemandEvidence",
    "ResourceDemandEvidenceEvidenceState",
    "ResourcePlanningCode",
    "ResourceTerm",
    "ResourceTermProblem",
    "RolloutPreparation",
    "RouteClaimMarker",
    "RoutePublicationState",
    "RouteState",
    "RunAdmissionCode",
    "RunDegradedReason",
    "RunMemoryResidualRange",
    "RunMemoryResidualRangeReservationKind",
    "RunNodeChange",
    "RunNodePayload",
    "RunPresence",
    "RunPresenceGroupState",
    "RunPresenceOptionChoices",
    "RunState",
    "RunSwitchApplyRequest",
    "RunSwitchApplyRequestAction",
    "RunSwitchApplyRequestOptionChoices",
    "RunSwitchApplyRequestRetention",
    "RunSwitchAssessment",
    "RunSwitchBuildEvidence",
    "RunSwitchBuildEvidenceState",
    "RunSwitchCachedTransferResult",
    "RunSwitchCachedTransferResultCachedTargetTotals",
    "RunSwitchCancellation",
    "RunSwitchChildProgress",
    "RunSwitchChildProgressPhaseType0",
    "RunSwitchCleanupIntent",
    "RunSwitchCleanupIntentCleanupMode",
    "RunSwitchCleanupResult",
    "RunSwitchCleanupResultSubphaseType0",
    "RunSwitchCleanupVerifyResult",
    "RunSwitchCleanupVerifyResultCleanupMode",
    "RunSwitchCleanupVerifyResultSubphaseType0",
    "RunSwitchCode",
    "RunSwitchContainerBuildResult",
    "RunSwitchContainerBuildResultState",
    "RunSwitchDistributionChildResult",
    "RunSwitchDistributionEndedResult",
    "RunSwitchFinalVerifyResult",
    "RunSwitchFinalVerifyResultSubphaseType0",
    "RunSwitchInstallationVerifyResult",
    "RunSwitchInstallationVerifyResultSubphaseType0",
    "RunSwitchJobPayload",
    "RunSwitchJobPayloadAction",
    "RunSwitchJobPayloadOperationKind",
    "RunSwitchJournalRepairEndEvidence",
    "RunSwitchJournalRepairEvidence",
    "RunSwitchJournalRepairPendingState",
    "RunSwitchMemberProgress",
    "RunSwitchMemberProgressPhaseType0",
    "RunSwitchMemberProgressState",
    "RunSwitchMemberReceipt",
    "RunSwitchMemberReceiptPhaseType0",
    "RunSwitchMemberReceiptState",
    "RunSwitchModelDownloadPendingResult",
    "RunSwitchModelDownloadResult",
    "RunSwitchOperation",
    "RunSwitchOperationAction",
    "RunSwitchOperationCleanupModeType0",
    "RunSwitchOperationCompletedPhasesItem",
    "RunSwitchOperationCurrentPhaseType0",
    "RunSwitchOperationKind",
    "RunSwitchOperationResult",
    "RunSwitchOperationResultCompletedPhasesItem",
    "RunSwitchOperationResultFailedPhaseType0",
    "RunSwitchOperationResultPhaseType0",
    "RunSwitchOperationResultSubphaseType0",
    "RunSwitchOperationState",
    "RunSwitchPhase",
    "RunSwitchPhaseKind",
    "RunSwitchPhaseState",
    "RunSwitchPhaseSubphaseType0",
    "RunSwitchPlan",
    "RunSwitchPlanAction",
    "RunSwitchPlanCleanupDisposition",
    "RunSwitchPlanCleanupMode",
    "RunSwitchPreparedResult",
    "RunSwitchProfileStopIntent",
    "RunSwitchProfileStopScope",
    "RunSwitchProgress",
    "RunSwitchProgressPhaseType0",
    "RunSwitchProgressState",
    "RunSwitchProgressSubphaseType0",
    "RunSwitchRankReceipt",
    "RunSwitchReason",
    "RunSwitchReasonScope",
    "RunSwitchReasonSeverity",
    "RunSwitchReconciliationAuthority",
    "RunSwitchReconciliationTarget",
    "RunSwitchReconciliationTargetState",
    "RunSwitchRunIntent",
    "RunSwitchRuntimeImageReferenceIntent",
    "RunSwitchRuntimeImageResult",
    "RunSwitchRuntimeInstallResult",
    "RunSwitchRuntimePlanResult",
    "RunSwitchStartResult",
    "RunSwitchStartResultSubphaseType0",
    "RunSwitchStopIntent",
    "RunSwitchStopResult",
    "RunSwitchStopResultSubphaseType0",
    "RunSwitchTargetTransferEvidenceResult",
    "RunSwitchTargetTransferResult",
    "RunSwitchTargetTransferResultAssignments",
    "RunSwitchUninstallResult",
    "RunSwitchUninstallResultDisposition",
    "RunSwitchUninstallResultSubphaseType0",
    "RunSwitchVerifyResult",
    "RunSwitchVerifyResultCachedTargetTotals",
    "RuntimeArgument",
    "RuntimeEnvironmentEntry",
    "RuntimeImageCode",
    "RuntimeImageIdentity",
    "RuntimeImagePreparation",
    "RuntimeImageReceipt",
    "RuntimeImageReferenceIntent",
    "RuntimeImageStorageImpact",
    "RuntimeImageStorageImpactMissingImageDistributionBytesByNodeType0",
    "RuntimeImageStorageImpactNasCoverage",
    "RuntimeImageStorageImpactRunningCoverage",
    "RuntimeImageStorageImpactSparkCoverage",
    "RuntimePreflightCode",
    "RuntimePreflightFinding",
    "RuntimePreflightFindingCode",
    "RuntimePreflightFindingStatus",
    "RuntimePreflightRequest",
    "RuntimePreflightRequestFabricConnectivity",
    "RuntimePreflightResult",
    "RuntimeTelemetryProjection",
    "SavedProfileProjectionIssue",
    "SecurityRefusal",
    "SecurityRefusalReason",
    "ServiceRunStopReview",
    "ServiceRunStopReviewExactPayloadsType0",
    "ServiceRunStopReviewStage",
    "SourceBundleCode",
    "SourceBundleFile",
    "SourceBundleFileMode",
    "SourceBundleManifest",
    "SourcePolicyCode",
    "SparkFit",
    "SparkFitNode",
    "SparkFitNodeMemoryKindType0",
    "SparkFitNodeMemoryPoolType0",
    "SparkGroup",
    "SparkGroupNode",
    "StartPhaseOperation",
    "StateAlias",
    "StateWriteKind",
    "StopImpact",
    "StopOutcome",
    "StopPhaseOperation",
    "StopPlanCode",
    "StorageDemandCode",
    "StoredAdmissionReason",
    "StoredBuildPolicyReport",
    "StoredInstallationPlan",
    "StoredInstallationPlanCompiledExecutionPlans",
    "StoredInstallNodePlan",
    "StoredPolicyFinding",
    "StoredPrebuiltDecision",
    "StoredRunEndpoint",
    "StoredRunNodePlan",
    "StoredRunNodePlanMemoryKind",
    "StoredRunNodePlanMemoryPool",
    "StoredRunPlan",
    "StringParameter",
    "SupersedeCode",
    "TargetAssetState",
    "TargetAssetStateState",
    "TelemetryPoint",
    "TelemetryState",
    "TelemetryStateFreshness",
    "TopologyCode",
    "UnavailableFleetProfileView",
    "UnavailableRecipePresence",
    "UnavailableRunPresence",
    "UninstallPhaseOperation",
    "UninstallPlanCode",
    "UnknownError",
    "UnprojectedRevision",
    "WaitReason",
    "WaitVerdict",
    "WorkerRuntimeObservation",
    "WritablePath",
)
