""" Contains all the data models used in inputs/outputs """

from .admission_code import AdmissionCode
from .agent_evidence_code import AgentEvidenceCode
from .agent_failure_kind import AgentFailureKind
from .agent_failure_result import AgentFailureResult
from .agent_install_result import AgentInstallResult
from .agent_operation import AgentOperation
from .agent_operation_change import AgentOperationChange
from .agent_operation_payload import AgentOperationPayload
from .agent_result_state import AgentResultState
from .agent_upgrade_diagnostics_response import AgentUpgradeDiagnosticsResponse
from .agent_upgrade_identity_response import AgentUpgradeIdentityResponse
from .agent_upgrade_target_diagnostics_response import AgentUpgradeTargetDiagnosticsResponse
from .artifact_file_declaration import ArtifactFileDeclaration
from .artifact_input_contract import ArtifactInputContract
from .artifact_job_capabilities_response import ArtifactJobCapabilitiesResponse
from .artifact_job_create import ArtifactJobCreate
from .artifact_job_create_parameters import ArtifactJobCreateParameters
from .artifact_job_list_response import ArtifactJobListResponse
from .artifact_job_response import ArtifactJobResponse
from .artifact_job_response_interface import ArtifactJobResponseInterface
from .artifact_job_response_preparation_type_0 import ArtifactJobResponsePreparationType0
from .artifact_job_response_state_type_0 import ArtifactJobResponseStateType0
from .artifact_job_result_evidence import ArtifactJobResultEvidence
from .artifact_job_storage_capabilities import ArtifactJobStorageCapabilities
from .artifact_job_transport_capabilities import ArtifactJobTransportCapabilities
from .artifact_lifecycle_code import ArtifactLifecycleCode
from .artifact_output_contract import ArtifactOutputContract
from .artifact_output_file import ArtifactOutputFile
from .artifact_output_limits import ArtifactOutputLimits
from .artifact_preparation import ArtifactPreparation
from .artifact_slot_contract import ArtifactSlotContract
from .artifact_storage_impact import ArtifactStorageImpact
from .artifact_storage_impact_missing_spark_bytes_by_node_type_0 import ArtifactStorageImpactMissingSparkBytesByNodeType0
from .artifact_storage_impact_nas_coverage import ArtifactStorageImpactNasCoverage
from .artifact_storage_impact_retention import ArtifactStorageImpactRetention
from .artifact_storage_impact_running_coverage import ArtifactStorageImpactRunningCoverage
from .artifact_storage_impact_spark_coverage import ArtifactStorageImpactSparkCoverage
from .artifact_verification_evidence import ArtifactVerificationEvidence
from .asset_availability import AssetAvailability
from .availability_operation_failure import AvailabilityOperationFailure
from .availability_recovery_action import AvailabilityRecoveryAction
from .blocker_category import BlockerCategory
from .boolean_parameter import BooleanParameter
from .bounded_error_response import BoundedErrorResponse
from .build_compatibility_evidence import BuildCompatibilityEvidence
from .build_compatibility_evidence_state import BuildCompatibilityEvidenceState
from .build_context import BuildContext
from .build_network import BuildNetwork
from .build_patch import BuildPatch
from .build_source_evidence import BuildSourceEvidence
from .build_source_evidence_state import BuildSourceEvidenceState
from .cache_reference_reason import CacheReferenceReason
from .cache_removal_asset import CacheRemovalAsset
from .cache_removal_asset_disposition import CacheRemovalAssetDisposition
from .cache_removal_asset_kind import CacheRemovalAssetKind
from .cache_removal_blocker import CacheRemovalBlocker
from .cache_removal_finding import CacheRemovalFinding
from .cache_removal_finding_asset_kind import CacheRemovalFindingAssetKind
from .cache_removal_finding_classification import CacheRemovalFindingClassification
from .cache_removal_review import CacheRemovalReview
from .cache_removal_review_resource_kind import CacheRemovalReviewResourceKind
from .cancel_request import CancelRequest
from .capacity_reservations import CapacityReservations
from .catalog_code import CatalogCode
from .catalog_problem import CatalogProblem
from .catalog_sync_code import CatalogSyncCode
from .catalog_sync_state import CatalogSyncState
from .certificate_state import CertificateState
from .cluster_mapping_code import ClusterMappingCode
from .compatibility_identity import CompatibilityIdentity
from .compatibility_preparation import CompatibilityPreparation
from .compatibility_preparation_kind import CompatibilityPreparationKind
from .compatibility_preparation_stage import CompatibilityPreparationStage
from .compatibility_preparation_state import CompatibilityPreparationState
from .compiled_artifact_contract import CompiledArtifactContract
from .compiled_artifact_contract_engine_type_0 import CompiledArtifactContractEngineType0
from .compiled_artifact_contract_interface import CompiledArtifactContractInterface
from .conditional_post_stop_memory_check import ConditionalPostStopMemoryCheck
from .controller_asset_state import ControllerAssetState
from .controller_asset_state_source import ControllerAssetStateSource
from .controller_asset_state_state import ControllerAssetStateState
from .controller_error_code import ControllerErrorCode
from .desired_assignment_state import DesiredAssignmentState
from .distribution_assignment_state import DistributionAssignmentState
from .distribution_code import DistributionCode
from .distribution_object import DistributionObject
from .effective_parallelism import EffectiveParallelism
from .effective_settings_selection import EffectiveSettingsSelection
from .effective_settings_selection_change_effects import EffectiveSettingsSelectionChangeEffects
from .effective_settings_selection_change_effects_additional_property import EffectiveSettingsSelectionChangeEffectsAdditionalProperty
from .effective_settings_selection_kind import EffectiveSettingsSelectionKind
from .effective_settings_selection_knobs import EffectiveSettingsSelectionKnobs
from .endpoint_response import EndpointResponse
from .endpoint_state import EndpointState
from .enrollment_grant_response import EnrollmentGrantResponse
from .enrollment_grant_response_installer_url import EnrollmentGrantResponseInstallerUrl
from .enrollment_grant_response_purpose import EnrollmentGrantResponsePurpose
from .enrollment_grant_state import EnrollmentGrantState
from .enrollment_grant_status import EnrollmentGrantStatus
from .enrollment_grant_status_purpose import EnrollmentGrantStatusPurpose
from .enum_parameter import EnumParameter
from .error_catalog import ErrorCatalog
from .error_category import ErrorCategory
from .error_context_response import ErrorContextResponse
from .error_context_response_decision import ErrorContextResponseDecision
from .error_context_response_source import ErrorContextResponseSource
from .evidence_context import EvidenceContext
from .evidence_context_source import EvidenceContextSource
from .failure_code import FailureCode
from .failure_diagnostics import FailureDiagnostics
from .failure_diagnostics_category import FailureDiagnosticsCategory
from .failure_evidence_bundle import FailureEvidenceBundle
from .failure_log_tail import FailureLogTail
from .failure_property import FailureProperty
from .fleet_action_response import FleetActionResponse
from .fleet_action_response_action import FleetActionResponseAction
from .fleet_change_event import FleetChangeEvent
from .fleet_enroll_request import FleetEnrollRequest
from .fleet_lock_holder import FleetLockHolder
from .fleet_locks_response import FleetLocksResponse
from .fleet_log_entry import FleetLogEntry
from .fleet_log_entry_level import FleetLogEntryLevel
from .fleet_log_entry_source import FleetLogEntrySource
from .fleet_log_response import FleetLogResponse
from .fleet_node import FleetNode
from .fleet_node_identity import FleetNodeIdentity
from .fleet_node_labels import FleetNodeLabels
from .fleet_open_transaction import FleetOpenTransaction
from .fleet_profile_admission_decision import FleetProfileAdmissionDecision
from .fleet_profile_application_cancel_request import FleetProfileApplicationCancelRequest
from .fleet_profile_application_cancellation_intent import FleetProfileApplicationCancellationIntent
from .fleet_profile_application_cancellation_intent_cause import FleetProfileApplicationCancellationIntentCause
from .fleet_profile_application_cancellation_intent_state import FleetProfileApplicationCancellationIntentState
from .fleet_profile_application_cancellation_view import FleetProfileApplicationCancellationView
from .fleet_profile_application_cancellation_view_cause import FleetProfileApplicationCancellationViewCause
from .fleet_profile_application_cancellation_view_state import FleetProfileApplicationCancellationViewState
from .fleet_profile_application_effect import FleetProfileApplicationEffect
from .fleet_profile_application_effect_kind import FleetProfileApplicationEffectKind
from .fleet_profile_application_effect_outcome import FleetProfileApplicationEffectOutcome
from .fleet_profile_application_progress import FleetProfileApplicationProgress
from .fleet_profile_application_progress_step_results import FleetProfileApplicationProgressStepResults
from .fleet_profile_application_result import FleetProfileApplicationResult
from .fleet_profile_application_view import FleetProfileApplicationView
from .fleet_profile_application_view_state import FleetProfileApplicationViewState
from .fleet_profile_assignment import FleetProfileAssignment
from .fleet_profile_assignment_assessment import FleetProfileAssignmentAssessment
from .fleet_profile_assignment_failure import FleetProfileAssignmentFailure
from .fleet_profile_assignment_input import FleetProfileAssignmentInput
from .fleet_profile_assignment_input_option_choices import FleetProfileAssignmentInputOptionChoices
from .fleet_profile_assignment_option_choices import FleetProfileAssignmentOptionChoices
from .fleet_profile_assignment_preparation import FleetProfileAssignmentPreparation
from .fleet_profile_assignment_preview import FleetProfileAssignmentPreview
from .fleet_profile_assignment_preview_actions_item import FleetProfileAssignmentPreviewActionsItem
from .fleet_profile_assignment_preview_option_choices import FleetProfileAssignmentPreviewOptionChoices
from .fleet_profile_assignment_view import FleetProfileAssignmentView
from .fleet_profile_assignment_view_model import FleetProfileAssignmentViewModel
from .fleet_profile_assignment_view_option_choices import FleetProfileAssignmentViewOptionChoices
from .fleet_profile_assignment_view_recipe import FleetProfileAssignmentViewRecipe
from .fleet_profile_assignment_view_resources import FleetProfileAssignmentViewResources
from .fleet_profile_child_progress import FleetProfileChildProgress
from .fleet_profile_child_progress_phase import FleetProfileChildProgressPhase
from .fleet_profile_compatibility_decision import FleetProfileCompatibilityDecision
from .fleet_profile_compatibility_decision_kind import FleetProfileCompatibilityDecisionKind
from .fleet_profile_compatibility_decision_stage import FleetProfileCompatibilityDecisionStage
from .fleet_profile_definition import FleetProfileDefinition
from .fleet_profile_definition_installation_policy import FleetProfileDefinitionInstallationPolicy
from .fleet_profile_definition_labels import FleetProfileDefinitionLabels
from .fleet_profile_definition_view import FleetProfileDefinitionView
from .fleet_profile_effects import FleetProfileEffects
from .fleet_profile_endpoint_assignment_view import FleetProfileEndpointAssignmentView
from .fleet_profile_endpoint_projection_issue import FleetProfileEndpointProjectionIssue
from .fleet_profile_endpoints_view import FleetProfileEndpointsView
from .fleet_profile_endpoints_view_application_state_type_0 import FleetProfileEndpointsViewApplicationStateType0
from .fleet_profile_input import FleetProfileInput
from .fleet_profile_input_installation_policy import FleetProfileInputInstallationPolicy
from .fleet_profile_input_labels import FleetProfileInputLabels
from .fleet_profile_installation_effect import FleetProfileInstallationEffect
from .fleet_profile_installation_effect_action import FleetProfileInstallationEffectAction
from .fleet_profile_intended_configuration import FleetProfileIntendedConfiguration
from .fleet_profile_intended_configuration_installation_policy import FleetProfileIntendedConfigurationInstallationPolicy
from .fleet_profile_list import FleetProfileList
from .fleet_profile_load_request import FleetProfileLoadRequest
from .fleet_profile_node import FleetProfileNode
from .fleet_profile_pending_effect import FleetProfilePendingEffect
from .fleet_profile_pending_effect_kind import FleetProfilePendingEffectKind
from .fleet_profile_plan_step import FleetProfilePlanStep
from .fleet_profile_plan_step_kind import FleetProfilePlanStepKind
from .fleet_profile_plan_summary import FleetProfilePlanSummary
from .fleet_profile_preparation_decision import FleetProfilePreparationDecision
from .fleet_profile_preview import FleetProfilePreview
from .fleet_profile_reason import FleetProfileReason
from .fleet_profile_reason_severity import FleetProfileReasonSeverity
from .fleet_profile_resource_requirement import FleetProfileResourceRequirement
from .fleet_profile_resource_requirement_memory_kind_type_0 import FleetProfileResourceRequirementMemoryKindType0
from .fleet_profile_resource_requirement_memory_pool_type_0 import FleetProfileResourceRequirementMemoryPoolType0
from .fleet_profile_run_effect import FleetProfileRunEffect
from .fleet_profile_run_effect_action import FleetProfileRunEffectAction
from .fleet_profile_scope import FleetProfileScope
from .fleet_profile_scope_preview import FleetProfileScopePreview
from .fleet_profile_step_result import FleetProfileStepResult
from .fleet_profile_switch_adapter_result import FleetProfileSwitchAdapterResult
from .fleet_profile_switch_adapter_state import FleetProfileSwitchAdapterState
from .fleet_profile_switch_adapter_state_active_kind_type_0 import FleetProfileSwitchAdapterStateActiveKindType0
from .fleet_profile_switch_adapter_state_state import FleetProfileSwitchAdapterStateState
from .fleet_profile_switch_child_result import FleetProfileSwitchChildResult
from .fleet_profile_switch_child_state import FleetProfileSwitchChildState
from .fleet_profile_switch_child_state_kind import FleetProfileSwitchChildStateKind
from .fleet_profile_switch_child_state_state import FleetProfileSwitchChildStateState
from .fleet_profile_switch_queue_item import FleetProfileSwitchQueueItem
from .fleet_profile_switch_queue_item_kind import FleetProfileSwitchQueueItemKind
from .fleet_profile_verification_result import FleetProfileVerificationResult
from .fleet_profile_view import FleetProfileView
from .fleet_profile_view_cache_summary import FleetProfileViewCacheSummary
from .fleet_profile_view_fleet_item import FleetProfileViewFleetItem
from .fleet_profile_view_installation_policy import FleetProfileViewInstallationPolicy
from .fleet_profile_view_labels import FleetProfileViewLabels
from .fleet_reenroll_request import FleetReenrollRequest
from .fleet_rename_request import FleetRenameRequest
from .fleet_snapshot import FleetSnapshot
from .fleet_snapshot_event import FleetSnapshotEvent
from .fleet_telemetry_event import FleetTelemetryEvent
from .fleet_upgrade_request import FleetUpgradeRequest
from .float_parameter import FloatParameter
from .freshness_evidence import FreshnessEvidence
from .freshness_evidence_state import FreshnessEvidenceState
from .freshness_policy import FreshnessPolicy
from .gateway_key_create_request import GatewayKeyCreateRequest
from .gateway_key_created import GatewayKeyCreated
from .gateway_key_list import GatewayKeyList
from .gateway_key_revoked import GatewayKeyRevoked
from .gateway_key_view import GatewayKeyView
from .gateway_route_state import GatewayRouteState
from .get_fleet_log_info_source_type_0 import GetFleetLogInfoSourceType0
from .git_hub_release_asset import GitHubReleaseAsset
from .git_hub_release_source import GitHubReleaseSource
from .helper_error_code import HelperErrorCode
from .image_store_code import ImageStoreCode
from .install_admission_code import InstallAdmissionCode
from .install_degraded_reason import InstallDegradedReason
from .install_partial_evidence import InstallPartialEvidence
from .installation_node_change import InstallationNodeChange
from .installation_node_payload import InstallationNodePayload
from .installation_node_state import InstallationNodeState
from .installation_reconcile_request import InstallationReconcileRequest
from .installation_state import InstallationState
from .integer_parameter import IntegerParameter
from .invalid_request import InvalidRequest
from .invalid_request_reason import InvalidRequestReason
from .inventory_state import InventoryState
from .inventory_state_freshness import InventoryStateFreshness
from .invocation_metadata import InvocationMetadata
from .invocation_metadata_context import InvocationMetadataContext
from .job_change import JobChange
from .job_detail_response import JobDetailResponse
from .job_operation_response import JobOperationResponse
from .job_payload import JobPayload
from .job_progress import JobProgress
from .job_resume_request import JobResumeRequest
from .job_resume_request_disposition import JobResumeRequestDisposition
from .job_resume_response import JobResumeResponse
from .library_assessment_code import LibraryAssessmentCode
from .library_facet_values import LibraryFacetValues
from .library_filter_values import LibraryFilterValues
from .library_filter_values_sort_type_0 import LibraryFilterValuesSortType0
from .library_local_progress import LibraryLocalProgress
from .library_local_progress_state import LibraryLocalProgressState
from .library_local_state import LibraryLocalState
from .library_local_state_controller import LibraryLocalStateController
from .library_model_identity import LibraryModelIdentity
from .library_model_projection import LibraryModelProjection
from .library_projection_code import LibraryProjectionCode
from .library_recipe_identity import LibraryRecipeIdentity
from .library_recipe_model import LibraryRecipeModel
from .library_recipe_projection import LibraryRecipeProjection
from .library_release import LibraryRelease
from .library_resource_projection import LibraryResourceProjection
from .lifecycle_code_failure_result import LifecycleCodeFailureResult
from .lifecycle_effect import LifecycleEffect
from .lifecycle_event_kind import LifecycleEventKind
from .lifecycle_preflight_checkpoint import LifecyclePreflightCheckpoint
from .lifecycle_preflight_checkpoint_attempts import LifecyclePreflightCheckpointAttempts
from .lifecycle_preflight_checkpoint_receipts import LifecyclePreflightCheckpointReceipts
from .lifecycle_state import LifecycleState
from .lifecycle_subject import LifecycleSubject
from .lifecycle_vocabulary import LifecycleVocabulary
from .list_model_library_sort import ListModelLibrarySort
from .list_recipe_library_sort import ListRecipeLibrarySort
from .managed_catalog_stale_recipe import ManagedCatalogStaleRecipe
from .managed_catalog_sync_failure import ManagedCatalogSyncFailure
from .managed_catalog_sync_problem import ManagedCatalogSyncProblem
from .managed_catalog_sync_response import ManagedCatalogSyncResponse
from .managed_catalog_sync_response_trigger import ManagedCatalogSyncResponseTrigger
from .managed_catalog_withdrawn_recipe import ManagedCatalogWithdrawnRecipe
from .mapping_selection import MappingSelection
from .mapping_selection_action import MappingSelectionAction
from .mapping_selection_option_choices import MappingSelectionOptionChoices
from .mapping_selection_parameters import MappingSelectionParameters
from .memory_usage_uncertainty import MemoryUsageUncertainty
from .migration_step import MigrationStep
from .model_artifact_identity import ModelArtifactIdentity
from .model_artifact_preparation import ModelArtifactPreparation
from .model_artifact_preparation_completeness import ModelArtifactPreparationCompleteness
from .model_cache_blocker_code import ModelCacheBlockerCode
from .model_cache_cancellation import ModelCacheCancellation
from .model_cache_cancellation_request import ModelCacheCancellationRequest
from .model_cache_code import ModelCacheCode
from .model_cache_download_result import ModelCacheDownloadResult
from .model_cache_operator_request import ModelCacheOperatorRequest
from .model_cache_operator_response import ModelCacheOperatorResponse
from .model_cache_operator_response_action import ModelCacheOperatorResponseAction
from .model_cache_operator_response_state_type_1 import ModelCacheOperatorResponseStateType1
from .model_cache_operator_status import ModelCacheOperatorStatus
from .model_cache_removal_request import ModelCacheRemovalRequest
from .model_cache_removal_result import ModelCacheRemovalResult
from .model_definition import ModelDefinition
from .model_definition_modalities_item import ModelDefinitionModalitiesItem
from .model_detail_response import ModelDetailResponse
from .model_family import ModelFamily
from .model_file import ModelFile
from .model_file_part import ModelFilePart
from .model_file_state import ModelFileState
from .model_format import ModelFormat
from .model_identity import ModelIdentity
from .model_library_response import ModelLibraryResponse
from .model_license import ModelLicense
from .model_metadata import ModelMetadata
from .model_record import ModelRecord
from .model_reference import ModelReference
from .model_source import ModelSource
from .model_territorial_restrictions import ModelTerritorialRestrictions
from .network_interface import NetworkInterface
from .network_interface_kind import NetworkInterfaceKind
from .node_connection import NodeConnection
from .node_connection_agent_state import NodeConnectionAgentState
from .node_connection_online_state import NodeConnectionOnlineState
from .node_distribution_assignment import NodeDistributionAssignment
from .node_offline_reason import NodeOfflineReason
from .node_profile_change import NodeProfileChange
from .node_profile_payload import NodeProfilePayload
from .observation_cause import ObservationCause
from .observed_assignment_state import ObservedAssignmentState
from .operation_blocker import OperationBlocker
from .operation_blocker_severity import OperationBlockerSeverity
from .operation_checkpoint import OperationCheckpoint
from .operation_detail_response import OperationDetailResponse
from .operation_evidence_download import OperationEvidenceDownload
from .operation_failure_code import OperationFailureCode
from .operation_failure_evidence import OperationFailureEvidence
from .operation_member_progress import OperationMemberProgress
from .operation_member_progress_activity_type_0 import OperationMemberProgressActivityType0
from .operation_owner_reference import OperationOwnerReference
from .operation_progress import OperationProgress
from .operation_progress_activity_type_0 import OperationProgressActivityType0
from .operation_recovery import OperationRecovery
from .operation_recovery_action import OperationRecoveryAction
from .operations_response import OperationsResponse
from .operator_action_name import OperatorActionName
from .operator_surface import OperatorSurface
from .outcome_kind import OutcomeKind
from .output_limits import OutputLimits
from .package_activation_receipt import PackageActivationReceipt
from .package_activation_receipt_phase import PackageActivationReceiptPhase
from .placement_install_state import PlacementInstallState
from .placement_load_state import PlacementLoadState
from .prebuilt_image_code import PrebuiltImageCode
from .preparation_reason import PreparationReason
from .preparation_reason_severity import PreparationReasonSeverity
from .profile_reason_code import ProfileReasonCode
from .projection_code import ProjectionCode
from .projection_reason import ProjectionReason
from .projection_reason_severity import ProjectionReasonSeverity
from .reason_code_vocabulary import ReasonCodeVocabulary
from .recipe_alternative import RecipeAlternative
from .recipe_alternative_cache import RecipeAlternativeCache
from .recipe_alternative_fits_fleet import RecipeAlternativeFitsFleet
from .recipe_build_cleanup_evidence import RecipeBuildCleanupEvidence
from .recipe_build_code import RecipeBuildCode
from .recipe_build_definition import RecipeBuildDefinition
from .recipe_build_evidence import RecipeBuildEvidence
from .recipe_cancellation_request import RecipeCancellationRequest
from .recipe_definition import RecipeDefinition
from .recipe_detail_response import RecipeDetailResponse
from .recipe_disk_resources import RecipeDiskResources
from .recipe_download_request import RecipeDownloadRequest
from .recipe_embedding_settings import RecipeEmbeddingSettings
from .recipe_embedding_settings_knobs import RecipeEmbeddingSettingsKnobs
from .recipe_execution import RecipeExecution
from .recipe_generation_settings import RecipeGenerationSettings
from .recipe_generation_settings_knobs import RecipeGenerationSettingsKnobs
from .recipe_http_serving_request import RecipeHttpServingRequest
from .recipe_http_serving_request_body_type_0 import RecipeHttpServingRequestBodyType0
from .recipe_http_serving_request_method import RecipeHttpServingRequestMethod
from .recipe_identity import RecipeIdentity
from .recipe_image import RecipeImage
from .recipe_image_availability_action import RecipeImageAvailabilityAction
from .recipe_image_availability_artifact import RecipeImageAvailabilityArtifact
from .recipe_image_availability_child import RecipeImageAvailabilityChild
from .recipe_image_availability_child_kind import RecipeImageAvailabilityChildKind
from .recipe_image_availability_child_state import RecipeImageAvailabilityChildState
from .recipe_image_availability_response import RecipeImageAvailabilityResponse
from .recipe_image_availability_response_state import RecipeImageAvailabilityResponseState
from .recipe_image_availability_result import RecipeImageAvailabilityResult
from .recipe_image_code import RecipeImageCode
from .recipe_input_slot import RecipeInputSlot
from .recipe_installation_change import RecipeInstallationChange
from .recipe_installation_payload import RecipeInstallationPayload
from .recipe_integer_setting import RecipeIntegerSetting
from .recipe_integer_setting_change_effect import RecipeIntegerSettingChangeEffect
from .recipe_job_input import RecipeJobInput
from .recipe_job_interface import RecipeJobInterface
from .recipe_job_interface_adapter import RecipeJobInterfaceAdapter
from .recipe_job_output import RecipeJobOutput
from .recipe_job_serving_request import RecipeJobServingRequest
from .recipe_job_serving_request_input_slots import RecipeJobServingRequestInputSlots
from .recipe_job_settings import RecipeJobSettings
from .recipe_job_settings_knobs import RecipeJobSettingsKnobs
from .recipe_library_response import RecipeLibraryResponse
from .recipe_lifecycle import RecipeLifecycle
from .recipe_memory_resources import RecipeMemoryResources
from .recipe_metadata import RecipeMetadata
from .recipe_metadata_alignment_type_0 import RecipeMetadataAlignmentType0
from .recipe_model_file import RecipeModelFile
from .recipe_model_selection import RecipeModelSelection
from .recipe_mount import RecipeMount
from .recipe_open_ai_interface import RecipeOpenAIInterface
from .recipe_operation_cancellation_result import RecipeOperationCancellationResult
from .recipe_operation_cancellation_result_launch_evidence_type_0 import RecipeOperationCancellationResultLaunchEvidenceType0
from .recipe_operation_cancellation_result_node_evidence_type_0 import RecipeOperationCancellationResultNodeEvidenceType0
from .recipe_operation_code import RecipeOperationCode
from .recipe_operator_request import RecipeOperatorRequest
from .recipe_operator_response import RecipeOperatorResponse
from .recipe_operator_response_state import RecipeOperatorResponseState
from .recipe_option import RecipeOption
from .recipe_option_choice import RecipeOptionChoice
from .recipe_option_choice_env import RecipeOptionChoiceEnv
from .recipe_output_slot import RecipeOutputSlot
from .recipe_package_code import RecipePackageCode
from .recipe_parallelism import RecipeParallelism
from .recipe_presence import RecipePresence
from .recipe_provenance import RecipeProvenance
from .recipe_readiness import RecipeReadiness
from .recipe_readiness_check import RecipeReadinessCheck
from .recipe_readiness_check_state import RecipeReadinessCheckState
from .recipe_reconcile_result import RecipeReconcileResult
from .recipe_release import RecipeRelease
from .recipe_retry_intent import RecipeRetryIntent
from .recipe_revision_intent import RecipeRevisionIntent
from .recipe_role_resources import RecipeRoleResources
from .recipe_run_change import RecipeRunChange
from .recipe_run_payload import RecipeRunPayload
from .recipe_runtime import RecipeRuntime
from .recipe_runtime_argument import RecipeRuntimeArgument
from .recipe_runtime_environment import RecipeRuntimeEnvironment
from .recipe_selector_intent import RecipeSelectorIntent
from .recipe_serving_validation import RecipeServingValidation
from .recipe_serving_validation_interface import RecipeServingValidationInterface
from .recipe_setting import RecipeSetting
from .recipe_setting_change_effect import RecipeSettingChangeEffect
from .recipe_start_result import RecipeStartResult
from .recipe_stop_result import RecipeStopResult
from .recipe_topology import RecipeTopology
from .recipe_topology_role import RecipeTopologyRole
from .recipe_uninstall_result import RecipeUninstallResult
from .recipe_update_child import RecipeUpdateChild
from .recipe_update_child_state import RecipeUpdateChildState
from .recipe_update_code import RecipeUpdateCode
from .recipe_update_failure import RecipeUpdateFailure
from .recipe_update_notice import RecipeUpdateNotice
from .recipe_update_request import RecipeUpdateRequest
from .recipe_update_response import RecipeUpdateResponse
from .recipe_update_response_state import RecipeUpdateResponseState
from .recipe_update_scope import RecipeUpdateScope
from .recipe_validation import RecipeValidation
from .recipe_validation_check import RecipeValidationCheck
from .recipe_validation_check_assertions_item import RecipeValidationCheckAssertionsItem
from .recipe_validation_check_kind import RecipeValidationCheckKind
from .reconcile_code import ReconcileCode
from .removed_recipe_node_result import RemovedRecipeNodeResult
from .request_validation_issue import RequestValidationIssue
from .request_validation_problem import RequestValidationProblem
from .reservation_state import ReservationState
from .resource_blocker_code import ResourceBlockerCode
from .resource_demand_evidence import ResourceDemandEvidence
from .resource_demand_evidence_evidence_state import ResourceDemandEvidenceEvidenceState
from .resource_planning_code import ResourcePlanningCode
from .resource_term import ResourceTerm
from .resource_term_problem import ResourceTermProblem
from .rollout_preparation import RolloutPreparation
from .route_publication_state import RoutePublicationState
from .route_state import RouteState
from .run_admission_code import RunAdmissionCode
from .run_degraded_reason import RunDegradedReason
from .run_memory_residual_range import RunMemoryResidualRange
from .run_memory_residual_range_reservation_kind import RunMemoryResidualRangeReservationKind
from .run_node_change import RunNodeChange
from .run_node_payload import RunNodePayload
from .run_presence import RunPresence
from .run_presence_group_state import RunPresenceGroupState
from .run_presence_option_choices import RunPresenceOptionChoices
from .run_state import RunState
from .run_switch_assessment import RunSwitchAssessment
from .run_switch_build_evidence import RunSwitchBuildEvidence
from .run_switch_build_evidence_state import RunSwitchBuildEvidenceState
from .run_switch_cached_transfer_result import RunSwitchCachedTransferResult
from .run_switch_cached_transfer_result_cached_target_totals import RunSwitchCachedTransferResultCachedTargetTotals
from .run_switch_cancellation import RunSwitchCancellation
from .run_switch_child_progress import RunSwitchChildProgress
from .run_switch_child_progress_phase_type_0 import RunSwitchChildProgressPhaseType0
from .run_switch_cleanup_result import RunSwitchCleanupResult
from .run_switch_cleanup_result_subphase_type_0 import RunSwitchCleanupResultSubphaseType0
from .run_switch_cleanup_verify_result import RunSwitchCleanupVerifyResult
from .run_switch_cleanup_verify_result_cleanup_mode import RunSwitchCleanupVerifyResultCleanupMode
from .run_switch_cleanup_verify_result_subphase_type_0 import RunSwitchCleanupVerifyResultSubphaseType0
from .run_switch_code import RunSwitchCode
from .run_switch_container_build_result import RunSwitchContainerBuildResult
from .run_switch_container_build_result_state import RunSwitchContainerBuildResultState
from .run_switch_final_verify_result import RunSwitchFinalVerifyResult
from .run_switch_final_verify_result_subphase_type_0 import RunSwitchFinalVerifyResultSubphaseType0
from .run_switch_installation_verify_result import RunSwitchInstallationVerifyResult
from .run_switch_installation_verify_result_subphase_type_0 import RunSwitchInstallationVerifyResultSubphaseType0
from .run_switch_member_progress import RunSwitchMemberProgress
from .run_switch_member_progress_phase_type_0 import RunSwitchMemberProgressPhaseType0
from .run_switch_member_progress_state import RunSwitchMemberProgressState
from .run_switch_member_receipt import RunSwitchMemberReceipt
from .run_switch_member_receipt_phase_type_0 import RunSwitchMemberReceiptPhaseType0
from .run_switch_member_receipt_state import RunSwitchMemberReceiptState
from .run_switch_model_download_pending_result import RunSwitchModelDownloadPendingResult
from .run_switch_model_download_result import RunSwitchModelDownloadResult
from .run_switch_operation import RunSwitchOperation
from .run_switch_operation_action import RunSwitchOperationAction
from .run_switch_operation_cleanup_mode_type_0 import RunSwitchOperationCleanupModeType0
from .run_switch_operation_completed_phases_item import RunSwitchOperationCompletedPhasesItem
from .run_switch_operation_current_phase_type_0 import RunSwitchOperationCurrentPhaseType0
from .run_switch_operation_kind import RunSwitchOperationKind
from .run_switch_operation_result import RunSwitchOperationResult
from .run_switch_operation_result_completed_phases_item import RunSwitchOperationResultCompletedPhasesItem
from .run_switch_operation_result_failed_phase_type_0 import RunSwitchOperationResultFailedPhaseType0
from .run_switch_operation_result_phase_type_0 import RunSwitchOperationResultPhaseType0
from .run_switch_operation_result_subphase_type_0 import RunSwitchOperationResultSubphaseType0
from .run_switch_operation_state import RunSwitchOperationState
from .run_switch_phase import RunSwitchPhase
from .run_switch_phase_kind import RunSwitchPhaseKind
from .run_switch_phase_state import RunSwitchPhaseState
from .run_switch_phase_subphase_type_0 import RunSwitchPhaseSubphaseType0
from .run_switch_plan import RunSwitchPlan
from .run_switch_plan_action import RunSwitchPlanAction
from .run_switch_plan_cleanup_disposition import RunSwitchPlanCleanupDisposition
from .run_switch_plan_cleanup_mode import RunSwitchPlanCleanupMode
from .run_switch_prepared_result import RunSwitchPreparedResult
from .run_switch_profile_stop_scope import RunSwitchProfileStopScope
from .run_switch_progress import RunSwitchProgress
from .run_switch_progress_phase_type_0 import RunSwitchProgressPhaseType0
from .run_switch_progress_state import RunSwitchProgressState
from .run_switch_progress_subphase_type_0 import RunSwitchProgressSubphaseType0
from .run_switch_rank_receipt import RunSwitchRankReceipt
from .run_switch_reason import RunSwitchReason
from .run_switch_reason_scope import RunSwitchReasonScope
from .run_switch_reason_severity import RunSwitchReasonSeverity
from .run_switch_reconciliation_authority import RunSwitchReconciliationAuthority
from .run_switch_reconciliation_target import RunSwitchReconciliationTarget
from .run_switch_reconciliation_target_state import RunSwitchReconciliationTargetState
from .run_switch_runtime_image_reference_intent import RunSwitchRuntimeImageReferenceIntent
from .run_switch_runtime_image_result import RunSwitchRuntimeImageResult
from .run_switch_runtime_install_result import RunSwitchRuntimeInstallResult
from .run_switch_runtime_plan_result import RunSwitchRuntimePlanResult
from .run_switch_start_result import RunSwitchStartResult
from .run_switch_start_result_subphase_type_0 import RunSwitchStartResultSubphaseType0
from .run_switch_stop_result import RunSwitchStopResult
from .run_switch_stop_result_subphase_type_0 import RunSwitchStopResultSubphaseType0
from .run_switch_target_transfer_evidence_result import RunSwitchTargetTransferEvidenceResult
from .run_switch_target_transfer_result import RunSwitchTargetTransferResult
from .run_switch_target_transfer_result_assignments import RunSwitchTargetTransferResultAssignments
from .run_switch_uninstall_result import RunSwitchUninstallResult
from .run_switch_uninstall_result_disposition import RunSwitchUninstallResultDisposition
from .run_switch_uninstall_result_subphase_type_0 import RunSwitchUninstallResultSubphaseType0
from .run_switch_verify_result import RunSwitchVerifyResult
from .run_switch_verify_result_cached_target_totals import RunSwitchVerifyResultCachedTargetTotals
from .runtime_image_code import RuntimeImageCode
from .runtime_image_identity import RuntimeImageIdentity
from .runtime_image_preparation import RuntimeImagePreparation
from .runtime_image_receipt import RuntimeImageReceipt
from .runtime_image_storage_impact import RuntimeImageStorageImpact
from .runtime_image_storage_impact_missing_image_distribution_bytes_by_node_type_0 import RuntimeImageStorageImpactMissingImageDistributionBytesByNodeType0
from .runtime_image_storage_impact_nas_coverage import RuntimeImageStorageImpactNasCoverage
from .runtime_image_storage_impact_running_coverage import RuntimeImageStorageImpactRunningCoverage
from .runtime_image_storage_impact_spark_coverage import RuntimeImageStorageImpactSparkCoverage
from .runtime_preflight_code import RuntimePreflightCode
from .runtime_preflight_finding import RuntimePreflightFinding
from .runtime_preflight_finding_code import RuntimePreflightFindingCode
from .runtime_preflight_finding_status import RuntimePreflightFindingStatus
from .runtime_preflight_result import RuntimePreflightResult
from .security_refusal import SecurityRefusal
from .security_refusal_reason import SecurityRefusalReason
from .source_bundle_code import SourceBundleCode
from .source_policy_code import SourcePolicyCode
from .spark_fit import SparkFit
from .spark_fit_node import SparkFitNode
from .spark_fit_node_memory_kind_type_0 import SparkFitNodeMemoryKindType0
from .spark_fit_node_memory_pool_type_0 import SparkFitNodeMemoryPoolType0
from .spark_group import SparkGroup
from .spark_group_node import SparkGroupNode
from .state_alias import StateAlias
from .state_write_kind import StateWriteKind
from .stop_impact import StopImpact
from .stop_outcome import StopOutcome
from .stop_plan_code import StopPlanCode
from .storage_demand_code import StorageDemandCode
from .string_parameter import StringParameter
from .supersede_code import SupersedeCode
from .target_asset_state import TargetAssetState
from .target_asset_state_state import TargetAssetStateState
from .telemetry_point import TelemetryPoint
from .telemetry_state import TelemetryState
from .telemetry_state_freshness import TelemetryStateFreshness
from .topology_code import TopologyCode
from .uninstall_plan_code import UninstallPlanCode
from .unknown_error import UnknownError
from .wait_reason import WaitReason
from .wait_verdict import WaitVerdict

__all__ = (
    "AdmissionCode",
    "AgentEvidenceCode",
    "AgentFailureKind",
    "AgentFailureResult",
    "AgentInstallResult",
    "AgentOperation",
    "AgentOperationChange",
    "AgentOperationPayload",
    "AgentResultState",
    "AgentUpgradeDiagnosticsResponse",
    "AgentUpgradeIdentityResponse",
    "AgentUpgradeTargetDiagnosticsResponse",
    "ArtifactFileDeclaration",
    "ArtifactInputContract",
    "ArtifactJobCapabilitiesResponse",
    "ArtifactJobCreate",
    "ArtifactJobCreateParameters",
    "ArtifactJobListResponse",
    "ArtifactJobResponse",
    "ArtifactJobResponseInterface",
    "ArtifactJobResponsePreparationType0",
    "ArtifactJobResponseStateType0",
    "ArtifactJobResultEvidence",
    "ArtifactJobStorageCapabilities",
    "ArtifactJobTransportCapabilities",
    "ArtifactLifecycleCode",
    "ArtifactOutputContract",
    "ArtifactOutputFile",
    "ArtifactOutputLimits",
    "ArtifactPreparation",
    "ArtifactSlotContract",
    "ArtifactStorageImpact",
    "ArtifactStorageImpactMissingSparkBytesByNodeType0",
    "ArtifactStorageImpactNasCoverage",
    "ArtifactStorageImpactRetention",
    "ArtifactStorageImpactRunningCoverage",
    "ArtifactStorageImpactSparkCoverage",
    "ArtifactVerificationEvidence",
    "AssetAvailability",
    "AvailabilityOperationFailure",
    "AvailabilityRecoveryAction",
    "BlockerCategory",
    "BooleanParameter",
    "BoundedErrorResponse",
    "BuildCompatibilityEvidence",
    "BuildCompatibilityEvidenceState",
    "BuildContext",
    "BuildNetwork",
    "BuildPatch",
    "BuildSourceEvidence",
    "BuildSourceEvidenceState",
    "CacheReferenceReason",
    "CacheRemovalAsset",
    "CacheRemovalAssetDisposition",
    "CacheRemovalAssetKind",
    "CacheRemovalBlocker",
    "CacheRemovalFinding",
    "CacheRemovalFindingAssetKind",
    "CacheRemovalFindingClassification",
    "CacheRemovalReview",
    "CacheRemovalReviewResourceKind",
    "CancelRequest",
    "CapacityReservations",
    "CatalogCode",
    "CatalogProblem",
    "CatalogSyncCode",
    "CatalogSyncState",
    "CertificateState",
    "ClusterMappingCode",
    "CompatibilityIdentity",
    "CompatibilityPreparation",
    "CompatibilityPreparationKind",
    "CompatibilityPreparationStage",
    "CompatibilityPreparationState",
    "CompiledArtifactContract",
    "CompiledArtifactContractEngineType0",
    "CompiledArtifactContractInterface",
    "ConditionalPostStopMemoryCheck",
    "ControllerAssetState",
    "ControllerAssetStateSource",
    "ControllerAssetStateState",
    "ControllerErrorCode",
    "DesiredAssignmentState",
    "DistributionAssignmentState",
    "DistributionCode",
    "DistributionObject",
    "EffectiveParallelism",
    "EffectiveSettingsSelection",
    "EffectiveSettingsSelectionChangeEffects",
    "EffectiveSettingsSelectionChangeEffectsAdditionalProperty",
    "EffectiveSettingsSelectionKind",
    "EffectiveSettingsSelectionKnobs",
    "EndpointResponse",
    "EndpointState",
    "EnrollmentGrantResponse",
    "EnrollmentGrantResponseInstallerUrl",
    "EnrollmentGrantResponsePurpose",
    "EnrollmentGrantState",
    "EnrollmentGrantStatus",
    "EnrollmentGrantStatusPurpose",
    "EnumParameter",
    "ErrorCatalog",
    "ErrorCategory",
    "ErrorContextResponse",
    "ErrorContextResponseDecision",
    "ErrorContextResponseSource",
    "EvidenceContext",
    "EvidenceContextSource",
    "FailureCode",
    "FailureDiagnostics",
    "FailureDiagnosticsCategory",
    "FailureEvidenceBundle",
    "FailureLogTail",
    "FailureProperty",
    "FleetActionResponse",
    "FleetActionResponseAction",
    "FleetChangeEvent",
    "FleetEnrollRequest",
    "FleetLockHolder",
    "FleetLocksResponse",
    "FleetLogEntry",
    "FleetLogEntryLevel",
    "FleetLogEntrySource",
    "FleetLogResponse",
    "FleetNode",
    "FleetNodeIdentity",
    "FleetNodeLabels",
    "FleetOpenTransaction",
    "FleetProfileAdmissionDecision",
    "FleetProfileApplicationCancellationIntent",
    "FleetProfileApplicationCancellationIntentCause",
    "FleetProfileApplicationCancellationIntentState",
    "FleetProfileApplicationCancellationView",
    "FleetProfileApplicationCancellationViewCause",
    "FleetProfileApplicationCancellationViewState",
    "FleetProfileApplicationCancelRequest",
    "FleetProfileApplicationEffect",
    "FleetProfileApplicationEffectKind",
    "FleetProfileApplicationEffectOutcome",
    "FleetProfileApplicationProgress",
    "FleetProfileApplicationProgressStepResults",
    "FleetProfileApplicationResult",
    "FleetProfileApplicationView",
    "FleetProfileApplicationViewState",
    "FleetProfileAssignment",
    "FleetProfileAssignmentAssessment",
    "FleetProfileAssignmentFailure",
    "FleetProfileAssignmentInput",
    "FleetProfileAssignmentInputOptionChoices",
    "FleetProfileAssignmentOptionChoices",
    "FleetProfileAssignmentPreparation",
    "FleetProfileAssignmentPreview",
    "FleetProfileAssignmentPreviewActionsItem",
    "FleetProfileAssignmentPreviewOptionChoices",
    "FleetProfileAssignmentView",
    "FleetProfileAssignmentViewModel",
    "FleetProfileAssignmentViewOptionChoices",
    "FleetProfileAssignmentViewRecipe",
    "FleetProfileAssignmentViewResources",
    "FleetProfileChildProgress",
    "FleetProfileChildProgressPhase",
    "FleetProfileCompatibilityDecision",
    "FleetProfileCompatibilityDecisionKind",
    "FleetProfileCompatibilityDecisionStage",
    "FleetProfileDefinition",
    "FleetProfileDefinitionInstallationPolicy",
    "FleetProfileDefinitionLabels",
    "FleetProfileDefinitionView",
    "FleetProfileEffects",
    "FleetProfileEndpointAssignmentView",
    "FleetProfileEndpointProjectionIssue",
    "FleetProfileEndpointsView",
    "FleetProfileEndpointsViewApplicationStateType0",
    "FleetProfileInput",
    "FleetProfileInputInstallationPolicy",
    "FleetProfileInputLabels",
    "FleetProfileInstallationEffect",
    "FleetProfileInstallationEffectAction",
    "FleetProfileIntendedConfiguration",
    "FleetProfileIntendedConfigurationInstallationPolicy",
    "FleetProfileList",
    "FleetProfileLoadRequest",
    "FleetProfileNode",
    "FleetProfilePendingEffect",
    "FleetProfilePendingEffectKind",
    "FleetProfilePlanStep",
    "FleetProfilePlanStepKind",
    "FleetProfilePlanSummary",
    "FleetProfilePreparationDecision",
    "FleetProfilePreview",
    "FleetProfileReason",
    "FleetProfileReasonSeverity",
    "FleetProfileResourceRequirement",
    "FleetProfileResourceRequirementMemoryKindType0",
    "FleetProfileResourceRequirementMemoryPoolType0",
    "FleetProfileRunEffect",
    "FleetProfileRunEffectAction",
    "FleetProfileScope",
    "FleetProfileScopePreview",
    "FleetProfileStepResult",
    "FleetProfileSwitchAdapterResult",
    "FleetProfileSwitchAdapterState",
    "FleetProfileSwitchAdapterStateActiveKindType0",
    "FleetProfileSwitchAdapterStateState",
    "FleetProfileSwitchChildResult",
    "FleetProfileSwitchChildState",
    "FleetProfileSwitchChildStateKind",
    "FleetProfileSwitchChildStateState",
    "FleetProfileSwitchQueueItem",
    "FleetProfileSwitchQueueItemKind",
    "FleetProfileVerificationResult",
    "FleetProfileView",
    "FleetProfileViewCacheSummary",
    "FleetProfileViewFleetItem",
    "FleetProfileViewInstallationPolicy",
    "FleetProfileViewLabels",
    "FleetReenrollRequest",
    "FleetRenameRequest",
    "FleetSnapshot",
    "FleetSnapshotEvent",
    "FleetTelemetryEvent",
    "FleetUpgradeRequest",
    "FloatParameter",
    "FreshnessEvidence",
    "FreshnessEvidenceState",
    "FreshnessPolicy",
    "GatewayKeyCreated",
    "GatewayKeyCreateRequest",
    "GatewayKeyList",
    "GatewayKeyRevoked",
    "GatewayKeyView",
    "GatewayRouteState",
    "GetFleetLogInfoSourceType0",
    "GitHubReleaseAsset",
    "GitHubReleaseSource",
    "HelperErrorCode",
    "ImageStoreCode",
    "InstallAdmissionCode",
    "InstallationNodeChange",
    "InstallationNodePayload",
    "InstallationNodeState",
    "InstallationReconcileRequest",
    "InstallationState",
    "InstallDegradedReason",
    "InstallPartialEvidence",
    "IntegerParameter",
    "InvalidRequest",
    "InvalidRequestReason",
    "InventoryState",
    "InventoryStateFreshness",
    "InvocationMetadata",
    "InvocationMetadataContext",
    "JobChange",
    "JobDetailResponse",
    "JobOperationResponse",
    "JobPayload",
    "JobProgress",
    "JobResumeRequest",
    "JobResumeRequestDisposition",
    "JobResumeResponse",
    "LibraryAssessmentCode",
    "LibraryFacetValues",
    "LibraryFilterValues",
    "LibraryFilterValuesSortType0",
    "LibraryLocalProgress",
    "LibraryLocalProgressState",
    "LibraryLocalState",
    "LibraryLocalStateController",
    "LibraryModelIdentity",
    "LibraryModelProjection",
    "LibraryProjectionCode",
    "LibraryRecipeIdentity",
    "LibraryRecipeModel",
    "LibraryRecipeProjection",
    "LibraryRelease",
    "LibraryResourceProjection",
    "LifecycleCodeFailureResult",
    "LifecycleEffect",
    "LifecycleEventKind",
    "LifecyclePreflightCheckpoint",
    "LifecyclePreflightCheckpointAttempts",
    "LifecyclePreflightCheckpointReceipts",
    "LifecycleState",
    "LifecycleSubject",
    "LifecycleVocabulary",
    "ListModelLibrarySort",
    "ListRecipeLibrarySort",
    "ManagedCatalogStaleRecipe",
    "ManagedCatalogSyncFailure",
    "ManagedCatalogSyncProblem",
    "ManagedCatalogSyncResponse",
    "ManagedCatalogSyncResponseTrigger",
    "ManagedCatalogWithdrawnRecipe",
    "MappingSelection",
    "MappingSelectionAction",
    "MappingSelectionOptionChoices",
    "MappingSelectionParameters",
    "MemoryUsageUncertainty",
    "MigrationStep",
    "ModelArtifactIdentity",
    "ModelArtifactPreparation",
    "ModelArtifactPreparationCompleteness",
    "ModelCacheBlockerCode",
    "ModelCacheCancellation",
    "ModelCacheCancellationRequest",
    "ModelCacheCode",
    "ModelCacheDownloadResult",
    "ModelCacheOperatorRequest",
    "ModelCacheOperatorResponse",
    "ModelCacheOperatorResponseAction",
    "ModelCacheOperatorResponseStateType1",
    "ModelCacheOperatorStatus",
    "ModelCacheRemovalRequest",
    "ModelCacheRemovalResult",
    "ModelDefinition",
    "ModelDefinitionModalitiesItem",
    "ModelDetailResponse",
    "ModelFamily",
    "ModelFile",
    "ModelFilePart",
    "ModelFileState",
    "ModelFormat",
    "ModelIdentity",
    "ModelLibraryResponse",
    "ModelLicense",
    "ModelMetadata",
    "ModelRecord",
    "ModelReference",
    "ModelSource",
    "ModelTerritorialRestrictions",
    "NetworkInterface",
    "NetworkInterfaceKind",
    "NodeConnection",
    "NodeConnectionAgentState",
    "NodeConnectionOnlineState",
    "NodeDistributionAssignment",
    "NodeOfflineReason",
    "NodeProfileChange",
    "NodeProfilePayload",
    "ObservationCause",
    "ObservedAssignmentState",
    "OperationBlocker",
    "OperationBlockerSeverity",
    "OperationCheckpoint",
    "OperationDetailResponse",
    "OperationEvidenceDownload",
    "OperationFailureCode",
    "OperationFailureEvidence",
    "OperationMemberProgress",
    "OperationMemberProgressActivityType0",
    "OperationOwnerReference",
    "OperationProgress",
    "OperationProgressActivityType0",
    "OperationRecovery",
    "OperationRecoveryAction",
    "OperationsResponse",
    "OperatorActionName",
    "OperatorSurface",
    "OutcomeKind",
    "OutputLimits",
    "PackageActivationReceipt",
    "PackageActivationReceiptPhase",
    "PlacementInstallState",
    "PlacementLoadState",
    "PrebuiltImageCode",
    "PreparationReason",
    "PreparationReasonSeverity",
    "ProfileReasonCode",
    "ProjectionCode",
    "ProjectionReason",
    "ProjectionReasonSeverity",
    "ReasonCodeVocabulary",
    "RecipeAlternative",
    "RecipeAlternativeCache",
    "RecipeAlternativeFitsFleet",
    "RecipeBuildCleanupEvidence",
    "RecipeBuildCode",
    "RecipeBuildDefinition",
    "RecipeBuildEvidence",
    "RecipeCancellationRequest",
    "RecipeDefinition",
    "RecipeDetailResponse",
    "RecipeDiskResources",
    "RecipeDownloadRequest",
    "RecipeEmbeddingSettings",
    "RecipeEmbeddingSettingsKnobs",
    "RecipeExecution",
    "RecipeGenerationSettings",
    "RecipeGenerationSettingsKnobs",
    "RecipeHttpServingRequest",
    "RecipeHttpServingRequestBodyType0",
    "RecipeHttpServingRequestMethod",
    "RecipeIdentity",
    "RecipeImage",
    "RecipeImageAvailabilityAction",
    "RecipeImageAvailabilityArtifact",
    "RecipeImageAvailabilityChild",
    "RecipeImageAvailabilityChildKind",
    "RecipeImageAvailabilityChildState",
    "RecipeImageAvailabilityResponse",
    "RecipeImageAvailabilityResponseState",
    "RecipeImageAvailabilityResult",
    "RecipeImageCode",
    "RecipeInputSlot",
    "RecipeInstallationChange",
    "RecipeInstallationPayload",
    "RecipeIntegerSetting",
    "RecipeIntegerSettingChangeEffect",
    "RecipeJobInput",
    "RecipeJobInterface",
    "RecipeJobInterfaceAdapter",
    "RecipeJobOutput",
    "RecipeJobServingRequest",
    "RecipeJobServingRequestInputSlots",
    "RecipeJobSettings",
    "RecipeJobSettingsKnobs",
    "RecipeLibraryResponse",
    "RecipeLifecycle",
    "RecipeMemoryResources",
    "RecipeMetadata",
    "RecipeMetadataAlignmentType0",
    "RecipeModelFile",
    "RecipeModelSelection",
    "RecipeMount",
    "RecipeOpenAIInterface",
    "RecipeOperationCancellationResult",
    "RecipeOperationCancellationResultLaunchEvidenceType0",
    "RecipeOperationCancellationResultNodeEvidenceType0",
    "RecipeOperationCode",
    "RecipeOperatorRequest",
    "RecipeOperatorResponse",
    "RecipeOperatorResponseState",
    "RecipeOption",
    "RecipeOptionChoice",
    "RecipeOptionChoiceEnv",
    "RecipeOutputSlot",
    "RecipePackageCode",
    "RecipeParallelism",
    "RecipePresence",
    "RecipeProvenance",
    "RecipeReadiness",
    "RecipeReadinessCheck",
    "RecipeReadinessCheckState",
    "RecipeReconcileResult",
    "RecipeRelease",
    "RecipeRetryIntent",
    "RecipeRevisionIntent",
    "RecipeRoleResources",
    "RecipeRunChange",
    "RecipeRunPayload",
    "RecipeRuntime",
    "RecipeRuntimeArgument",
    "RecipeRuntimeEnvironment",
    "RecipeSelectorIntent",
    "RecipeServingValidation",
    "RecipeServingValidationInterface",
    "RecipeSetting",
    "RecipeSettingChangeEffect",
    "RecipeStartResult",
    "RecipeStopResult",
    "RecipeTopology",
    "RecipeTopologyRole",
    "RecipeUninstallResult",
    "RecipeUpdateChild",
    "RecipeUpdateChildState",
    "RecipeUpdateCode",
    "RecipeUpdateFailure",
    "RecipeUpdateNotice",
    "RecipeUpdateRequest",
    "RecipeUpdateResponse",
    "RecipeUpdateResponseState",
    "RecipeUpdateScope",
    "RecipeValidation",
    "RecipeValidationCheck",
    "RecipeValidationCheckAssertionsItem",
    "RecipeValidationCheckKind",
    "ReconcileCode",
    "RemovedRecipeNodeResult",
    "RequestValidationIssue",
    "RequestValidationProblem",
    "ReservationState",
    "ResourceBlockerCode",
    "ResourceDemandEvidence",
    "ResourceDemandEvidenceEvidenceState",
    "ResourcePlanningCode",
    "ResourceTerm",
    "ResourceTermProblem",
    "RolloutPreparation",
    "RoutePublicationState",
    "RouteState",
    "RunAdmissionCode",
    "RunDegradedReason",
    "RunMemoryResidualRange",
    "RunMemoryResidualRangeReservationKind",
    "RunNodeChange",
    "RunNodePayload",
    "RunPresence",
    "RunPresenceGroupState",
    "RunPresenceOptionChoices",
    "RunState",
    "RunSwitchAssessment",
    "RunSwitchBuildEvidence",
    "RunSwitchBuildEvidenceState",
    "RunSwitchCachedTransferResult",
    "RunSwitchCachedTransferResultCachedTargetTotals",
    "RunSwitchCancellation",
    "RunSwitchChildProgress",
    "RunSwitchChildProgressPhaseType0",
    "RunSwitchCleanupResult",
    "RunSwitchCleanupResultSubphaseType0",
    "RunSwitchCleanupVerifyResult",
    "RunSwitchCleanupVerifyResultCleanupMode",
    "RunSwitchCleanupVerifyResultSubphaseType0",
    "RunSwitchCode",
    "RunSwitchContainerBuildResult",
    "RunSwitchContainerBuildResultState",
    "RunSwitchFinalVerifyResult",
    "RunSwitchFinalVerifyResultSubphaseType0",
    "RunSwitchInstallationVerifyResult",
    "RunSwitchInstallationVerifyResultSubphaseType0",
    "RunSwitchMemberProgress",
    "RunSwitchMemberProgressPhaseType0",
    "RunSwitchMemberProgressState",
    "RunSwitchMemberReceipt",
    "RunSwitchMemberReceiptPhaseType0",
    "RunSwitchMemberReceiptState",
    "RunSwitchModelDownloadPendingResult",
    "RunSwitchModelDownloadResult",
    "RunSwitchOperation",
    "RunSwitchOperationAction",
    "RunSwitchOperationCleanupModeType0",
    "RunSwitchOperationCompletedPhasesItem",
    "RunSwitchOperationCurrentPhaseType0",
    "RunSwitchOperationKind",
    "RunSwitchOperationResult",
    "RunSwitchOperationResultCompletedPhasesItem",
    "RunSwitchOperationResultFailedPhaseType0",
    "RunSwitchOperationResultPhaseType0",
    "RunSwitchOperationResultSubphaseType0",
    "RunSwitchOperationState",
    "RunSwitchPhase",
    "RunSwitchPhaseKind",
    "RunSwitchPhaseState",
    "RunSwitchPhaseSubphaseType0",
    "RunSwitchPlan",
    "RunSwitchPlanAction",
    "RunSwitchPlanCleanupDisposition",
    "RunSwitchPlanCleanupMode",
    "RunSwitchPreparedResult",
    "RunSwitchProfileStopScope",
    "RunSwitchProgress",
    "RunSwitchProgressPhaseType0",
    "RunSwitchProgressState",
    "RunSwitchProgressSubphaseType0",
    "RunSwitchRankReceipt",
    "RunSwitchReason",
    "RunSwitchReasonScope",
    "RunSwitchReasonSeverity",
    "RunSwitchReconciliationAuthority",
    "RunSwitchReconciliationTarget",
    "RunSwitchReconciliationTargetState",
    "RunSwitchRuntimeImageReferenceIntent",
    "RunSwitchRuntimeImageResult",
    "RunSwitchRuntimeInstallResult",
    "RunSwitchRuntimePlanResult",
    "RunSwitchStartResult",
    "RunSwitchStartResultSubphaseType0",
    "RunSwitchStopResult",
    "RunSwitchStopResultSubphaseType0",
    "RunSwitchTargetTransferEvidenceResult",
    "RunSwitchTargetTransferResult",
    "RunSwitchTargetTransferResultAssignments",
    "RunSwitchUninstallResult",
    "RunSwitchUninstallResultDisposition",
    "RunSwitchUninstallResultSubphaseType0",
    "RunSwitchVerifyResult",
    "RunSwitchVerifyResultCachedTargetTotals",
    "RuntimeImageCode",
    "RuntimeImageIdentity",
    "RuntimeImagePreparation",
    "RuntimeImageReceipt",
    "RuntimeImageStorageImpact",
    "RuntimeImageStorageImpactMissingImageDistributionBytesByNodeType0",
    "RuntimeImageStorageImpactNasCoverage",
    "RuntimeImageStorageImpactRunningCoverage",
    "RuntimeImageStorageImpactSparkCoverage",
    "RuntimePreflightCode",
    "RuntimePreflightFinding",
    "RuntimePreflightFindingCode",
    "RuntimePreflightFindingStatus",
    "RuntimePreflightResult",
    "SecurityRefusal",
    "SecurityRefusalReason",
    "SourceBundleCode",
    "SourcePolicyCode",
    "SparkFit",
    "SparkFitNode",
    "SparkFitNodeMemoryKindType0",
    "SparkFitNodeMemoryPoolType0",
    "SparkGroup",
    "SparkGroupNode",
    "StateAlias",
    "StateWriteKind",
    "StopImpact",
    "StopOutcome",
    "StopPlanCode",
    "StorageDemandCode",
    "StringParameter",
    "SupersedeCode",
    "TargetAssetState",
    "TargetAssetStateState",
    "TelemetryPoint",
    "TelemetryState",
    "TelemetryStateFreshness",
    "TopologyCode",
    "UninstallPlanCode",
    "UnknownError",
    "WaitReason",
    "WaitVerdict",
)
