from typing import Literal

FailureStage = Literal['agent-restart', 'agent-upgrade-installed', 'artifact-distribution', 'base-image-import', 'bounded-build-process', 'egress-address', 'egress-image-import', 'egress-network-create', 'egress-readiness', 'egress-service-start', 'helper-runtime-reconciliation', 'helper-runtime-reconciliation-lock', 'image-build', 'image-upload', 'image-verification', 'installation-checkpoint-storage', 'installation-directory', 'installation-metadata', 'installation-path', 'installation-receipt', 'installation-reconciliation-lock', 'installation-removal', 'installation-validation', 'job-cancel-stop', 'job-inputs', 'job-state', 'job-stop', 'lifecycle-metadata', 'model-custody', 'model-materialization', 'observation-identity', 'output-storage', 'retained-container', 'run-storage', 'runtime-adapter', 'runtime-cache', 'runtime-cache-cleanup', 'runtime-metadata', 'runtime-projection', 'source-bundle-fetch', 'stop', 'stop-cleanup', 'stop-metadata', 'stop-plan', 'unknown']

FAILURE_STAGE_VALUES: set[FailureStage] = { 'agent-restart', 'agent-upgrade-installed', 'artifact-distribution', 'base-image-import', 'bounded-build-process', 'egress-address', 'egress-image-import', 'egress-network-create', 'egress-readiness', 'egress-service-start', 'helper-runtime-reconciliation', 'helper-runtime-reconciliation-lock', 'image-build', 'image-upload', 'image-verification', 'installation-checkpoint-storage', 'installation-directory', 'installation-metadata', 'installation-path', 'installation-receipt', 'installation-reconciliation-lock', 'installation-removal', 'installation-validation', 'job-cancel-stop', 'job-inputs', 'job-state', 'job-stop', 'lifecycle-metadata', 'model-custody', 'model-materialization', 'observation-identity', 'output-storage', 'retained-container', 'run-storage', 'runtime-adapter', 'runtime-cache', 'runtime-cache-cleanup', 'runtime-metadata', 'runtime-projection', 'source-bundle-fetch', 'stop', 'stop-cleanup', 'stop-metadata', 'stop-plan', 'unknown',  }

def check_failure_stage(value: str) -> FailureStage:
    if value in FAILURE_STAGE_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {FAILURE_STAGE_VALUES!r}")
