from typing import Literal

HelperOperationCode = Literal['helper.artifact_invalid', 'helper.command_failed', 'helper.installation_intent_observation_required', 'helper.installation_reconciliation_busy', 'helper.installation_reconciliation_storage_unavailable', 'helper.io_failed', 'helper.operation_invalid', 'helper.package_install_failed', 'helper.package_metadata_invalid', 'helper.package_preflight_failed', 'helper.package_preparation_unavailable', 'helper.runtime_endpoint_firewall_rejected', 'helper.runtime_fabric_firewall_rejected', 'helper.runtime_fabric_unavailable', 'helper.runtime_image_identity_invalid', 'helper.runtime_image_inspect_failed', 'helper.runtime_image_load_failed', 'helper.runtime_image_receipt_failed', 'helper.runtime_invocation_limit_exceeded', 'helper.runtime_invocation_limits_unavailable', 'helper.runtime_invocation_string_limit_exceeded', 'helper.runtime_process_exited', 'helper.runtime_run_missing', 'helper.stop_uncertain', 'helper.unsafe_path']

HELPER_OPERATION_CODE_VALUES: set[HelperOperationCode] = { 'helper.artifact_invalid', 'helper.command_failed', 'helper.installation_intent_observation_required', 'helper.installation_reconciliation_busy', 'helper.installation_reconciliation_storage_unavailable', 'helper.io_failed', 'helper.operation_invalid', 'helper.package_install_failed', 'helper.package_metadata_invalid', 'helper.package_preflight_failed', 'helper.package_preparation_unavailable', 'helper.runtime_endpoint_firewall_rejected', 'helper.runtime_fabric_firewall_rejected', 'helper.runtime_fabric_unavailable', 'helper.runtime_image_identity_invalid', 'helper.runtime_image_inspect_failed', 'helper.runtime_image_load_failed', 'helper.runtime_image_receipt_failed', 'helper.runtime_invocation_limit_exceeded', 'helper.runtime_invocation_limits_unavailable', 'helper.runtime_invocation_string_limit_exceeded', 'helper.runtime_process_exited', 'helper.runtime_run_missing', 'helper.stop_uncertain', 'helper.unsafe_path',  }

def check_helper_operation_code(value: str) -> HelperOperationCode:
    if value in HELPER_OPERATION_CODE_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {HELPER_OPERATION_CODE_VALUES!r}")
