from typing import Literal

ProfileReasonCode = Literal['profile.admission_busy', 'profile.admission_effect_busy', 'profile.application_intent.invalid', 'profile.asset_reservation_unavailable', 'profile.choices_unreadable', 'profile.cleanup_delegated', 'profile.distributed_cross_scope', 'profile.incomplete_multi_spark_model', 'profile.interruption_expected', 'profile.pending_cross_scope', 'profile.preparation_not_started', 'profile.preparation_scope_mismatch', 'profile.preparation_unavailable', 'profile.recipe_unavailable', 'profile.recovery_artifact_changed', 'profile.recovery_assignments_changed', 'profile.recovery_cache_pending', 'profile.recovery_scope_changed', 'profile.recovery_waiting', 'profile.resource_recheck_unavailable', 'profile.retry_conflict', 'profile.retry_executor_unavailable', 'profile.retry_intent_unavailable', 'profile.retry_review_unavailable', 'profile.review_stale', 'profile.runtime-image-changed', 'profile.runtime_image_rebuild_pending', 'profile.selection_lost', 'profile.shared_installation_scope', 'profile.spark_removed', 'profile.spark_unavailable', 'profile.stale_plan', 'profile.switch_authority_unavailable', 'profile.switch_scope_unresolved', 'profile.topology_incomplete']

PROFILE_REASON_CODE_VALUES: set[ProfileReasonCode] = { 'profile.admission_busy', 'profile.admission_effect_busy', 'profile.application_intent.invalid', 'profile.asset_reservation_unavailable', 'profile.choices_unreadable', 'profile.cleanup_delegated', 'profile.distributed_cross_scope', 'profile.incomplete_multi_spark_model', 'profile.interruption_expected', 'profile.pending_cross_scope', 'profile.preparation_not_started', 'profile.preparation_scope_mismatch', 'profile.preparation_unavailable', 'profile.recipe_unavailable', 'profile.recovery_artifact_changed', 'profile.recovery_assignments_changed', 'profile.recovery_cache_pending', 'profile.recovery_scope_changed', 'profile.recovery_waiting', 'profile.resource_recheck_unavailable', 'profile.retry_conflict', 'profile.retry_executor_unavailable', 'profile.retry_intent_unavailable', 'profile.retry_review_unavailable', 'profile.review_stale', 'profile.runtime-image-changed', 'profile.runtime_image_rebuild_pending', 'profile.selection_lost', 'profile.shared_installation_scope', 'profile.spark_removed', 'profile.spark_unavailable', 'profile.stale_plan', 'profile.switch_authority_unavailable', 'profile.switch_scope_unresolved', 'profile.topology_incomplete',  }

def check_profile_reason_code(value: str) -> ProfileReasonCode:
    if value in PROFILE_REASON_CODE_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {PROFILE_REASON_CODE_VALUES!r}")
