from typing import Literal

RecipeImageCode = Literal['recipe_image.action_invalid', 'recipe_image.build_cancelled', 'recipe_image.build_capacity_wait', 'recipe_image.build_failed', 'recipe_image.build_input_missing', 'recipe_image.build_invalid', 'recipe_image.build_unavailable', 'recipe_image.build_wait', 'recipe_image.builder_busy', 'recipe_image.builder_occupied', 'recipe_image.cancel_busy', 'recipe_image.cancel_request_key_reused', 'recipe_image.cancellation_invalid', 'recipe_image.claim_lost', 'recipe_image.database_busy', 'recipe_image.identity_conflict', 'recipe_image.identity_invalid', 'recipe_image.insufficient_disk', 'recipe_image.insufficient_memory', 'recipe_image.metadata_refresh_failed', 'recipe_image.metadata_refresh_unavailable', 'recipe_image.model_cache_failed', 'recipe_image.model_cache_invalid', 'recipe_image.model_cache_unavailable', 'recipe_image.model_child_cancelled', 'recipe_image.model_child_missing', 'recipe_image.no_builder', 'recipe_image.not_cancellable', 'recipe_image.not_retryable', 'recipe_image.operation_invalid', 'recipe_image.operation_missing', 'recipe_image.preparation_failed', 'recipe_image.preparing', 'recipe_image.recipe_invalid', 'recipe_image.recipe_unavailable', 'recipe_image.removal_choice_invalid', 'recipe_image.removal_evidence_unavailable', 'recipe_image.removal_failed', 'recipe_image.removal_referenced', 'recipe_image.removal_scope_limited', 'recipe_image.request_key_reused', 'recipe_image.runtime_invalid', 'recipe_image.selector_ambiguous', 'recipe_image.selector_invalid', 'recipe_image.selector_missing', 'recipe_image.source_policy_refused', 'recipe_image.superseded_by_newer_revision', 'recipe_image.waiting_for_model', 'recipe_image.waiting_for_worker']

RECIPE_IMAGE_CODE_VALUES: set[RecipeImageCode] = { 'recipe_image.action_invalid', 'recipe_image.build_cancelled', 'recipe_image.build_capacity_wait', 'recipe_image.build_failed', 'recipe_image.build_input_missing', 'recipe_image.build_invalid', 'recipe_image.build_unavailable', 'recipe_image.build_wait', 'recipe_image.builder_busy', 'recipe_image.builder_occupied', 'recipe_image.cancel_busy', 'recipe_image.cancel_request_key_reused', 'recipe_image.cancellation_invalid', 'recipe_image.claim_lost', 'recipe_image.database_busy', 'recipe_image.identity_conflict', 'recipe_image.identity_invalid', 'recipe_image.insufficient_disk', 'recipe_image.insufficient_memory', 'recipe_image.metadata_refresh_failed', 'recipe_image.metadata_refresh_unavailable', 'recipe_image.model_cache_failed', 'recipe_image.model_cache_invalid', 'recipe_image.model_cache_unavailable', 'recipe_image.model_child_cancelled', 'recipe_image.model_child_missing', 'recipe_image.no_builder', 'recipe_image.not_cancellable', 'recipe_image.not_retryable', 'recipe_image.operation_invalid', 'recipe_image.operation_missing', 'recipe_image.preparation_failed', 'recipe_image.preparing', 'recipe_image.recipe_invalid', 'recipe_image.recipe_unavailable', 'recipe_image.removal_choice_invalid', 'recipe_image.removal_evidence_unavailable', 'recipe_image.removal_failed', 'recipe_image.removal_referenced', 'recipe_image.removal_scope_limited', 'recipe_image.request_key_reused', 'recipe_image.runtime_invalid', 'recipe_image.selector_ambiguous', 'recipe_image.selector_invalid', 'recipe_image.selector_missing', 'recipe_image.source_policy_refused', 'recipe_image.superseded_by_newer_revision', 'recipe_image.waiting_for_model', 'recipe_image.waiting_for_worker',  }

def check_recipe_image_code(value: str) -> RecipeImageCode:
    if value in RECIPE_IMAGE_CODE_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {RECIPE_IMAGE_CODE_VALUES!r}")
