from typing import Literal

ResourcePlanningCode = Literal['resource.batch_evidence_invalid', 'resource.batch_evidence_unknown', 'resource.batch_unknown', 'resource.batch_unsupported', 'resource.concurrency_evidence_invalid', 'resource.concurrency_evidence_unknown', 'resource.concurrency_unknown', 'resource.concurrency_unsupported', 'resource.context_evidence_invalid', 'resource.context_evidence_unknown', 'resource.context_unknown', 'resource.context_unsupported', 'resource.envelope_exceeds_capacity', 'resource.envelope_unverified', 'resource.estimate_uncertain', 'resource.evidence_invalid', 'resource.evidence_unknown', 'resource.knobs_invalid', 'resource.parallelism_duplicate', 'resource.parallelism_inconsistent', 'resource.parallelism_type', 'resource.parallelism_unknown', 'resource.settings_kind_unknown', 'resource.settings_type', 'resource.settings_unknown', 'resource.stop_release_unknown']

RESOURCE_PLANNING_CODE_VALUES: set[ResourcePlanningCode] = { 'resource.batch_evidence_invalid', 'resource.batch_evidence_unknown', 'resource.batch_unknown', 'resource.batch_unsupported', 'resource.concurrency_evidence_invalid', 'resource.concurrency_evidence_unknown', 'resource.concurrency_unknown', 'resource.concurrency_unsupported', 'resource.context_evidence_invalid', 'resource.context_evidence_unknown', 'resource.context_unknown', 'resource.context_unsupported', 'resource.envelope_exceeds_capacity', 'resource.envelope_unverified', 'resource.estimate_uncertain', 'resource.evidence_invalid', 'resource.evidence_unknown', 'resource.knobs_invalid', 'resource.parallelism_duplicate', 'resource.parallelism_inconsistent', 'resource.parallelism_type', 'resource.parallelism_unknown', 'resource.settings_kind_unknown', 'resource.settings_type', 'resource.settings_unknown', 'resource.stop_release_unknown',  }

def check_resource_planning_code(value: str) -> ResourcePlanningCode:
    if value in RESOURCE_PLANNING_CODE_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {RESOURCE_PLANNING_CODE_VALUES!r}")
