from typing import Literal

RuntimeImageCode = Literal['registry.destination_forbidden', 'registry.digest_mismatch', 'registry.redirect_forbidden', 'runtime_image.architecture_mismatch', 'runtime_image.architecture_missing', 'runtime_image.archive_conflict', 'runtime_image.archive_invalid', 'runtime_image.archive_mismatch', 'runtime_image.archive_size_mismatch', 'runtime_image.archive_unavailable', 'runtime_image.build_archive_digest', 'runtime_image.build_digest', 'runtime_image.build_id', 'runtime_image.build_incomplete', 'runtime_image.cache_missing', 'runtime_image.config_missing', 'runtime_image.digest_invalid', 'runtime_image.digest_mismatch', 'runtime_image.evidence_invalid', 'runtime_image.identity_invalid', 'runtime_image.image_unpinned', 'runtime_image.inspect_invalid', 'runtime_image.insufficient_disk', 'runtime_image.interface_mismatch', 'runtime_image.interface_missing', 'runtime_image.lock_unavailable', 'runtime_image.publication_contended', 'runtime_image.receipt_contract_newer', 'runtime_image.receipt_identity_conflict', 'runtime_image.receipt_identity_invalid', 'runtime_image.receipt_invalid', 'runtime_image.receipt_persistence_failed', 'runtime_image.receipt_unavailable', 'runtime_image.receipt_write_failed', 'runtime_image.recipe_invalid', 'runtime_image.reference_intent_invalid', 'runtime_image.removal_storage_failed', 'runtime_image.runtime_invalid', 'runtime_image.source_mismatch', 'runtime_image.transfer_contended']

RUNTIME_IMAGE_CODE_VALUES: set[RuntimeImageCode] = { 'registry.destination_forbidden', 'registry.digest_mismatch', 'registry.redirect_forbidden', 'runtime_image.architecture_mismatch', 'runtime_image.architecture_missing', 'runtime_image.archive_conflict', 'runtime_image.archive_invalid', 'runtime_image.archive_mismatch', 'runtime_image.archive_size_mismatch', 'runtime_image.archive_unavailable', 'runtime_image.build_archive_digest', 'runtime_image.build_digest', 'runtime_image.build_id', 'runtime_image.build_incomplete', 'runtime_image.cache_missing', 'runtime_image.config_missing', 'runtime_image.digest_invalid', 'runtime_image.digest_mismatch', 'runtime_image.evidence_invalid', 'runtime_image.identity_invalid', 'runtime_image.image_unpinned', 'runtime_image.inspect_invalid', 'runtime_image.insufficient_disk', 'runtime_image.interface_mismatch', 'runtime_image.interface_missing', 'runtime_image.lock_unavailable', 'runtime_image.publication_contended', 'runtime_image.receipt_contract_newer', 'runtime_image.receipt_identity_conflict', 'runtime_image.receipt_identity_invalid', 'runtime_image.receipt_invalid', 'runtime_image.receipt_persistence_failed', 'runtime_image.receipt_unavailable', 'runtime_image.receipt_write_failed', 'runtime_image.recipe_invalid', 'runtime_image.reference_intent_invalid', 'runtime_image.removal_storage_failed', 'runtime_image.runtime_invalid', 'runtime_image.source_mismatch', 'runtime_image.transfer_contended',  }

def check_runtime_image_code(value: str) -> RuntimeImageCode:
    if value in RUNTIME_IMAGE_CODE_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {RUNTIME_IMAGE_CODE_VALUES!r}")
