from typing import Literal

SecurityRefusalReason = Literal['401', '403', 'agent.certificate.rotation.conflict', 'agent.enrollment.submit.rejected', 'agent.identity_mismatch', 'agent.tombstone_fenced', 'catalog.authentication_required', 'controller.authentication_required', 'controller.fleet.enrollment_denied', 'controller.request_rejected', 'digest_verification_failed', 'distribution.revoked', 'forbidden', 'grant_invalid', 'grant_node_mismatch', 'grant_unauthorized', 'helper.authorization_invalid', 'helper_grant_invalid', 'helper_grant_node_mismatch', 'helper_grant_unauthorized', 'helper_operation_invalid_artifact', 'helper_peer_identity_invalid', 'helper_request_installation_identity_invalid', 'helper_request_plan_binding_invalid', 'helper_request_replayed', 'helper_runtime_image_identity_invalid', 'host_helper.authority_denied', 'local.identity_expired', 'local.identity_failed', 'model_cache.credentials_denied', 'model_cache.credentials_invalid', 'model_cache.source_access_denied', 'operation_invalid_artifact', 'peer_identity_invalid', 'permission_denied', 'recipe_update.authority_denied', 'request_replayed', 'run-switch.artifact-digest-verification-failed', 'run-switch.cleanup-nas-eviction-forbidden', 'run-switch.cleanup-reclaimed-digest-not-planned', 'run-switch.runtime-image-preparation-digest-mismatch', 'runtime_image.authorization_invalid', 'runtime_image.authorization_revoked', 'runtime_image_identity_invalid', 'stale_fence', 'tuf.metadata_invalid', 'tuf.signature_invalid', 'unauthorized', 'unsafe_path']

SECURITY_REFUSAL_REASON_VALUES: set[SecurityRefusalReason] = { '401', '403', 'agent.certificate.rotation.conflict', 'agent.enrollment.submit.rejected', 'agent.identity_mismatch', 'agent.tombstone_fenced', 'catalog.authentication_required', 'controller.authentication_required', 'controller.fleet.enrollment_denied', 'controller.request_rejected', 'digest_verification_failed', 'distribution.revoked', 'forbidden', 'grant_invalid', 'grant_node_mismatch', 'grant_unauthorized', 'helper.authorization_invalid', 'helper_grant_invalid', 'helper_grant_node_mismatch', 'helper_grant_unauthorized', 'helper_operation_invalid_artifact', 'helper_peer_identity_invalid', 'helper_request_installation_identity_invalid', 'helper_request_plan_binding_invalid', 'helper_request_replayed', 'helper_runtime_image_identity_invalid', 'host_helper.authority_denied', 'local.identity_expired', 'local.identity_failed', 'model_cache.credentials_denied', 'model_cache.credentials_invalid', 'model_cache.source_access_denied', 'operation_invalid_artifact', 'peer_identity_invalid', 'permission_denied', 'recipe_update.authority_denied', 'request_replayed', 'run-switch.artifact-digest-verification-failed', 'run-switch.cleanup-nas-eviction-forbidden', 'run-switch.cleanup-reclaimed-digest-not-planned', 'run-switch.runtime-image-preparation-digest-mismatch', 'runtime_image.authorization_invalid', 'runtime_image.authorization_revoked', 'runtime_image_identity_invalid', 'stale_fence', 'tuf.metadata_invalid', 'tuf.signature_invalid', 'unauthorized', 'unsafe_path',  }

def check_security_refusal_reason(value: str) -> SecurityRefusalReason:
    if value in SECURITY_REFUSAL_REASON_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {SECURITY_REFUSAL_REASON_VALUES!r}")
