import {useEffect, useState} from "react";
import type {LibraryApi, LibraryRecipeDetail, LibraryRecipeSummary} from "../api/types";
import {formatBytes} from "../lib/fleet";

export function LibraryComparison({api, recipes, selectedIds, onToggle}: {api: LibraryApi; recipes: LibraryRecipeSummary[]; selectedIds: string[]; onToggle(recipeId: string): void}) {
  const [details, setDetails] = useState<Record<string, LibraryRecipeDetail>>({});
  useEffect(() => { const controller = new AbortController(); for (const id of selectedIds.slice(0, 3)) if (!details[id]) void api.libraryRecipe(id, controller.signal).then(detail => { if (!controller.signal.aborted) setDetails(current => ({...current, [id]: detail})); }).catch(() => undefined); return () => controller.abort(); }, [api, details, selectedIds]);
  const selected = selectedIds.flatMap(id => recipes.find(recipe => recipe.recipe_id === id) ? [recipes.find(recipe => recipe.recipe_id === id)!] : []);
  if (!selected.length) return <section className="library-compare-empty" aria-label="Recipe comparison"><h3>Choose Recipes to compare</h3><p>Select up to three exact Recipes.</p></section>;
  return <section className="library-comparison" aria-label="Recipe comparison"><header><h3>Recipe comparison</h3><span>{selected.length} of 3 selected</span></header><div className="library-comparison-scroll" tabIndex={0}><table><thead><tr><th scope="col">Fact</th>{selected.map(recipe => <th scope="col" key={recipe.recipe_id}><strong>{recipe.title}</strong><button type="button" onClick={() => onToggle(recipe.recipe_id)}>Remove</button></th>)}</tr></thead><tbody><tr><th scope="row">Topology</th>{selected.map(recipe => <td key={recipe.recipe_id}>{recipe.topology_name ?? "Not declared"}</td>)}</tr><tr><th scope="row">Capabilities</th>{selected.map(recipe => <td key={recipe.recipe_id}>{recipe.capabilities.join(" · ") || "Not declared"}</td>)}</tr><tr><th scope="row">Model files</th>{selected.map(recipe => { const detail = details[recipe.recipe_id]; const bytes = detail?.model_documents.flatMap(item => item.model_document.files).reduce((sum, file) => sum + file.size_bytes, 0); return <td key={recipe.recipe_id}>{bytes === undefined ? "Loading…" : formatBytes(bytes)}</td>; })}</tr></tbody></table></div></section>;
}
