import {useEffect, useMemo, useState} from "react";
import type {MouseEvent} from "react";
import type {ControlApi, LibraryModel, LibrarySnapshot, VisualFleetSnapshot} from "../api/types";
import {formatBytes, nodeDisplayName} from "../lib/fleet";
import {modelLibraryPath, modelVersionKey} from "../lib/library-route";
import type {LibraryRecipeRecord, LibraryWorkcellFilters} from "./library-workcell";
import {filterLibraryRecipeRecords} from "./library-workcell";
import {aggregateCacheEntries, LibraryModelDownloadAction, loadModelCacheInventory} from "./library-cache-view";
import {LibraryModelDeletionDialog} from "./library-model-deletion-dialog";

export function LibraryModelsView({api, entries, filters, fleet, modelInventory, onBusyChange, onFiltersChange, onNavigate, onNavigatePath, onQueryChange, onRefresh, path, query}: {api: ControlApi; entries: LibraryRecipeRecord[]; fleet?: VisualFleetSnapshot; filters: LibraryWorkcellFilters; modelInventory?: LibrarySnapshot["models"]; onBusyChange?(busy: boolean): void; onFiltersChange(filters: LibraryWorkcellFilters): void; onNavigate(event: MouseEvent<HTMLAnchorElement>, path: string): void; onNavigatePath?(path: string, replace?: boolean): void; onQueryChange(value: string): void; onRefresh?: (signal: AbortSignal) => Promise<void>; path: string; query: string}) {
  const [deleteModel, setDeleteModel] = useState<LibraryModel>();
  const [cacheInventory, setCacheInventory] = useState<{entries: import("../api/types").CacheEntryResponse[]}>();
  const [cacheAttempt, setCacheAttempt] = useState(0);
  const [cacheLoading, setCacheLoading] = useState(true);
  const [cacheError, setCacheError] = useState("");
  const models = modelInventory ?? [];
  const filtered = filterLibraryRecipeRecords(entries, filters, query);
  const visible = models.filter(model => !filters.model || modelVersionKey(model.model) === filters.model).filter(model => !query.trim() || filtered.some(record => record.modelKey === modelVersionKey(model.model)));
  useEffect(() => { if (!api.modelCacheInventory) { setCacheLoading(false); setCacheError("NAS cache API unavailable"); return; } const controller = new AbortController(); setCacheLoading(true); setCacheError(""); void loadModelCacheInventory(api, controller.signal).then(value => { if (!controller.signal.aborted) setCacheInventory(value); }).catch(value => { if (!controller.signal.aborted) setCacheError(value instanceof Error ? value.message : "NAS cache inventory unavailable"); }).finally(() => { if (!controller.signal.aborted) setCacheLoading(false); }); return () => controller.abort(); }, [api, cacheAttempt]);
  const cacheByModel = useMemo(() => new Map(aggregateCacheEntries(models, cacheInventory).map(entry => [entry.key, entry])), [cacheInventory, models]);
  const nodeNames = Object.fromEntries((fleet?.nodes ?? []).map(node => [node.id, nodeDisplayName(node)]));
  function updateModel(value: string) {
    onFiltersChange({...filters, model: value});
    if (onNavigatePath) { const url = new URL(path, location.origin); if (value) url.searchParams.set("model", value); else url.searchParams.delete("model"); onNavigatePath(`${url.pathname}${url.search}`, true); }
  }
  const titleFor = (model: LibraryModel) => model.model_document.identity.model.title || model.model_document.identity.family.title || `${model.model.publisher}/${model.model.slug}`;
  return <section className="library-models-view" aria-labelledby="library-models-heading">
    <header className="library-subview-heading"><div><h2 id="library-models-heading">Models</h2><p>Exact model manifests own their files, bytes, and capability evidence.</p></div><span>{visible.length} of {models.length} Models</span></header>{cacheError && <div className="library-error" role="alert"><span>NAS cache: {cacheError}</span><button type="button" className="button secondary" onClick={() => setCacheAttempt(value => value + 1)}>Retry cache</button></div>}
    <div className="library-model-controls"><label>Search Models<input type="search" aria-label="Search Models" value={query} onChange={event => onQueryChange(event.target.value)} placeholder="Search model title or capability"/></label><label>Exact Model<select aria-label="Filter exact model" value={filters.model} onChange={event => updateModel(event.target.value)}><option value="">All Models</option>{models.map(model => <option key={modelVersionKey(model.model)} value={modelVersionKey(model.model)}>{titleFor(model)}</option>)}</select></label></div>
    <div className="library-model-list" aria-label="Exact model inventory">{visible.map(model => { const key = modelVersionKey(model.model); const modelRecords = entries.filter(record => record.modelKey === key && record.recipe); const bytes = model.model_document.files.reduce((sum, file) => sum + file.size_bytes, 0); const caps = (model.model_capabilities?.facts ?? []).filter(fact => fact.support === "supported").map(fact => fact.capability); const cache = cacheByModel.get(model.model.content_sha256); const cacheLabel = cacheLoading ? "loading" : cacheError ? "unavailable" : cache?.status ?? "not cached"; return <div key={key} className="library-model-row"><div><a href={modelLibraryPath(key)} onClick={event => onNavigate(event, modelLibraryPath(key))}><h3>{titleFor(model)}</h3><p>{model.model.publisher}/{model.model.slug} · {model.model_document.identity.variant}</p></a><div className="library-model-badges">{caps.length ? caps.map(capability => <span key={capability}>{capability}</span>) : <span>Capabilities unknown</span>}</div><span className={`library-cache-status state-${cacheLabel}`}>NAS cache: {cacheLabel}{!cacheLoading && !cacheError && ` · ${formatBytes(cache?.verifiedBytes ?? 0)} / ${formatBytes(bytes)} verified`}</span></div><dl><div><dt>Files</dt><dd>{model.model_document.files.length}</dd></div><div><dt>Bytes</dt><dd>{formatBytes(bytes)}</dd></div><div><dt>Recipes</dt><dd>{modelRecords.length || "No Recipe"}</dd></div></dl><LibraryModelDownloadAction api={api} model={model} onComplete={() => setCacheAttempt(value => value + 1)}/><button type="button" className="button secondary" onClick={() => setDeleteModel(model)}>Review Model removal</button></div>; })}{visible.length === 0 && <p className="library-empty-state">No Models match the current filters.</p>}</div>{deleteModel && <LibraryModelDeletionDialog api={api} modelTitle={titleFor(deleteModel)} modelVersionSha256={deleteModel.model.content_sha256} nodeNames={nodeNames} onBusyChange={onBusyChange} onClose={() => setDeleteModel(undefined)} onRefresh={onRefresh ?? (async () => undefined)}/>}</section>
}
