# Import contracts first: its operation registry imports lifecycle models, and
# those models refer back to the compiled plan primitives.
# ruff: noqa: I001
from .contracts import (
    MAX_COMPILED_EXECUTION_PLAN_CLAIM_BYTES,
    MAX_COMPILED_EXECUTION_PLAN_DOCUMENT_BYTES,
    MAX_DOCUMENT_BYTES,
    AgentClaim,
    AgentDirective,
    AgentFailureKind,
    AgentFailureResult,
    AgentInstallResult,
    AgentOperation,
    AgentPayload,
    AgentProgress,
    AgentProtocolError,
    AgentResult,
    AgentResultPayload,
    AgentUpgradeResult,
    AgentUpgradePayload,
    ArtifactDistributionPayload,
    ArtifactDistributionResult,
    RecipeStartResult,
    canonical_message,
    canonical_payload,
    format_model_identity,
    parse_model_identity,
    schema_validator,
    validate_schema_message,
    validate_result_for_operation,
)
from .build_import import (
    RecipeBuildCleanupEvidence,
    RecipeBuildCleanupRequest,
    RecipeBuildEvidence,
    RecipeBuildRequest,
    RecipeImageImportEvidence,
    RecipeImageImportRequest,
)
from .compiled_execution_plan import (
    CompiledExecutionPlan,
    CompiledExecutionPlanError,
    CompiledJobInput,
    CompiledJobInputSlot,
    validate_compiled_execution_plan,
)
from .distribution import (
    DistributionAssignment,
    DistributionObject,
)
from .failure_evidence import FailureDiagnostics
from .host_helper import (
    ConfirmPackageActivationOperation,
    ContainerRuntimeAction,
    ExecuteContainerRuntimeRequestOperation,
    HostHelperGrantClaims,
    HostHelperSignature,
    HostOperation,
    HostOperationKind,
    InstallVonkDebOperation,
    HostRuntimeRequest,
    RecipeReconciliationIdentity,
    RecipeRunObservationReceiptClaims,
    RestartUnit,
    SignedHostHelperGrant,
    SignedRecipeRunObservationReceipt,
    host_helper_grant_signing_bytes,
    recipe_run_observation_receipt_signing_bytes,
)
from .inventory import InventoryRequest
from .recipe_jobs import (
    RecipeJobEvidence,
    RecipeJobFile,
    RecipeJobInputFile,
    RecipeJobOutputLimits,
    RecipeJobOutputManifest,
    RecipeJobOutputMapping,
    RecipeJobRunRequest,
    RecipeJobRunResult,
)
from .recipe_jobs import (
    manifest_document as recipe_job_manifest_document,
)
from .recipe_jobs import (
    manifest_sha256 as recipe_job_manifest_sha256,
)
from .recipe_observations import (
    RECIPE_RUN_OBSERVATION_SCHEMA_VERSION,
    RecipeRunObservationGrantRequest,
    RecipeRunObservationGrantWire,
    RecipeRunObservationsWire,
    RecipeRunObservationWire,
)
from .recipe_operations import (
    RECIPE_OPERATIONS,
    RecipeInstallPayload,
    RecipeOperationRequest,
    RecipeStartPayload,
    RecipeStopPayload,
    RecipeStopResult,
    RecipeReconcilePayload,
    RecipeReconcileResult,
    RecipeUninstallPayload,
    RecipeUninstallResult,
    parse_recipe_operation_result,
)
from .telemetry import (
    TelemetryRequest,
    TelemetrySample,
)
from .package_upgrade import (
    PackageActivationReceipt,
    PackageRollbackAuthority,
    PackageRollbackSource,
)
from .wire_model import (
    ERROR_CODE_PATTERN,
    ErrorCode,
    OperationCheckpoint,
    OperationMemberProgress,
    OperationProgress,
    StrictJSONModel,
    WireModel,
    normalize_operation_progress,
)

HostRuntimeRequest.model_rebuild(
    _types_namespace={
        "RecipeStartPayload": RecipeStartPayload,
        "RecipeJobRunRequest": RecipeJobRunRequest,
        "RecipeStopPayload": RecipeStopPayload,
    }
)

__all__ = [
    "ERROR_CODE_PATTERN",
    "MAX_COMPILED_EXECUTION_PLAN_CLAIM_BYTES",
    "MAX_COMPILED_EXECUTION_PLAN_DOCUMENT_BYTES",
    "MAX_DOCUMENT_BYTES",
    "RECIPE_OPERATIONS",
    "RECIPE_RUN_OBSERVATION_SCHEMA_VERSION",
    "AgentClaim",
    "AgentDirective",
    "AgentFailureKind",
    "AgentFailureResult",
    "AgentInstallResult",
    "AgentOperation",
    "AgentPayload",
    "AgentProgress",
    "AgentProtocolError",
    "AgentResult",
    "AgentResultPayload",
    "AgentUpgradePayload",
    "AgentUpgradeResult",
    "ArtifactDistributionPayload",
    "ArtifactDistributionResult",
    "CompiledExecutionPlan",
    "CompiledExecutionPlanError",
    "CompiledJobInput",
    "CompiledJobInputSlot",
    "ConfirmPackageActivationOperation",
    "ContainerRuntimeAction",
    "DistributionAssignment",
    "DistributionObject",
    "ErrorCode",
    "ExecuteContainerRuntimeRequestOperation",
    "FailureDiagnostics",
    "HostHelperGrantClaims",
    "HostHelperSignature",
    "HostOperation",
    "HostOperationKind",
    "HostRuntimeRequest",
    "InstallVonkDebOperation",
    "InventoryRequest",
    "OperationCheckpoint",
    "OperationMemberProgress",
    "OperationProgress",
    "PackageActivationReceipt",
    "PackageRollbackAuthority",
    "PackageRollbackSource",
    "RecipeBuildCleanupEvidence",
    "RecipeBuildCleanupRequest",
    "RecipeBuildEvidence",
    "RecipeBuildRequest",
    "RecipeImageImportEvidence",
    "RecipeImageImportRequest",
    "RecipeInstallPayload",
    "RecipeJobEvidence",
    "RecipeJobFile",
    "RecipeJobInputFile",
    "RecipeJobOutputLimits",
    "RecipeJobOutputManifest",
    "RecipeJobOutputMapping",
    "RecipeJobRunRequest",
    "RecipeJobRunResult",
    "RecipeOperationRequest",
    "RecipeReconcilePayload",
    "RecipeReconcileResult",
    "RecipeReconciliationIdentity",
    "RecipeRunObservationGrantRequest",
    "RecipeRunObservationGrantWire",
    "RecipeRunObservationReceiptClaims",
    "RecipeRunObservationWire",
    "RecipeRunObservationsWire",
    "RecipeStartPayload",
    "RecipeStartResult",
    "RecipeStopPayload",
    "RecipeStopResult",
    "RecipeUninstallPayload",
    "RecipeUninstallResult",
    "RestartUnit",
    "SignedHostHelperGrant",
    "SignedRecipeRunObservationReceipt",
    "StrictJSONModel",
    "TelemetryRequest",
    "TelemetrySample",
    "WireModel",
    "canonical_message",
    "canonical_payload",
    "format_model_identity",
    "host_helper_grant_signing_bytes",
    "normalize_operation_progress",
    "parse_model_identity",
    "parse_recipe_operation_result",
    "recipe_job_manifest_document",
    "recipe_job_manifest_sha256",
    "recipe_run_observation_receipt_signing_bytes",
    "schema_validator",
    "validate_compiled_execution_plan",
    "validate_result_for_operation",
    "validate_schema_message",
]
