"""The route activation states, generated. Do not edit.

Generated by scripts/generate-python-vocabulary from
vonk_agent_protocol.state_machines.GatewayRouteState. The LiteLLM supervisor
loads route_activation.py with no package around it, so it carries this file
beside it instead of a copy of the words."""

from typing import Literal

ActivationState = Literal["maintenance", "published"]
