from __future__ import annotations

import base64
import hashlib
import io
import json
import re
import subprocess
import sys
import wave
import zipfile
from pathlib import Path

import pytest

from cluster_profiles.fleet_qualification import (
    ArtifactJobSmokeAdapter,
    EvidenceLedger,
)
from cluster_profiles.qualification_fixtures import (
    Fixture,
    FixtureError,
    FixtureRegistry,
    RecipeFixture,
    _glb_metadata,
    _parse_assertion,
    _parse_recipe_fixture,
    _safe_zip_entries,
    _validate_hunyuan_ocr_zip,
    _validate_magic,
    _validate_moss_transcript,
    _wav_metadata,
    validate_outputs,
)

PNG = base64.b64decode(
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAIAAAAlC+aJAAAACXBIWXMAAAABAAAAAQBPJcTWAAAAYElEQVR4nO3PwQkAIBDAMAX3H/lwCB9BaCZo96y/HR3wqgGtAa0BrQGtAa0BrQGtAa0BrQGtAa0BrQGtAa0BrQGtAa0BrQGtAa0BrQGtAa0BrQGtAa0BrQGtAa0BrQHtAgK6AfwYG1VIAAAAAElFTkSuQmCC"
)


def _registry() -> FixtureRegistry:
    prompt_content = b"Draw a red square.\n"
    prompt = Fixture(
        "prompt",
        "prompt.txt",
        "identity",
        "prompt.txt",
        "text/plain",
        len(prompt_content),
        hashlib.sha256(prompt_content).hexdigest(),
        prompt_content,
    )
    recipe = RecipeFixture(
        "vonk-forge/image",
        "a" * 64,
        "image-job",
        {},
        (("prompt", prompt),),
        {
            "max_files": 1,
            "max_file_bytes": 1024,
            "max_total_bytes": 1024,
            "allowed_media_types": ["image/png"],
        },
        60,
        (
            {"kind": "file-count", "exact": 1},
            {"kind": "media-type", "allowed": ["image/png"]},
            {"kind": "format", "format": "png"},
        ),
    )
    return FixtureRegistry(
        {"prompt": prompt},
        {recipe.key: recipe},
        {},
        manifest_sha256="b" * 64,
    )


def test_packaged_generic_fixtures_are_digest_and_format_valid() -> None:
    registry = FixtureRegistry.packaged()

    assert set(registry.fixtures) == {
        "foley-video-1s",
        "generic-image-png",
        "generic-mesh-glb",
        "generic-prompt-text",
        "moss-session-v1",
        "service-digit7-png",
        "skintokens-rigged-figure",
        "wan-dancer-music-1s",
    }
    assert all(
        hashlib.sha256(value.content).hexdigest() == value.sha256
        for value in registry.fixtures.values()
    )
    assert len(registry.recipes) == 38
    assert len(registry.special) == 0
    assert len(registry.service_recipes) == 27
    assert all(fixture.provenance is not None for fixture in registry.fixtures.values())
    with wave.open(
        io.BytesIO(registry.fixtures["wan-dancer-music-1s"].content)
    ) as music:
        assert music.getnframes() / music.getframerate() == 1
    assert _wav_metadata(registry.fixtures["wan-dancer-music-1s"].content) == {
        "channels": 1,
        "sample_rate": 8000,
        "sample_width_bytes": 1,
        "frame_count": 8000,
        "duration_seconds": 1.0,
    }
    assert registry.fixtures["foley-video-1s"].name == "foley-video-1s.mp4"


def test_mesh_fixtures_are_semantic_provenanced_and_executable() -> None:
    registry = FixtureRegistry.packaged()
    cube = registry.fixtures["generic-mesh-glb"]
    rigged = registry.fixtures["skintokens-rigged-figure"]

    assert len(cube.content) == 784
    assert (
        cube.sha256
        == "626e31b8722f1618bfb4f2ea86905fdd1de15703cb98a8ec946072526602126a"
    )
    assert cube.provenance == {
        "origin": "generated",
        "source_url": "urn:vonk:qualification-fixture",
        "source_revision": cube.sha256,
        "license_spdx": "CC0-1.0",
        "attribution": "Generated by Vonk Forge as an auditable unit-cube qualification mesh.",
    }
    assert _glb_metadata(cube.content)["primitive_count"] == 1

    assert len(rigged.content) == 7864
    assert (
        rigged.sha256
        == "3360574c6fb468ed5577bc489256946c9c734d8b21fe64fec0ea31845b7b26d8"
    )
    assert rigged.provenance is not None
    assert (
        rigged.provenance["source_revision"]
        == "5bad5aaa0bbb5d0f9cdc934e626f27d0df1e79b8"
    )
    assert rigged.provenance["license_spdx"] == "CC-BY-4.0"
    assert _glb_metadata(rigged.content) == {
        "mesh_count": 1,
        "primitive_count": 1,
        "accessor_count": 2,
        "binary_bytes": 6864,
        "material_count": 1,
        "texture_count": 0,
        "image_count": 0,
        "skin_count": 0,
    }
    assert "trimesh 5.0.0" in rigged.provenance["attribution"]

    skin = registry.recipes["vonk-forge/skintokens-pytorch-single"]
    texture = registry.recipes["vonk-forge/step1x-3d-texture-pytorch-single"]
    assert skin.inputs[0][1] is rigged
    assert skin.assertions[-1]["profile"] == "skinned"
    assert [fixture.fixture_id for _, fixture in texture.inputs] == [
        "generic-image-png",
        "generic-mesh-glb",
    ]
    assert texture.assertions[-1]["profile"] == "textured"
    assert skin.preview()["inputs"][0]["provenance"] == rigged.provenance


def test_cube_fixture_generator_is_byte_identical(tmp_path: Path) -> None:
    root = Path(__file__).resolve().parents[2]
    output = tmp_path / "cube.glb"
    subprocess.run(
        [
            sys.executable,
            str(root / "tools/generate-qualification-cube-glb"),
            str(output),
        ],
        check=True,
    )
    registry = FixtureRegistry.packaged()
    assert output.read_bytes() == registry.fixtures["generic-mesh-glb"].content


def test_skintokens_derivation_recipe_pins_upstream_and_transform() -> None:
    root = Path(__file__).resolve().parents[2]
    source = (root / "tools/derive-skintokens-rigged-figure").read_text()
    assert "d6be85417d3e256861ee733eea6916093a7af7c79c16366181fd8abcaeb38cf5" in source
    assert 'trimesh.__version__ != "5.0.0"' in source
    assert 'force="mesh", process=True' in source


def test_glb_fixture_validation_rejects_header_only_transport_stub() -> None:
    with pytest.raises(FixtureError, match="GLB fixture structure"):
        _validate_magic(b"glTF\x02\x00\x00\x00\x0c\x00\x00\x00", "glb")


def test_registry_requires_provenance_and_rejects_unused_blobs(tmp_path: Path) -> None:
    asset = tmp_path / "pixel.png"
    asset.write_bytes(PNG)
    fixture = {
        "path": "pixel.png",
        "encoding": "identity",
        "name": "pixel.png",
        "media_type": "image/png",
        "size_bytes": len(PNG),
        "sha256": hashlib.sha256(PNG).hexdigest(),
    }
    document = {
        "schema_version": 1,
        "fixtures": {"unused": fixture},
        "recipes": {},
        "special_fixtures": {},
        "service_case_templates": {},
        "service_recipes": {},
    }
    manifest = tmp_path / "fixtures.json"
    manifest.write_text(json.dumps(document), encoding="utf-8")

    with pytest.raises(FixtureError, match="provenance is required"):
        FixtureRegistry.packaged(manifest)

    fixture["provenance"] = {
        "origin": "generated",
        "source_url": "urn:vonk:qualification-fixture",
        "source_revision": fixture["sha256"],
        "license_spdx": "CC0-1.0",
        "attribution": "Generated test fixture.",
    }
    manifest.write_text(json.dumps(document), encoding="utf-8")
    with pytest.raises(FixtureError, match="declares unused fixtures: unused"):
        FixtureRegistry.packaged(manifest)


def test_assertion_parser_rejects_unknown_fields_and_missing_semantics() -> None:
    with pytest.raises(FixtureError, match="assertion fields"):
        _parse_assertion(
            "vonk-forge/image",
            {"kind": "image-metadata", "width": 64, "height": 64, "typo": 1},
        )

    registry = _registry()
    with pytest.raises(FixtureError, match="lacks semantic coverage"):
        _parse_recipe_fixture(
            "vonk-forge/image",
            {
                "content_sha256": "a" * 64,
                "interface": "image-job",
                "parameters": {},
                "inputs": [{"slot": "prompt", "fixture": "prompt"}],
                "output_limits": {
                    "max_files": 1,
                    "max_file_bytes": 1024,
                    "max_total_bytes": 1024,
                    "allowed_media_types": ["image/png"],
                },
                "timeout_seconds": 60,
                "assertions": [{"kind": "file-count", "exact": 1}],
            },
            registry.fixtures,
        )


def _ocr_zip(*, characters_delta: int = 0, extra_name: str | None = None) -> bytes:
    markdown = "# OCR\n\n7\n"
    manifest = {
        "documents": [
            {
                "characters": len(markdown) + characters_delta,
                "early_stopped_tail_repetition": False,
                "input": "digit7.png",
                "output": "documents/001-digit7.md",
            }
        ],
        "inference": "vllm-dflash",
        "model": "tencent/HunyuanOCR",
        "model_revision": "449e7d471a8a1ef5bd5d652e4881183d7252cbc7",
        "runtime_source_revision": "c55965d3da1e6f41987abec8068f2e70851318bc",
        "sampling": {
            "repetition_penalty": 1.08,
            "temperature": 0.0,
            "top_k": -1,
            "top_p": 1.0,
        },
        "schema_version": 1,
        "task_type": "doc_parse",
    }
    destination = io.BytesIO()
    with zipfile.ZipFile(destination, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("manifest.json", json.dumps(manifest))
        archive.writestr("documents/001-digit7.md", markdown)
        if extra_name is not None:
            archive.writestr(extra_name, "unsafe")
    return destination.getvalue()


def test_hunyuan_ocr_zip_is_closed_and_semantic() -> None:
    _validate_hunyuan_ocr_zip(_ocr_zip())
    with pytest.raises(FixtureError, match="character|semantic"):
        _validate_hunyuan_ocr_zip(_ocr_zip(characters_delta=1))
    with pytest.raises(FixtureError, match="unsafe"):
        _safe_zip_entries(_ocr_zip(extra_name="../escaped"))


def test_moss_transcript_requires_authority_ack_and_terminal_record() -> None:
    records = [
        {
            "sequence": 0,
            "elapsed_seconds": 0.0,
            "type": "session-start",
            "model_revision": "06b067617677661194cf837970fe3a10f1a0e56d",
        },
        {
            "sequence": 1,
            "elapsed_seconds": 0.1,
            "type": "frame-ack",
            "event_index": 0,
            "timestamp": 0.0,
            "dropped_oldest": False,
        },
        {"sequence": 2, "elapsed_seconds": 1.0, "type": "session-stop"},
    ]
    content = b"".join(
        json.dumps(record, separators=(",", ":")).encode() + b"\n" for record in records
    )
    _validate_moss_transcript(content)

    corrupted = content.replace(b'"event_index":0', b'"event_index":1')
    with pytest.raises(FixtureError, match="acknowledgement"):
        _validate_moss_transcript(corrupted)


def test_packaged_recipe_bindings_match_the_campaign_matrix_exactly() -> None:
    registry = FixtureRegistry.packaged()
    matrix = (
        Path(__file__).resolve().parents[2]
        / "docs/runbooks/recipe-qualification-matrix.md"
    ).read_text(encoding="utf-8")
    catalog_keys = {
        f"vonk-forge/{slug}"
        for slug in re.findall(r"^\| `([^`]+)` \|", matrix, flags=re.MULTILINE)
    }
    unsupported_topologies = {
        "vonk-forge/glm-5-2-aqlm-vllm-triple",
        "vonk-forge/glm-5-2-quanttrio-vllm-four",
        "vonk-forge/glm-5-3-flash-nvfp4-vllm-four",
        "vonk-forge/inkling-975b-a41b-nvfp4-sglang-eight",
    }
    fixture_keys = (
        set(registry.recipes) | set(registry.special) | set(registry.service_recipes)
    )

    assert len(catalog_keys) == 69
    assert fixture_keys == catalog_keys - unsupported_topologies


def test_registry_fails_closed_for_missing_changed_and_special_fixtures() -> None:
    registry = _registry()

    recipe, blocker = registry.resolve("vonk-forge/image", "a" * 64, "image-job")
    assert recipe is not None and blocker is None
    assert (
        registry.resolve("vonk-forge/image", "c" * 64, "image-job")[1]["code"]
        == "fixture.recipe_digest_mismatch"
    )
    assert (
        registry.resolve("vonk-forge/missing", "a" * 64, "image-job")[1]["code"]
        == "fixture.missing"
    )


class _DownloadClient:
    def download_file(
        self,
        _path: str,
        destination: Path,
        *,
        media_type: str,
        expected_sha256: str,
        expected_size: int,
        overwrite: bool,
    ) -> dict[str, object]:
        assert media_type in {"application/octet-stream", "image/png"}
        assert expected_sha256 == hashlib.sha256(PNG).hexdigest()
        assert expected_size == len(PNG)
        assert overwrite is False
        destination.write_bytes(PNG)
        return {"sha256": expected_sha256}


def test_output_assertions_download_and_validate_exact_artifacts() -> None:
    recipe = _registry().recipes["vonk-forge/image"]
    digest = hashlib.sha256(PNG).hexdigest()
    result = {
        "id": "job-1",
        "output_manifest_sha256": "c" * 64,
        "output_files": [
            {
                "name": "result.png",
                "media_type": "image/png",
                "size_bytes": len(PNG),
                "sha256": digest,
            }
        ],
    }

    evidence = validate_outputs(recipe, result, _DownloadClient())

    assert evidence["output_files"][0]["sha256"] == digest
    assert evidence["output_manifest_sha256"] == "c" * 64


def test_output_assertions_reject_mime_mismatch() -> None:
    recipe = _registry().recipes["vonk-forge/image"]
    with pytest.raises(FixtureError, match="media-type"):
        validate_outputs(
            recipe,
            {
                "id": "job-1",
                "output_files": [
                    {
                        "name": "result.bin",
                        "media_type": "application/octet-stream",
                        "size_bytes": len(PNG),
                        "sha256": hashlib.sha256(PNG).hexdigest(),
                    }
                ],
            },
            _DownloadClient(),
        )


class _ArtifactClient(_DownloadClient):
    def __init__(self) -> None:
        self.calls: list[tuple[str, str]] = []
        self.status_reads = 0
        self.uploaded: list[str] = []

    def request(
        self,
        method: str,
        path: str,
        payload: object = None,
        *,
        extra_headers: object = None,
        query: object = None,
    ) -> dict[str, object]:
        self.calls.append((method, path))
        if path == "/api/v1/artifact-jobs/capabilities":
            return {"schema_version": 1, "transport": {}, "storage": {}}
        if path.endswith("/artifact-jobs"):
            assert extra_headers == {"X-Request-ID": extra_headers["X-Request-ID"]}
            return {"id": "job-1", "state": "draft"}
        if path == "/api/v1/artifact-jobs/job-1" and method == "GET":
            self.status_reads += 1
            if self.status_reads == 1:
                return {"id": "job-1", "state": "draft"}
            return {
                "id": "job-1",
                "state": "succeeded",
                "contract_sha256": "d" * 64,
                "input_manifest_sha256": "e" * 64,
            }
        if path.endswith("/finalize"):
            return {"id": "job-1", "state": "ready"}
        if path.endswith("/submit"):
            return {"id": "job-1", "state": "queued"}
        if path.endswith("/result"):
            return {
                "id": "job-1",
                "output_manifest_sha256": "f" * 64,
                "output_files": [
                    {
                        "name": "result.png",
                        "media_type": "image/png",
                        "size_bytes": len(PNG),
                        "sha256": hashlib.sha256(PNG).hexdigest(),
                    }
                ],
            }
        raise AssertionError((method, path, payload, query))

    def upload_file(
        self,
        path: str,
        source: Path,
        *,
        media_type: str,
        expected_sha256: str,
        expected_size: int,
    ) -> dict[str, object]:
        assert source.is_file()
        assert hashlib.sha256(source.read_bytes()).hexdigest() == expected_sha256
        assert source.stat().st_size == expected_size
        assert media_type == "text/plain"
        self.uploaded.append(path)
        return {"id": "job-1", "state": "draft"}


def test_artifact_adapter_runs_and_ledgers_durable_controller_lifecycle(
    tmp_path: Path,
) -> None:
    registry = _registry()
    adapter = ArtifactJobSmokeAdapter(registry)
    preview = adapter.preview(
        {"visual_recipe": {"interfaces": [{"adapter": "image-job"}]}},
        recipe_key="vonk-forge/image",
        recipe_content_sha256="a" * 64,
    )
    client = _ArtifactClient()
    ledger = EvidenceLedger(tmp_path / "evidence.jsonl")

    result = adapter.run(
        client,
        "run-1",
        preview,
        ledger=ledger,
        plan_digest="f" * 64,
        recipe_key="vonk-forge/image",
        timeout_seconds=300,
        poll_interval_seconds=0.1,
        clock=iter([0, 0, 1]).__next__,
        sleeper=lambda _seconds: None,
    )

    assert result["job_id"] == "job-1"
    assert result["output_manifest_sha256"] == "f" * 64
    assert len(client.uploaded) == 1
    assert {row["event"] for row in ledger.records} >= {
        "artifact-job.created",
        "artifact-job.input-uploaded",
        "artifact-job.finalized",
        "artifact-job.submitted",
        "artifact-job.completed",
    }
