"""Generated by scripts/generate-python-vocabulary. Do not edit."""

from enum import StrEnum


class HookFailureCode(StrEnum):
    HOOK_VM_BUSY = "hook.vm_busy"
    HOOK_VM_PROCESS_KILLED = "hook.vm_process_killed"
    HOOK_VM_TIMEOUT = "hook.vm_timeout"


class HookFailureKind(StrEnum):
    TEMPORARY_DEPENDENCY = "temporary-dependency"
