"""The contract words the CLI compares, generated. Do not edit.

Generated by scripts/generate-python-vocabulary from
vonk_agent_protocol.lifecycle_vocabulary and state_machines; the CLI ships
without the contract package, so it imports these instead of copying them."""

from __future__ import annotations

STOP_UNCONFIRMED = "unconfirmed"
PROFILE_NOT_ISSUED = "not-issued"
ENROLLMENT_PENDING = "pending"
UNKNOWN = "unknown"
PROFILE_REVIEW_STALE = "profile.review_stale"
NEEDS_OPERATOR = "needs-operator"
QUEUED = "queued"
RUNNING = "running"
BACKOFF = "backoff"
OBSERVING = "observing"
SUCCEEDED = "succeeded"
FAILED = "failed"
CANCELLED = "cancelled"
LEGACY_NEEDS_OPERATOR = "waiting-for-operator"
LEGACY_CANCELLING = "cancelling"
LEGACY_PARTIAL = "partial"
EXPIRED = "expired"
DRAFT = "draft"
READY = "ready"
PUBLISHED = "published"
ENDPOINT_INSTALLED_ONLY = "installed-only"
ENDPOINT_NOT_PUBLISHED_YET = "not-published-yet"
ENDPOINT_EXPIRED = "expired"
ENDPOINT_WITHDRAWN = "withdrawn"
ENDPOINT_UNAVAILABLE = "unavailable"
